### ISSUE TITLE
Digital items quit working again for .com

### ISSUE THREAD

**Issue by ScottMcNay** [philipmulcahy/azad#101]
Digital items quit working again for .com -- but only for English; appears to work ok in Spanish.

**Comment by ScottMcNay** [comment]
Update: it appears that digital is only fetched for www.amazon.com and www.amazon.com.mx. Is that correct? Do other sites offer digital sales?

**Comment by philipmulcahy** [comment]
1) Are they still broken? If so the easiest way out of this is to share json dump files with me so I can debug it and test the fix.

2) The URL schemas seem to be different for different countries (com is the outlier), hence templates_by_site - I just re-tested .co.uk on my account and it seems fine. (after a panicky moment when I tried to use the half migrated typescript branch, which absolutely didn't work). Is this question the same as your comment "what about digital orders?" on https://github.com/philipmulcahy/azad/pull/99/

**Comment by ScottMcNay** [comment]
Yes, same question; it failed when I commented out .com and tested
smile.amazon.com, worked when testing www.amazon.com, so I made the same
change to the Other (added the second URL), so that I would continue to get
digital when I had the .com commented out. So, still wondering if non-.com
handle digital differently, or if they've been missing and no-one has
noticed and reported.

--Scott.

**Comment by philipmulcahy** [comment]
.co.uk is working right now. there are loads of .de users who aren't shy about complaining so we're probably good there. I leave .com in your hands - if it works for you, we're good. Remember that the user never sees the differences that the url language params affect (except if the scrapes fail)

**Comment by philipmulcahy** [comment]
I don't understand your test strategy here: if you comment out .com and visit .com then it's not going to work - it's not allowed to say "I see Scott's on amazon.com, but I've got no template for that site, so I'll use smile.amazon.com instead" or vice versa. We could code such fallbacks but I don't see the point, if we know about a site we should have the pattern in the map.

**Comment by philipmulcahy** [comment]
for other, I'd copy the non us sites, which are mostly identical?
I remember spending a fun hour working the difference in behaviour out for .com vs .co.uk and then a slightly less fun time when I worked on .fr. Others did the leg work for all the other sites, or I guessed and no-one complained.

**Comment by ScottMcNay** [comment]
No, they both fell back to "Other".

--Scott.
