### ISSUE TITLE
Cannot generate reports later than 2012

### ISSUE THREAD

**Issue by motet** [philipmulcahy/azad#109]
https://www.amazon.ca/gp/css/order-history
https://www.amazon.com/gp/css/order-history
extension: 1.9.4
browser: Vivaldi 3.0.1874

steps:
 * navigate to an account order page
 * open extension and clear cache
 * year buttons 2004 - 2012 will scrape but >= 2013 will not scrape for either site:
   * UI does not respond
   * status box is idle
   * report page is not rendered
   * coincidentally, 2013+ years are the top row of orange buttons

![image](https://user-images.githubusercontent.com/67708642/86281473-70c80f00-bb92-11ea-9a55-14255c9f220b.png)

**Comment by philipmulcahy** [comment]
Have you tried it on Chrome?

**Comment by motet** [comment]
Hello Philip,

I tried Chrome 83.0.4103.116.

https://www.amazon.ca/gp/css/order-history <https://www.amazon.ca/gp/css/order-history>
I was able to pull data for any year, 2010 - 2020 inclusive.

https://www.amazon.com/gp/css/order-history <https://www.amazon.com/gp/css/order-history>
UI responds when scraping any year, 2004 - 2020 inclusive, but it always renders an empty report with, "No data available in table".

If I request a report from the above link directly, it fails for <= 2009.

Cheers,
Jo

On 2020-Jul-01, at 14:23, Philip Mulcahy <notifications@github.com> wrote:

Have you tried it on Chrome?

**Comment by philipmulcahy** [comment]
Do you have more than one amazon tab open while this is all happening? I’m not completely sure how it’d handle that.

Yours,

Philip

**Comment by motet** [comment]
No, just one tab. And I made sure there were no other Amazon tabs open in the other browsers.

On 2020-Jul-01, at 15:40, Philip Mulcahy <notifications@github.com> wrote:

Do you have more than one amazon tab open while this is all happening? I’m not completely sure how it’d handle that.

Yours,

Philip

**Comment by philipmulcahy** [comment]
I’ve got a couple of orders in .com (my home site is .co.uk <http://co.uk/>), and 1.9.4 is showing them fine.
I reckon the next thing to try is (sorry!) zap all cookies with amazon in their name and to restart chrome.
If that doesn’t work, please attach your console log. (I made some improvements to the help page this week which is where you can find out about logs).
It’s going to be a while before I get time to spend on this: 1.9.6 is blocked by some google purgatory to do with the extension not being for a single purpose (apparently) - they are having a (justified) crack down on naughty extensions, and azad is collateral damage.

You can try 1.9.6 out yourself early if you can bear to follow the developer instructions (also on the home page) - there’s some stuff you have to install to get the build working though (git and npm are the main tools I think you have to have). Scott (a frequent contributor) works on windows. I am mostly on os-x.

Yours,

Philip

**Comment by motet** [comment]
You are the man!

Clearing cookies did it.

Thanks for all your help.

Cheers,
Jo

On 2020-Jul-01, at 16:06, Philip Mulcahy <notifications@github.com> wrote:

I’ve got a couple of orders in .com (my home site is .co.uk <http://co.uk/>), and 1.9.4 is showing them fine.
I reckon the next thing to try is (sorry!) zap all cookies with amazon in their name and to restart chrome.
If that doesn’t work, please attach your console log. (I made some improvements to the help page this week which is where you can find out about logs).
It’s going to be a while before I get time to spend on this: 1.9.6 is blocked by some google purgatory to do with the extension not being for a single purpose (apparently) - they are having a (justified) crack down on naughty extensions, and azad is collateral damage.

You can try 1.9.6 out yourself early if you can bear to follow the developer instructions (also on the home page) - there’s some stuff you have to install to get the build working though (git and npm are the main tools I think you have to have). Scott (a frequent contributor) works on windows. I am mostly on os-x.

Yours,
Philip

**Comment by philipmulcahy** [comment]
closing: WAI
