### ISSUE TITLE
euro currency (on amazon.it) blows up aggregation feature in the fancy table

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#11]
see: https://imgur.com/a/oR6Sw

**Comment by FIndustries** [comment]
This is how amazon shows the amount: https://imgur.com/a/7qhir

**Comment by philipmulcahy** [comment]
@FIndustries v1.7.6 (propagating now) should/might fix it - let me know :)

**Comment by FIndustries** [comment]
Fixed! Thank you
