### ISSUE TITLE
amazon.it - date.ts:67 could not parse date

### ISSUE THREAD

**Issue by antwal** [philipmulcahy/azad#112]
Hi @philipmulcahy for fix this warning you can edit this line

https://github.com/philipmulcahy/azad/blob/9583e14982b3c57b6240fe43cd6e77537d5bc124/src/js/order.ts#L88

with:

`/(?:Ordered on|Commandé le|Ordinato il|Digital Order:) (.*)/i,`

without me creating a PR for this change

Thanks.

**Comment by philipmulcahy** [comment]
no test pack supplied
