### ISSUE TITLE
amazon.it - payments column UNKNOWN and gift vouchers

### ISSUE THREAD

**Issue by antwal** [philipmulcahy/azad#113]
Hi @philipmulcahy 

i have updated the code for italian language on:  https://github.com/philipmulcahy/azad/blob/9583e14982b3c57b6240fe43cd6e77537d5bc124/src/js/extraction.ts#L68

and working:

![image](https://user-images.githubusercontent.com/410736/88401917-abf0e300-cdca-11ea-8d54-1bee1351310c.png)

your debug item:

`Item(s) Subtotal: GBP 9.63 Shipping & Handling: GBP 4.24 ----- Total before tax: GBP 13.87 Estimated tax to be collected: GBP 1.22 ----- Grand Total: GBP 15.09 Payment Method: American Express | Last digits: 1416 Billing address Mr Philip Mulcahy Somewhere in the UK`

my debug item:

`Subtotale articoli: EUR 2,83 Costi di spedizione: EUR 0,00 ----- Totale: EUR 2,83 Importo Buono Regalo: -EUR 2,83 ----- Totale: EUR 0,00 Modalità di pagamento: Visa / Electron | Ultime cifre: 5829 Buono Regalo Indirizzo associato alla modalità di pagamento: Antolini Walter <address>, <city> <postal_code> Italia`

thanks.

**Comment by yogendrakumar96** [comment]
can I know where to change the code in order to get rid of unknown in case of gift vouchers

**Comment by antwal** [comment]
> can I know where to change the code in order to get rid of unknown in case of gift vouchers

this is the code I used:

```
    const strategy_2 = () => {
        const new_style_payments = util.findMultipleNodeValues(
            '//*[contains(text(), "Modalità di pagamento")]/../self::*',
            doc.documentElement
        ).map(
            e => e.textContent.replace(/\s+/g, ' ').trim()
        );
        const card_names = new_style_payments.map(
            s => /Modalità di pagamento: ([A-Za-z0-9 /]*) \|/.exec(s)[1].trim()
        );
        const card_number_suffixes = new_style_payments.map(
            s => /Ultime cifre: (\d+)/.exec(s)[1]
        );
        const payment_amounts = new_style_payments.map(
            s => /Totale: (.*) Modalità di pagamento/.exec(s)[1].trim()
        );
```

**Comment by yogendrakumar96** [comment]
Same code I am also using but getting UNKNOWN can you send total code of extraction.ts file

**Comment by antwal** [comment]
@yogendrakumar96 I have also modified other files, you have to check all the issues "amazon.it" maybe that's why it doesn't work for you; or you are using a newer / older version

my version is 1.9.12

[extraction.ts.txt](https://github.com/philipmulcahy/azad/files/4994723/extraction.ts.txt)

**Comment by yogendrakumar96** [comment]
Not getting payment details for gift vouchers and c.o.d

**Comment by antwal** [comment]
> Not getting payment details for gift vouchers and c.o.d

surely you have something wrong; I have also tried on Windows 10 and it works perfectly;

if it still doesn't work for you, create the debug file and send it to the author, so that he can check the problem and correctly implement the Italian language

**Comment by philipmulcahy** [comment]
no dump file forthcoming - gonna close this
