### ISSUE TITLE
Unable to download data from Chrome to a csv file

### ISSUE THREAD

**Issue by awesomegiles26** [philipmulcahy/azad#114]
Hi,
Unable to download the data from Chrome to a csv file. Pressing the button on the data page in chrome 'download spreadsheet .csv' results in data showing in chrome in correct format but no download initiating. The table can not be copy and pasted in to excel, saving as pdf and converting to excel also was unsuccesful, as was saving data as html and converting to csv.

Can you please advise to download the data to a csv format from chrome? 

Thank you

**Comment by philipmulcahy** [comment]
I need your console log for this. Please read README and attach here.
Thanks.

**Comment by philipmulcahy** [comment]
Closing because no response from user.
