### ISSUE TITLE
No CSV-Download

### ISSUE THREAD

**Issue by littleyoda** [philipmulcahy/azad#116]
Version: 1.9.12; amazon.de
Trying to export the orders for 2020.
All the Orders are shown correctly. 

Pressing "download spreadsheet", the table is rebuilt, but no download starts.

I will send you the console.log by Mail.

**Comment by philipmulcahy** [comment]
Thanks for your help in debugging this one @littleyoda 
1.9.13 is on its way to you - google's review process has got slower recently - ETA 24h.
