### ISSUE TITLE
Tracking ID/Link

### ISSUE THREAD

**Issue by frekwentflier** [philipmulcahy/azad#118]
Is it possible to add tracking numbers to the order list?  Shipping address would be great too. Thank you.

**Comment by tdcomcl** [comment]
Hello, if please it would be very good about the numbre tranking. For me it is important that I am willing to make a payment for the report as I need it. crt @ tdcom .cl

**Comment by jjrai** [comment]
Adding a thumbs up to this request. For example USPS(Tracking#) or AMZN(Tracking #). In addition, 3 other items that would be great to have, would be the quantity of the item ordered, the price per item, and ASIN for the product.

**Comment by laxman18a** [comment]
Yes, tracking number would be awesome. Sometimes an order is split into multiple boxes, so if you end up picking up this feature please take that edge case into consideration as well.

**Comment by samit-thakkar** [comment]
Absolutely Need the Shipping address and tracking# info.
Would absolutely be willing to pay and support the extension and know a lot of people who would do so if this info is added.

**Comment by Enuratique** [comment]
Adding a +1 to this feature. All of the above suggested enhancements are good ideas (quantity, orders being split into multiple shipments, etc).

**Comment by philipmulcahy** [comment]
Per https://github.com/philipmulcahy/azad/blob/master/README.md#commercial-features-20212022,
vote for this feature here: https://forms.gle/LNjkzMoQERSoz1wA9

**Comment by vkhlystun** [comment]
google form is closed?

**Comment by philipmulcahy** [comment]
I think it's fixed: https://forms.gle/fjbVkBSJZoVEmP3m9
Thank you for calling this out @vkhlystun !

**Comment by philipmulcahy** [comment]
Survey closed, and first batch of features ready to go when the total gets to GBP5000 (about 1.5 k to go) - see https://github.com/philipmulcahy/azad/blob/master/doc/commercial_features.md

I like this feature for the next batch though - please continue "voting" your enthusiasm here.

**Comment by philipmulcahy** [comment]
merged to #221
