### ISSUE TITLE
Amazon.ca not scraping

### ISSUE THREAD

**Issue by charlesharden** [philipmulcahy/azad#119]
Amazon.ca is not scraping. Says it found the correct count but the subsequent page has no entries. [https://imgur.com/a/WdkpAMw](url)

**Comment by philipmulcahy** [comment]
Hi @charlesharden,

Can you confirm you've worked through the troubleshooting list in [README.md](https://github.com/philipmulcahy/azad/blob/master/README.md) ?
(also accessible from the "CLICK HERE if you get incorrect results" button on the control popup)

This looks like a stale login Amazon cookie to me - clearing the extension's cache and zapping all amazon cookies in chrome://settings/siteData is likely to work.

Yours,

Philip

**Comment by charlesharden** [comment]
Yeah it required me to clear all my amazon cookies for some reason. Thanks for the help. It worked after clearing.
