### ISSUE TITLE
Amazon.com scraper not reporting any items

### ISSUE THREAD

**Issue by mgiuffrida** [philipmulcahy/azad#120]
The scraper isn't reporting any items, despite the status showing that several orders were found and completed.

After installing, running, and clicking 2020, the extension popup says:

`queued:0; running:0; completed:13; errors:0; cache_hits:0`

(which is much fewer than the number of orders I've placed)

The resulting table and the CSV file are both empty apart from headers/footers.

Console logs are attached: [amazon.log](https://github.com/philipmulcahy/azad/files/5124604/amazon.log)

**Comment by philipmulcahy** [comment]
Hi @mgiuffrida,
Have you worked through troubleshooting steps in https://github.com/philipmulcahy/azad/blob/master/README.md ?
This looks like you might have stale amazon login cookies.
I'd zap all amazon cookies in chrome://settings/siteData, then clear the extension's cache and log back in to amazon and retry 2020.

If so, please let me know. I'd like to be able to detect this situation programatically, but need to catch it in the act and have the patience to debug it properly.

Yours,

Philip

**Comment by mgiuffrida** [comment]
Thanks! Clearing out the Amazon cookies and signing back in resolved the problem. Awesome tool!

Sorry I didn't check the README -- I'll go hand in my software engineer credentials :-(
