### ISSUE TITLE
cannot pull info for personal acct

### ISSUE THREAD

**Issue by jd613** [philipmulcahy/azad#122]
is there a workaround for personal accounts? the regular link doesn't work either

**Comment by philipmulcahy** [comment]
we’re going to need more info to have any hope of helping you.
Have you viewed the README.md file?

**Comment by BB8771** [comment]
@philipmulcahy - unfortunately, there's really nothing more to provide as regards attempting to use the extension now against a personal (i.e. non-business) account. I last successfully used this extension in October 2019. It seems Amazon is no longer exposing order history URLs or pages except to business accounts. If we/I attempt to navigate to "https://www.amazon.com/gp/b2b/reports" I just get redirected to "https://www.amazon.com/gp/your-account/order-history/".

More simply, the steps outlined here used to work, but no longer do:
https://www.komando.com/tech-tips/how-to-download-your-entire-amazon-purchase-history/564498/

**Comment by philipmulcahy** [comment]
Wait, you are complaining that Amazon's order download page isn't working?
I am not Amazon.
Please read the docs for the extension (it won't take you too long) before posting again on this project.

**Comment by BB8771** [comment]
Sorry for the miscommunication, Philip. No complaints here. I was providing amplifying information that might be good to share in the README (i.e. Because of changes made by Amazon, personal accounts will no longer not work/are not supported with this extension).

**Comment by philipmulcahy** [comment]
This extension still works (mostly) for personal accounts, and has never relied on the Amazon history download feature you refer to.
I created the extension precisely because Amazon didn’t make their history tool available for sites/countries other than amazon.com/USA <http://amazon.com/USA>.
Yours,
Philip
