### ISSUE TITLE
Does not seem to work at all

### ISSUE THREAD

**Issue by mckenziepiping** [philipmulcahy/azad#123]
I ran the plugin from the orders page and told it to pull my 2016 order. There are 85 orders shown on Amazon. The plugin pulls nothing.
![Screen Shot 2020-08-28 at 11 08 21](https://user-images.githubusercontent.com/70385237/91583278-f6600500-e91e-11ea-8789-e4e8878de149.png)
![Screen Shot 2020-08-28 at 11 10 37](https://user-images.githubusercontent.com/70385237/91583446-3b843700-e91f-11ea-8597-720bbf29546a.png)
![Screen Shot 2020-08-28 at 11 10 35](https://user-images.githubusercontent.com/70385237/91583447-3b843700-e91f-11ea-98ef-95d742bce309.png)

**Comment by philipmulcahy** [comment]
please confirm you have worked through the steps in README.md

**Comment by mckenziepiping** [comment]
I went through this Readme: https://github.com/philipmulcahy/azad/blob/master/README.md

It seems that my issue is not addressed. The issue shown in the screenshots is that no transactions get pulled at all. THe issues described in the Readme are all more complex than this.

**Comment by philipmulcahy** [comment]
This, or something very similar is in the file: 
open chrome://settings/siteData and type amazon in the search box, then delete them all. This will log you out - then try again.

**Comment by philipmulcahy** [comment]
Assuming it worked - closing
