### ISSUE TITLE
Fully blankreport on Amazon.com

### ISSUE THREAD

**Issue by djonesii** [philipmulcahy/azad#125]
Read the help, cleared the cache, in both chrome and the app, logged into amazon again, and still showing a fully blank report.

All dialogs show that the extension ran.... any help appreciated.

Dave

**Comment by Yair-Tendler** [comment]
I am also getting a fully blank report.

P.S.
Amazon.com removed the option to download CSV a few weeks ago.

**Comment by philipmulcahy** [comment]
please attach the console log file from a blank run on this ticket. Thank you!

**Comment by Yair-Tendler** [comment]
> please attach the console log file from a blank run on this ticket. Thank you!

[logama.log](https://github.com/philipmulcahy/azad/files/5164845/logama.log)

**Comment by philipmulcahy** [comment]
is that the whole log? if so, I've got some difficult debugging ahead of me!

**Comment by djonesii** [comment]
This is my log file as RTF with a picture of the error from the consol.
Dave
    On Wednesday, September 2, 2020, 04:09:22 PM CDT, Yair Tendler <notifications@github.com> wrote:  
 
 



please attach the console log file from a blank run on this ticket. Thank you!


logama.log

**Comment by Yair-Tendler** [comment]
I wrote this Javascript that you can paste in the console to get the data, 
go to purchase history and paste the code at the current page, then you need to run on each link to get the tracking#
& each page at a time. 
will that be helpful?
```

document.getElementsByClassName('order').forEach((element, index) => {
    var myOrder = document.getElementsByClassName('order')[index];
    var orderPlacedDate = myOrder.getElementsByClassName('a-color-secondary value')[0].innerText;
//     console.log(orderPlacedDate);
    var orderNumber =  myOrder.getElementsByTagName('bdi')[0].innerText;
//     console.log(orderNumber);

//     var getTrackingButton = myOrder.querySelectorAll('.track-package-button a')[0].href;
        var getTrackingButton = myOrder.querySelectorAll('.track-package-button a');
        if (getTrackingButton === undefined || getTrackingButton.length == 0)  {
            getTrackingButton = 'No Tracking Yet'
        }
       else {
            getTrackingButton = myOrder.querySelectorAll('.track-package-button a')[0].href;
       }
        
//     console.log(getTrackingButton);
    
    

    var getAllProducts = myOrder.getElementsByClassName('a-fixed-left-grid-col a-col-right');
//     console.log(getAllProducts);
    //console.log(getAllProducts);

    getAllProducts.forEach((order, myIndex) =>{
        
        var getSignleItem = myOrder.getElementsByClassName('a-fixed-left-grid-col a-col-right')[myIndex]
//         console.log(getSignleItem);
    

        var itemDescription = getSignleItem.getElementsByClassName('a-link-normal')[0].innerText;
//         console.log(itemDescription);
        var itemPrice = getSignleItem.getElementsByClassName('a-size-small a-color-price')[0].innerText;
//         console.log(itemPrice);
        var getImg = myOrder.querySelectorAll('.item-view-left-col-inner img')[0].src;
//         console.log(getImg);
        
        var getQty = myOrder.querySelectorAll('.item-view-left-col-inner .item-view-qty');
//         console.log(getQty);
        
        if (getQty === undefined || getQty.length == 0)  {
            getQty = 1;
        }
        else {
            getQty = myOrder.querySelectorAll('.item-view-left-col-inner .item-view-qty')[0].innerText;
        }

        console.log('-------------------------------------------');
       console.log('orderPlacedDate:' + orderPlacedDate);
       console.log('orderNumber: '+ orderNumber);
       console.log('itemDescription: '+ itemDescription)
       console.log('Image: '+ getImg);
       console.log('QTY: '+ getQty);
       console.log('itemPrice: '+itemPrice);
       console.log('Tracking URL: '+getTrackingButton);
        
    });
       
});
```

**Comment by Yair-Tendler** [comment]
@Author 

> is that the whole log? if so, I've got some difficult debugging ahead of me! It seems to be showing that it got stuck before Amazon responded with any details. Have you tried logging out and logging back in again (to amazon) and re-trying? (I know this sounds tired)

created a Javascript that gets all the info + tracking#  <-- need to go to each page to get the tracking#
https://github.com/Yair-Tendler/Amazon-Order-History

hopefully, that helps out to solve your issue.
