### ISSUE TITLE
Never pulls any order history

### ISSUE THREAD

**Issue by jorvis** [philipmulcahy/azad#127]
I tried this for the first time and can't get it to show any results.  I start on the "My orders" page like this (cropped screenshot):
 
![Screenshot from 2020-09-17 16-22-47](https://user-images.githubusercontent.com/330899/93529901-55071600-f902-11ea-9765-355acca96b01.png)

And then click the plugin and click 2020:

![Screenshot from 2020-09-17 16-23-30](https://user-images.githubusercontent.com/330899/93529944-66e8b900-f902-11ea-803d-3430465ecb49.png)

**Comment by philipmulcahy** [comment]
Hi Joshua,
Have you read and followed the troubleshooting instructions in README.md?
Yours,
Philip

**Comment by jorvis** [comment]
I cleared the amazon cookies per instruction, also cleared the plugin cache and tried again and still got the same error.

**Comment by philipmulcahy** [comment]
Bummer!
OK - it’s time to attach a console log file to your next post (how-to is in the README).
The log should include the timespan you opened the amazon tab until you got the empty table and the control popup stops doing anything.
(p.s. you need to get the log from the amazon tab, not by inspecting the popup).

Yours,

Philip

**Comment by jorvis** [comment]
Sorry for the delayed response.  I'll try to get to this tonight.

**Comment by jorvis** [comment]
Well, this is pretty annoying, but I tried it just now with the same steps and it worked and populated the table.

**Comment by philipmulcahy** [comment]
That is strange. I'll close, but if it happens, re-open this ticket and...
you know what to do.
Yours,
Philip
