### ISSUE TITLE
No results displayed in table

### ISSUE THREAD

**Issue by cornim** [philipmulcahy/azad#131]
The extension seems to retrive all my orders from this year just fine but doesn't display any.
I tried clearing the cache and updating/reinstalling the extension already.

Consule output and result:

![Console](https://user-images.githubusercontent.com/4417017/95985946-8c93b000-0e25-11eb-8498-48289dce0c46.png)
![Table](https://user-images.githubusercontent.com/4417017/95985951-8e5d7380-0e25-11eb-9a63-bacce6150f71.png)

**Comment by philipmulcahy** [comment]
1) this looks to be the same as #129
2) v1.9.15 is rolling out slowly (to 10% of users first, when Google have verified the code) - it might fix this problem when it arrives on your browser
3) well done on getting this far, but you haven't obeyed the rules -> closing

**Comment by cornim** [comment]
Ok, thanks for the reply and I'll wait and see if the next version fixes the issue.

Which rule didn't I obey?
