### ISSUE TITLE
Doesn't pull up spreadsheet after scrape is done

### ISSUE THREAD

**Issue by jratcliffe123** [philipmulcahy/azad#132]
Version 1.9.15 seems to have fixed the issue with the extension showing a spreadsheet with no records.  The extension seems to run properly (on amazon.com), and the "completed" metric is roughly what it should be for the number of orders in that year.  At the end of the run, though, it doesn't change to the spreadsheet tab, or provide any way to download the results.  It just shows the same Amazon order history page (https://www.amazon.com/gp/css/order-history).  I've tried removing all my Amazon sitedata, removing the extension, shutting down Chrome, and then restarting, re-adding the extension, and re-logging into Amazon, but that didn't work either.  

EDIT: Added console log.

[amazon order console log.txt](https://github.com/philipmulcahy/azad/files/5386225/amazon.order.console.log.txt)

**Comment by philipmulcahy** [comment]
Can you attach a console log to this ticket please? (Not paste!)

**Comment by jratcliffe123** [comment]
I think this is what you're looking for, please let me know if it isn't.  Thanks for all your work on this!

[amazon order console log.txt](https://github.com/philipmulcahy/azad/files/5386213/amazon.order.console.log.txt)

**Comment by jratcliffe123** [comment]
I added the console log.  Thanks!

**Comment by stewjoel** [comment]
First time user of this extension. Same issue.

**Comment by Sarah1135** [comment]
I have the same issue; it shows the spreadsheet for years 2004 to 2012, but for 2013 onwards there is nothing.  I am using Amazon UK, and Chrome Version 86.0.4240.75 (Official Build) (64-bit)
[Console Log.txt](https://github.com/philipmulcahy/azad/files/5390261/Console.Log.txt)
Log included

**Comment by philipmulcahy** [comment]
@jratcliffe123  I don't see a log - can you see it in the web view of github?

@Sarah1135 Your log is interesting. I think there are opportunities for me to report and handle the error better, but in the meantime, it's possible you have been partially logged out by Amazon. See the project's README.md file for how to delete cookies and re-try. I'd be grateful if you could let me know how you get on, because I'm beginning to suspect that the code I wrote to detect partially logged out state is not working any more - it's not fired for me for ages.

Also, please please include the extension version you're using - I've managed to figure it out this time from the log, but that's not always possible.
Thanks,
Philip

**Comment by jratcliffe123** [comment]
I added the log to my original post.  Here's another link to it:

https://github.com/philipmulcahy/azad/files/5386225/amazon.order.console.log.txt

**Comment by philipmulcahy** [comment]
@jratcliffe123 thanks! It looks like it's the same cause as @Sarah1135's problem.

All: I've cooked up a test version that might give us a better clue as to what's going on. It might also soldier on past the problem and produce an (incomplete) table...

...you'll need to:
1) download and unzip https://www.mulcahyfamily.org/azad/azad.6ccf3cd5.zip
2) open chrome://extensions
3) enable developer mode
4) disable the web store version of the extension
5) "load unpacked extension" and point to the unzipped folder
6) try it out
7) send me your log and let me know how you get on
8) remember to disable the experimental version and re-enable the web store one

Good luck!

**Comment by jratcliffe123** [comment]
That test version worked! 

Log is here
[amazon order log test version.txt](https://github.com/philipmulcahy/azad/files/5394320/amazon.order.log.test.version.txt)

**Comment by Sarah1135** [comment]
This seems to be much better.  I am still seeing some errors but it does seem to be working now

[Chrome Amazon Log 20201017.txt](https://github.com/philipmulcahy/azad/files/5395814/Chrome.Amazon.Log.20201017.txt)

**Comment by philipmulcahy** [comment]
That's good news!

To sort this out properly I need html from the an order list page that has a "bogey" order on it (one that's triggering the bug in the code). I am guessing (correct me if wrong) that the tables you are seeing have some "UNKNOWN_ORDER_ID" values in the first column. The challenge is to figure out a good order id that appears on the same list page (orders are show in pages of 10).

If you've got 5 minutes, could someone please do this:
1) identify a bad order from the table (really hoping it's showing total or items), 
2) then page through the order list in the amazon site (your orders 2020 or what ever year we're playing with) until you've found the page
3) pick a "good" order id from that page
4) then find it in the extensions output table and right click on the order id. You should see "save order debug id" in the context menu which you should click on.
5) after a few seconds the extension should "download" a json file.
6 DO NOT attach it to this ticket. Instead, mail it to azadextension@gmail.com - only I have access to this account, and I will not share your order's html with the internet which is what'd happen if you attached it here. Please include this ticket's id (#132) in the email subject. It won't include enough info to enable someone to access your account or payment card, but if any of the 10 orders on the page is one you'd not want someone (me) knowing about, pick another page (that contains a bad order).

This should enable me to fix it properly and get all the data scraping.

Yours,

Philip

**Comment by philipmulcahy** [comment]
hmm - "save order debug info" is broken - I will post back here when it's fixed

**Comment by philipmulcahy** [comment]
https://www.mulcahyfamily.org/azad/azad.c645de8a.zip has debug dumps working again (and some other reliability fixes plus better notifications (no more modal dialog boxes).

to use:
1) download and unzip https://www.mulcahyfamily.org/azad/azad.c645de8a.zip
2) open chrome://extensions
3) enable developer mode
4) disable the web store version of the extension
5) "load unpacked extension" and point to the unzipped folder
6) try it out
7) send me your feedback
8) remember to disable the experimental version and re-enable the web store one

**Comment by philipmulcahy** [comment]
I'm assuming this is fixed, and I've published the changes above as part of 1.9.16.
