### ISSUE TITLE
Enhancement: smaller time window - months?

### ISSUE THREAD

**Issue by alsun2001** [philipmulcahy/azad#133]
We have a lot of orders, so scraping the entire year (and also now that it's close to the end of year) takes a long time. This feature request is to be able to specify a smaller time window, such as the past month or two.

My use case is to download the latest transactions each month for budget tracking. I use the spreadsheet to match transactions on Mint.

**Comment by ADS1134** [comment]
That would be great. I opened a similiar request; may it could be merge: https://github.com/philipmulcahy/azad/issues/161

Thank you!

**Comment by philipmulcahy** [comment]
See https://github.com/philipmulcahy/azad/blob/master/doc/commercial_features.md and more specifically https://github.com/philipmulcahy/azad/blob/master/doc/img/azad_123_months.png - this (ready to be released) feature is waiting for commercial users to push https://www.justgiving.com/fundraising/azad-pah a little further along.

**Comment by TrtlyUndrCtrl** [comment]
I paid to enable this 1m, 2m, 3m feature, but when it is still going through all of the orders for the entire year (over 3000 now) the only difference now is it only gives me 1m worth of results. Not sure if the feature maybe isn't completed yet, but I figured it would not hurt to report it.

**Comment by philipmulcahy** [comment]
Hmm - it is _supposed_ to skip fetching details and attempting to fetch payment details for the orders that are not in the selected months. The per-order pages are the ones that consume the majority of the time, space and bandwidth  and cause Amazon to slow things down.
The reason for continuing to fetch all  the header pages for the year(s) is that Amazon sometimes put them in non-chronological order, but compared with the time spent fetching the individual pages, we’re talking 10% of the time.
For a “fair" comparison of performance, you need to purge the cache between experiments.
Would you be willing to send me a console log?

Yours,

Philip

**Comment by TrtlyUndrCtrl** [comment]
Sure that would be ok. How do I get that and where do I send it?

**Comment by philipmulcahy** [comment]
Great!

I have had a surge of working on AZAD this last month, and now I need to spend a bit more time on my day job and family, so not quite sure when I’ll get to this, but AZAD’s performance matters to me - I’m not likely to pass over an easy win - think next month or two.

https://github.com/philipmulcahy/azad/blob/master/README.md#how-to-save-a-log-file

Then in the next paragraph about json debug files: 
DO NOT attach this file to a github ticket - although it doesn't contain passwords or full credit card numbers, it is likely to contain your name and address and some details of stuff you've ordered. Instead, send it to ***@***.*** ***@***.***> with the subject line including the ticket link. I (Philip) do not monitor this email address so you should also post on the ticket to say you've emailed a json file.
Yours,

Philip

**Comment by philipmulcahy** [comment]
@TrtlyUndrCtrl I have your log files: thanks. Now I need to find time to dig into this. I am going to make a new issue to avoid spamming everyone else here. I'll ping you on it.
