### ISSUE TITLE
not all orders are being scraped - no error message

### ISSUE THREAD

**Issue by Gu108** [philipmulcahy/azad#135]
I love the idea of this tool. Unfortunately I was not able to scrape all orders from amazon.de
For 2017 the tool scrapes 151 orders (of 221 existing)
For 2018 the tool scrapes 54 orders (of 84 existing)
There is no error message. No cued/running/errors.

for the years 2019 it works fine (65 of 65 orders)
for the years 2020 it works fine too (110 of 110 orders)

Amazon adress:
https://www.amazon.de/gp/your-account/order-history?ie=UTF8&digitalOrders=1&opt=ab&orderFilter=year-2017&returnTo=&unifiedOrders=1&

It just shows "Showing 1 to 151 of 151 entries" at the bottom
<img width="206" alt="Screenshot 2020-11-15 at 00 43 00" src="https://user-images.githubusercontent.com/46876260/99159323-af8ed980-26db-11eb-8b4a-3da639297a5a.png">

while amazon says "221 orders placed in 2017".
<img width="231" alt="Screenshot 2020-11-15 at 00 43 13" src="https://user-images.githubusercontent.com/46876260/99159333-b87fab00-26db-11eb-96a4-235d6b5adcbe.png">

Steps I took:
1. I updated all chrome extensions, closed and reopened the amazon-page.
2. I deactivated popup-blockers
3. I cleared the chache
4. I forced logout
5. I deleted all amazon-cookies as described in the readme
6. I deactivated all amazon-sites but the two .de sites
7. I tried to save the log file by pressing Ctrl+Shift+I on my macbook pro (also tried cmd+Shift+I and option+Shift+I) when being on the tab of the report, but absolutely nothing happened, especially no log appearing on the bottom.

What can I do next?

**Comment by philipmulcahy** [comment]
I think there is a menu route to getting into the dev tools in chrome: that is where you should concentrate your effort: “ To open the developer console in Google Chrome, open the ChromeMenu in the upper-right-hand corner of the browser window and select More Tools > Developer Tools. You can also use the shortcut Option + ⌘ + J (on macOS)”

once you have them displayed, you will need to open the console display: Look for the word “Console” in the tool and click on it: it can either be a stripe at the bottom or occupy the whole of the tools’ screen area.

Yours,

Philip

**Comment by Gu108** [comment]
Thank's Philip, for your quick reply and direction.
I now have the log file. I would prefer to send it in a private way. How would I do that?
Thanks,
Gu108

**Comment by philipmulcahy** [comment]
You can send it to azadextension@gmail.com <mailto:azadextension@gmail.com> (mention the ticket id in the subject so I now what it’s for, and let me know here when you’ve sent it - I don’t monitor that mailbox).
The console log should be pretty innocuous, but if we need to go as far as dumping debug json files with the extension, definitely don’t send them in the ticket - that’s what the email address is for.
Yours,
Philip

**Comment by Gu108** [comment]
Thank's Philip.
Log sent.

**Comment by philipmulcahy** [comment]
Hi @Gu108 I've got the log file, but it's not complete - it's missing a bunch of lines at the start, which is where the trouble might be happening. I suggest using 2018 because it's got fewer orders but is still misbehaving. Would you also please tell me the ids and types (digital or physical) of a couple of 2018 orders that didn't make it into the output?
Thanks,
Philip

**Comment by Gu108** [comment]
thank's Philip, 
I sent a new logfile of 2018 with 10 missing orders (digital and physical).
Hope it works.

**Comment by philipmulcahy** [comment]
Hi @Gu108 the first line in your new offering (thank you) is 
`request_scheduler.ts:259 Finished https://www.amazon.de/gp/css/summary/print.html/ref=oh_aui_ajax_pi?ie=UTF8&orderID=303-0816731-6277153 with queue size 93`
which is after the phase when it's gathering ids of orders it thinks it needs to fetch.
The log has just over 1000 lines. I am able to save much more than 1000 lines (on macos) - I wonder if it depends on OS or perhaps how much memory is available. Can you scroll up further than that line if you take another shot?
Just to check: you are right clicking on the console pane and selecting "Save as..." ? Here's what it looks like on macos:
![image](https://user-images.githubusercontent.com/1668892/99591709-1c111d80-29e7-11eb-9ac0-f337df748da0.png)

**Comment by Gu108** [comment]
yes, this is how I was saving. 
I tried it again and it was again truncated. 
Macbook pro with 32 GB...should not be a RAM issue....

Then I found the trick:
right after starting the script I go into console while it's still running. Then the log gets much bigger. 
Just sent the new log.

**Comment by philipmulcahy** [comment]
Thanks @Gu108.
I've replied privately asking for you to send me some html.
Folks who are watching: the plan is to debug the scrape against the saved html, but we cannot share that html without sanitizing it first - if it seems like a regression test makes sense, then I'll put the effort in to do so.

**Comment by Gu108** [comment]
Thank's Philip,
I just sent you the html file.

**Comment by philipmulcahy** [comment]
sorry this is dragging on: I got sidetracked last night by a really cool (or so I thought) way to refactor the test code to be able to add your html in as a new kind of test, but it was a blind alley

**Comment by Gu108** [comment]
I'm very familiar with getting sidetracked.... 😂

**Comment by philipmulcahy** [comment]
I've made some progress - the code is getting hung up on an Audible order - it searches for the order id in the links within the section for each of the 10 orders per page, and the Audible order I'm looking at has a different url style for its details link. The order ID is there, I just need to adjust the pattern used to find it.

**Comment by philipmulcahy** [comment]
OK - I'm too tired to do any more tonight. I've made a modification to the regex that finds the IDs and it seems to work. The next step is to cook up a new build with this code in and have you (@Gu108 ) download it and try it out. If it works, great. If it doesn't you can save yourself some time gathering the deeper debug data needed to go further because hopefully you'll at least get a row in the table you can right click on to get the json debug file.

**Comment by philipmulcahy** [comment]
@Gu108 https://www.mulcahyfamily.org/azad/azad.b204977d.zip is the candidate for your testing pleasure.

1) download and unzip https://www.mulcahyfamily.org/azad/azad.b204977d.zip
2) open chrome://extensions
3) enable developer mode
4) disable the web store version of the extension
5) "load unpacked extension" and point to the unzipped folder
6) try it out
7) send me your log and let me know how you get on

**Comment by philipmulcahy** [comment]
?

**Comment by Gu108** [comment]
sorry, I have been super busy the last two weeks. 
I just now found some time to test the now script. 
It works perfectly. No further debugging needed imo.
When building the table I get several "too many redirects when fetching https://amazon....". but those disappear after a few seconds, so I don't think it's a problem.
Thank you for your fix!

**Comment by philipmulcahy** [comment]
Those redirect messages _might_ be a sign that part of the Amazon empire has logged you out and you’re getting blanks instead of data for some fields in some orders.
Glad you’re sorted out - I’ll put that fix in the next proper rollout.

**Comment by Gu108** [comment]
perfect, thank you.
