### ISSUE TITLE
Tie items to particular charge

### ISSUE THREAD

**Issue by RichMcClure** [philipmulcahy/azad#136]
I would like to be able to tie individual items in an order to a particular credit card charge.

**Comment by philipmulcahy** [comment]
Hi @RichMcClure,

I think you might get this from the new shipments feature - it's definitely not perfect, and it's behind the subscription paywall for the time being (beneficial to me for a couple of reasons: 1 - restrains the number of users that complain about inevitable teething defects of what has proven to be a complicated thing to get workin;g 2 - generates revenue - it's mostly businesses that want the shipment metadata, and they tend not to make charitable donations altruistically).

If it's just the transaction info, I think it might have already been there, but not as well populated, in which case no need to subscribe.

Have a look at [this screen shot](https://github.com/philipmulcahy/azad/blob/master/doc/img/items_csv_2023-12.png) of my recent items csv file. Although the transactions column is truncated in the screenshot (partly to fit, partly to not share my cc info), most non empty cells in this col contain an amount (with ccy), the last four digits of the card, and the issuer/network.

In the interests of trying to reduce the number of open tickets, I'm going to close this issue on the assumption it (finally - sorry for the very long wait!) works for you.
If it doesn't, please feel free to re-open with your thoughts.

Yours,
Philip
