### ISSUE TITLE
No complete download (D01-xxxxxxx-xxxxxxx Orders)

### ISSUE THREAD

**Issue by everonyt** [philipmulcahy/azad#137]
Jumps to the following site:
chrome-extension://mgkilgclilajckgnedgjgnfdokkgnibi/-/en/gp/digital/your-account/order-summary.html/ref=ppx_yo_dt_b_dor_o09?ie=UTF8&orderID=D01-xxxxxxx-xxxxxxx
(Number changed into xxxxxxx-xxxxxx)
Chrome shows the following error. 
"Zugriff auf die Datei nicht möglich Eventuell wurde sie verschoben, bearbeitet oder gelöscht."; "ERR_FILE_NOT_FOUND"

The download is not completely done, some of the values are "pending". I think the problem comes if it comes to D01 orders of amazon. only D01 orders do not show values for postage, gift, vat and refund.

**Comment by philipmulcahy** [comment]
I don't understand - is it jumping to that url or displaying a table? - I think a screenshot would be useful.
(also, please attach your console log - if you don't know how to do that, please read README.md)

**Comment by philipmulcahy** [comment]
assuming this is no longer an issue - please reopen if not.
