### ISSUE TITLE
[enhancement] Individual item subtotals and item quantities

### ISSUE THREAD

**Issue by Jerror** [philipmulcahy/azad#139]
Those of us looking to tally costs of specific items purchased (generally as parts of a larger order) would require this extension to extract a bit more data, specifically the cost of each subitem in an order. Presently the names of each item are listed in the 'items' column but there is no way to determine what each item cost from the scraped tables. Amazon, however, lists the subtotal of each item along with the name in Your Orders, at least for the CA version. It would be very nice if at minimum this subtotal is listed in 'items' with each item name.

Additionally, for orders containing multiple of some item there is nothing in 'items' to indicate that multiple were purchased, nor the quantity. Amazon(.ca) shows the quantity, when it is greater than 1, in a little graphic above the item image corresponding to the tag 
`<span class="item-view-qty">$QUANTITY</span> `
from which you could scrape the quantity directly. Reporting the quantity would be necessary to make item subtotals useful since amazon(.ca) only lists the item base price, not the total price of a stack of items.

With these enhancements one could analyze the scraped data to see precisely where their money is going, which is very handy for budgeting and taxes (eg., compiling business expenses) when one makes many amazon orders combining various unrelated items, as one often does to save on shipping. Order totals are by comparison not so useful since this data is just as easily extracted from bank records. For my use case anyway this would be the killer feature that makes the extension indispensable.

**Comment by philipmulcahy** [comment]
I have a branch with this feature ready to test if someone wants to volunteer.

p.s: I've not yet added ASIN extraction (much requested, nay _demanded_ by the drop shipping community) yet, because the charity donation flow has really dried up recently and consequently I'm not feeling that supportive of their business model.

**Comment by philipmulcahy** [comment]
<img width="1439" alt="Screenshot 2021-03-25 at 23 35 14" src="https://user-images.githubusercontent.com/1668892/112556990-3eff7400-8dc3-11eb-9bd1-b33ccb32a657.png">

**Comment by philipmulcahy** [comment]
v1.9.21 does this -> closing
