### ISSUE TITLE
No accounting for Prime member shipping discount

### ISSUE THREAD

**Issue by Jerror** [philipmulcahy/azad#140]
I'm not sure whether this is a bug or a feature request. Presently (at least for CA users) the base shipping cost is reported in 'postage' and no account is made of the discount corresponding to Amazon Prime free shipping. For example, a Prime member may see in the order details

Shipping & Handling: CDN$ 6.99
FREE Shipping: -CDN$ 6.99

and azad will scrape CDN$ 6.99 for 'postage' and 0 for 'refund', which makes it look like more is spent on shipping (and less on the items per se.) I would expect one of the following behaviours:
-a new column, eg. 'postage discount', displays the 'FREE Shipping:' data, in this case -CDN$ 6.99
-'postage' displays the difference (in this case $CDN 0.00)
-'postage' displays both (in this case CDN$ 6.99 -CDN$ 6.99)
-the shipping discount is added to 'refund'

I'd prefer the first option, personally.

**Comment by philipmulcahy** [comment]
That’s interesting - the UK site doesn’t show any cost information for prime deliveries.
You might want to try out the order debug dump feature (right click on an order link in the output table and select order dump next to the extensions icon). After a few seconds you should get a json file in your downloads folder.
Send the json file to me via azadextension@gmail.com <mailto:azadextension@gmail.com>, not by attaching to this ticket, but also post here to let me know you’ve done so - I don’t monitor the account: see README.md
With that file, I can take a look at the html your country’s site serves to see if I can easily improve the scraping code.
Fair warning - with the details of the order you send me, it may include summary info on up to 9 others. If there’s stuff you don’t want me seeing (you shouldn’t trust me saying I’m not interested, though I’m not), then pick another order that exhibits the bad behaviour you’re calling out.

Yours,

Philip

**Comment by Jerror** [comment]
Sent, with subject "No accounting for Prime member shipping discount -- order debug dump".

Cheers,
Jer

**Comment by philipmulcahy** [comment]
I haven't forgotten about this issue - I've just not had time to sit down and look at it yet :)

**Comment by halorrr** [comment]
Of note, not _every_ prime order will have this, but I experience the same thing.

Some are like this:
![image](https://user-images.githubusercontent.com/1358708/103450468-ed908e80-4c84-11eb-9682-d5a3681ed18a.png)

Others are just:
![image](https://user-images.githubusercontent.com/1358708/103450471-fbdeaa80-4c84-11eb-8ccc-9bbbccdccd14.png)

**Comment by philipmulcahy** [comment]
I've built an experimental version you can download from here: https://www.mulcahyfamily.org/azad/azad_ca48c850.zip

To use:
1) download and unzip the above link
2) open chrome://extensions
3) enable developer mode
4) disable the web store version of the extension
5) "load unpacked extension" and point to the unzipped folder
6) try it out
7) send me your feedback
8) remember to disable the experimental version and re-enable the web store one

**Comment by halorrr** [comment]
Looks to be working.

Example order:
![image](https://user-images.githubusercontent.com/1358708/104832709-fecec300-5860-11eb-9145-14f1531869f6.png)

Output:
![image](https://user-images.githubusercontent.com/1358708/104832714-0db57580-5861-11eb-916e-d1ce3cd88789.png)

**Comment by philipmulcahy** [comment]
I will merge the change into the master branch so it'll be included in the next release.

**Comment by philipmulcahy** [comment]
I have offered the "proper" version 1.9.19 to the approval gods at Google - On recent form, I would expect it to be on your browsers in less than 24 hours.
