### ISSUE TITLE
Report ASINs, price and quantity

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#141]
I think this would require an exploded table option, and some restructuring of the data model.

**Comment by ivucica** [comment]
The data shown in the GUI table, including the hyperlink URLs, is great. 

Exploded table, assuming this means getting the same order ID multiple times, but with individual items (and maybe item prices) would be great.

As far as use cases go: In my case, I am just right now trying to get physical book ISBNs for importing into goodreads.

(Long term, I'd like to be able to inventory every physical item I ever ordered from Amazon, and having unique product IDs + links to product pages would help.)

**Comment by ScottMcNay** [comment]
GoodReads has an option to import books from Amazon; have you tried it?

--Scott.

**Comment by ivucica** [comment]
Indeed it does. I wish I had found it before I spent half an afternoon copypasting ISBNs, adding to shelves, and then also creating 'physical copy' records.

It looks like discoverability of awesome features is really a big problem on Goodreads. Thanks for the advice!

Of course, this is working out for me only because I've chosen to use Goodreads... AZAD providing the information in CSV would still be useful for a non-Goodreads offline copy :)

**Comment by DioF** [comment]
I agree that this would be still very helpful. I am currently investigating how much I spent for which type of goods on Amazon to get a better understanding about my (and my family's) consumption behavior. For this it would be great to have the order items separately with price and quantity.

**Comment by philipmulcahy** [comment]
see latest post on #139. (I am not allowed to say: no charity bump, no ASINs+tracking numbers to the drop shippers, but it's certainly crossed my mind to do so.). If you want to test the row-per-item feature, let me know on the other ticket.

**Comment by philipmulcahy** [comment]
Per https://github.com/philipmulcahy/azad/blob/master/README.md#commercial-features-20212022,
vote for this feature here: https://forms.gle/LNjkzMoQERSoz1wA9

**Comment by philipmulcahy** [comment]
I've got this working - see https://github.com/philipmulcahy/azad/blob/master/doc/commercial_features.md for how to get it!

**Comment by philipmulcahy** [comment]
Released in May (1.9.26) behind preview subscription paywall - will become free when lifetime donations to https://www.justgiving.com/fundraising/azad-pah reach GBP 5000 (slightly more than  USD 5000). Currently just below GBP 3600
