### ISSUE TITLE
Payments column displays "Unknown" when gift card/Amazon balance is used

### ISSUE THREAD

**Issue by CalebKierum** [philipmulcahy/azad#142]
I love how the Payments column breaks down the potentially multiple transactions that go into one order. However it would seem for me that whenever reason when a order uses a gift card the payment row consistently reads "UNKOWN" in the downloaded CSV. 

Would be great if there were a way to still get the payment breakdown when using gift cards.

**Comment by philipmulcahy** [comment]
Are you saying that there was partial payment for that order and the remainder was taken from your gift card balance? If so, is the gift column showing the correct amount?

**Comment by philipmulcahy** [comment]
no response from Caleb -> closing
