### ISSUE TITLE
'Tax' column is taxable amount, not the tax.  

### ISSUE THREAD

**Issue by RBO3** [philipmulcahy/azad#144]
Not a big deal.  I can subtract in Excel.

I'm in Google on Mac.  Updated version today.

**Comment by philipmulcahy** [comment]
Would you mind doing the order dump thing?
That's
1) right clicking on an example bad order link in the output table and selecting the dump debug json option from the popup menu and 
2) then mailing it (the json file that should have appeared in your downloads folder after doing (1) ) to azadextension@gmail.com with a subject line that includes #144 so I know it's for this bug?

I'd also need to know the value you're getting in the tax column for the selected order at the moment (maybe a partial screen shot).

Thanks,

Philip

**Comment by philipmulcahy** [comment]
no response from user (please re-open if you are the original poster or someone else who can help me as suggested above.
