### ISSUE TITLE
'Pending' never went away for one row and (therefore?) Download window never opened. Audible issue?

### ISSUE THREAD

**Issue by RBO3** [philipmulcahy/azad#145]
I have 480 items on my 2020 list.  The process quickly listed the 480 and then took 5-10 minutes to update all the 'pending' cells.  But the Download window did not come up.  I tested with a handful of 2021 items and the process worked as expected.  Then used Select All, Copy, Paste into Excel and checked the data.  

ONE row still had 'pending' in all the pending cells.

That row looks like this:

D01-3078132-4653044 | Order Details<span   class="a-color-secondary"> (Audible.com)</span>; | 0 | 5/14/20 | $30.97 | pending | pending | pending | pending | 2020-05-14: $30.97; | pending

Somehow it did not pick up the order details correctly.    It might be that I need to be logged in to Audible.com as well as Amazon.com.  

There are many Audible audio books on the list.  None of them is identified as an audio book; I can tell by the price and the fact that I ordered both the book and the audio book.

**Comment by philipmulcahy** [comment]
Sorry I've taken so long away from azad.
I don't have any audible orders, but there's a way you can help me debug it and probably fix it relatively cleanly:

You can help by:
1) right clicking on an example bad (audible) order link (perhaps D01-3078132-4653044 ?) in the output table 
2) selecting the dump debug json option from the popup menu (which should end up dropping a json file into your downloads folder after a few seconds)
3) mailing the json file to azadextension@gmail.com with a subject line that includes #145 so I know it's for this bug
4) A console log for the initial scrape attempt could be useful as well - to capture the whole thing, you probably need to have the chrome developer console open before clicking on the scrape year button.
5) post back here to tell me you've sent the email - I don't check that mailbox unless someone tells me to.

Don't attach the json file here - you don't want the internet to see inside that file just in case Amazon have included any secrets (such as delivery addresses).

Thanks,

Philip

**Comment by philipmulcahy** [comment]
I am leaving this open because:
1) I don't have any example data for Audible, so have no reason to suspect it is working.
2) I've not changed anything that would have fixed this.

If anyone finds this after having similar problems, please provide details here and mail an order dump json file (for a misbehaving audible order) to azadextension at gmail dot com. - DON'T post the json file here - you don't want to share it with the internet - it won't have your cc details, but it may well have your home address and various other things of use to identity thieves. I will not share your data (except perhaps a small (<10) team of collaborators - only one other person has access to the test pack repo at the moment).

**Comment by neilspencer-jones** [comment]
> I am leaving this open because:
> 
> 1. I don't have any example data for Audible, so have no reason to suspect it is working.
> 2. I've not changed anything that would have fixed this.
> 
> If anyone finds this after having similar problems, please provide details here and mail an order dump json file (for a misbehaving audible order) to azadextension at gmail dot com. - DON'T post the json file here - you don't want to share it with the internet - it won't have your cc details, but it may well have your home address and various other things of use to identity thieves. I will not share your data (except perhaps a small (<10) team of collaborators - only one other person has access to the test pack repo at the moment).

Sadly once this error occurs the "Save Order Debug Info" function doesn't produce a download. It works fine if I use the option on a different year which doesn't have the audible error or before the error occurs.

**Comment by philipmulcahy** [comment]
Thanks for the hint @neilspencer-jones.

When 1.9.21 makes it through to the web store (hopefully tomorrow), would you mind grabbing a console log of one of your bad runs? [how-to-save-a-log-file](https://github.com/philipmulcahy/azad/blob/master/README.md#how-to-save-a-log-file) explains how to capture the log.

There's a small chance that the problem goes away with this release. If so, no need to send the log, just let me know!

If you get a scrape, but the audible row details are missing, then a debug dump is preferred to a log file (**remember** - don't attach a dump file here - send it the email address listed in [how-to-save-and-send-an-order-debug-json-file](https://github.com/philipmulcahy/azad/blob/master/README.md#how-to-save-and-send-an-order-debug-json-file))

**Comment by neilspencer-jones** [comment]
Hi I tried the new version and the same problem occurs. I get a scrape, the Audible payment is "Pending" and again  "Save Order Debug Info" function doesn't produce a download for this order, it does for others. But I will email the log file. Also again the download of the .csv doesn't work it just redraws the screen but no download starts.

**Comment by philipmulcahy** [comment]
can you identify one of the "bad" order ids (in an email) please?

**Comment by RBO3** [comment]
I just tried again for the first time since January.  I get this error for the same order originally posted.  The scrape seems to run to completion after this which is roughly record 125 of 509, but no data are displayed when the 508 are done.

HTTP0: too many redirects when fetching https://www.amazon.com:443/gp/redirect.html/ref=ppx_yo_dt_b_amzn_o00aud_?_encoding=UTF8&location=https%3A%2F%2Fwww.audible.com%2Forder-detail%3ForderNumber%3DD01-3078132-4653044%26orderType%3DREGULAR&source=standards&token=87AA96441C7E5FAF1A44261E5175B186D3BA082F which has been redirected You might want to consider using the "force full log out" button and logging yourself back into Amazon.

**Comment by RBO3** [comment]
Perhaps 'too many redirects' gives you a clue about the issue.  Thanks, Bob.

**Comment by RBO3** [comment]
a little more info.

The error I just posted above occurs when Show Items Not Orders is selected.

If I do not select that, then the Order list runs to completion but the one line remains Pending Pending etc.

However, when I click Download the page redisplays without the buttons and without downloading.

If there is something I can send based no this, please let me know.

Thanks

**Comment by RBO3** [comment]
One more thing.  I tracked down this order.  It was for Audible's "Premium Plus 24-credit Annual Plan Extra 3 Credits ".    The audiobooks before and after this listing in the Audible history are included in the Scrape.

**Comment by RBO3** [comment]
I notice that the Items column is empty for purchases such as Kindle Unlimited or Amazon Music even though the Order has that information.  Perhaps the line items for internal Amazon products such as the Kindle and Music subscriptions and possibly the Audible Premium do not store the product name where the Scraper expects to find it, or not at all.

**Comment by RBO3** [comment]
![Screen Shot 2021-05-29 at 2 17 49 PM](https://user-images.githubusercontent.com/72107395/120084880-b59d4400-c088-11eb-9521-d331d4c5034a.jpg)

**Comment by alexandrekm** [comment]
I have the same issue, to be able to unblock myself what I did was to archive the audible order. After that the scrapper completed.

**Comment by peteralbert** [comment]
@alexandrekm Thank you for the suggestion to archive the pending order - now I can use the tool again!

**Comment by Olli-ger** [comment]
I have the same issues for renting a movie on amazon video or buying some digital content (movie).

**Comment by philipmulcahy** [comment]
1.9.34 (deployed early this morning) has some changes intended to enable:
1) higher chance of getting past "bad" orders
2) higher chance of logging of the bad orders so we can figure out what happened

I'll wait for a few weeks to see if folks are still seeing problems (semi-optimistic strategy), and if no-one reports, then I'll close this ticket.

**Comment by philipmulcahy** [comment]
assuming fixed - 3-4 weeks of silence
