### ISSUE TITLE
Tax

### ISSUE THREAD

**Issue by Vidbot41** [philipmulcahy/azad#146]
The .csv file runs/downloads fine! However, every tax field for the entire year (2020) is listed as "pending" rather than the actual amount. The total therefore is 0.00
I need the tax amount I paid for the year for my Use tax payment to the state.

**Comment by philipmulcahy** [comment]
I am slightly confused. Would you mind showing a screenshot and attaching a console log (see the README page for how to get hold of one)?

**Comment by philipmulcahy** [comment]
no response from user
