### ISSUE TITLE
Fullfilled Orders Archived Are Not Retrieved

### ISSUE THREAD

**Issue by rfgnerd** [philipmulcahy/azad#147]
To keep prying eyes from seeing my orders for Christmas, I archived my fulfilled orders to hide them. However, when I did a report, all of the archived orders were missing.

**Comment by ScottMcNay** [comment]
Be sure Amazon still lists your archived items; they apparently get deleted
after a while.

**Comment by philipmulcahy** [comment]
Is that a bug or a feature (in your opinion)?

If the orders are not visible to you, they are unlikely to be visible to the extension - Amazon have not provided an API and so azad is scraping the pages you would use to look at your orders. This means that even if you were able to persuade me it’s a bug, I cannot see a way of fixing it.

Assuming it’s possible to un-archive them, I am not thinking positive thoughts about adding that capability to azad - having it mutate Amazon state is gonna be a whole new level of support pain. There would be hundreds of users asking why it had messed up their accounts. I already get complaints about their stuff being delivered late, or not coming with proper instructions.

Yours,

Philip

**Comment by rfgnerd** [comment]
Thank you, Phillip, for the quick response. I really appreciate that level
of support!

I agree it's not a bug but rather a limitation due to the lack of an API by
Amazon. What has been created in this add-on is pretty tremendous
considering how the add-on functions in collecting and formatting the data.
I tip my hat to you and everyone else who made this possible! Well done!

Bob

**Comment by pke** [comment]
Thanks for this very helpful add-on!

Just a note on this issue:
As far as I understand from the code its not using any API but rather webscraping. The archived orders are just under a different URL but contain roughly the same layout as the unarchived orders.

Archived = `/gp/legacy/order-history?orderFilter=archived`
Normal = `/gp/css/order-history`

Maybe it would be possible to support that after all?
