### ISSUE TITLE
All years button doesn't display a table.

### ISSUE THREAD

**Issue by DarkGreyCat** [philipmulcahy/azad#15]
When I press the all years button it successfully sifts through all the orders and completes them, but no table is displayed. However, clicking on each individual year works as expected.

amazon.co.uk | Chrome Version 63.0.3239.132 (Official Build) (64-bit)

Clicking on a year with no orders also doesn't display the table so the issue might be coming from these years. Weird as to why Amazon has tabs for years 2010-2013 when I made my account in 2014.

![image](https://user-images.githubusercontent.com/35639014/35418957-38c354c8-022d-11e8-8290-f5443292140f.png)

**Comment by philipmulcahy** [comment]
Thanks for the report - are you able to share a screen shot of the “stuck" state? (Including the orange counters in the top right hand corner).

**Comment by DarkGrayCat** [comment]
![snip](https://user-images.githubusercontent.com/35639014/35418680-afbdfe22-022b-11e8-83ec-18eb12f97bda.PNG)

**Comment by philipmulcahy** [comment]
In the current version, there's a hidden element (ul) with id=order_reporter_notification that has some basic logging in it. Do you know how to view the DOM in Chrome - you can get to it by right clicking somewhere in the view (such as on the counters) and selecting Inspect. Once there, paste order_reporter_notification into the search box (below the html/DOM view) and then open up the "tree" of elements inside it by clicking on the triangles on the left.

If you can find this (see screen shot below), we should be able to get to the bottom of the problem by adding some more logging calls in a new version I can publish (the current version doesn't do a great job of logging the phase your runs are falling over on).

![image](https://user-images.githubusercontent.com/1668892/35463165-3bb2e22e-02e7-11e8-8923-bf1e2caa5e23.png)

Thanks again!

**Comment by philipmulcahy** [comment]
logging is now done "properly" into the console - how would you feel about posting your log on this ticket?
1) Chrome developer console (three dot icon/button on right hand side|More tools|Developer Tools)
2) Click on Console (in a bar near the bottom normally)
3) Press the orange year button you want to fetch
4) Watch the console fill up with logs, and wait for stuff to stop happening in the counters on the top right hand side.
5) Right click somewhere in the console logs | Save as... (choose a file name)
6) Drag the file to a comment box in this ticket.
[although order ids end up in the log (and offer useful clues about digital/non-digital), I and others cannot use them to look at your orders or other account info.]

**Comment by DarkGreyCat** [comment]
[www.amazon.co.uk-1521310452011.log](https://github.com/philipmulcahy/azad/files/1821933/www.amazon.co.uk-1521310452011.log)

**Comment by philipmulcahy** [comment]
Thank you!
I think I've found the problem: Empty years were the culprit - my code stupidly relied on individual order data coming back before it could realise a year was complete, move on and display the table.
1.7.17 has an attempt at a fix.
Would you mind kicking its tyres (pushed about 5 minutes ago, so should be with you before 20:50 UTC) and letting me know?

Thank you again,

Philip

**Comment by DarkGreyCat** [comment]
Yup, works like a charm. Thank you :)
