### ISSUE TITLE
Download CSV button does not appear after successful scrape

### ISSUE THREAD

**Issue by davraamides** [philipmulcahy/azad#150]
The download completes and I get this status info: "queued:0; running:0; completed:2; errors:0; cache_hits:194" and I see the table of results in the browser, but the "Download CSV" button never appears so I can't download the results.

This was working before but it's been about two weeks since I last tried it.

Is there a way to force the button to appear?

macOS Big Sur 11.2.1 x86
Chrome version 88.0.4324.182
Amazon Order History Reporter version 1.9.19

**Comment by philipmulcahy** [comment]
You should work through the various hacks and workarounds on the README.md doc, but after that, I’m afraid it’s either:
1) post the console log to this ticket so I can take a look
or
2) get good at hacking javascript in the browser

**Comment by philipmulcahy** [comment]
1 month and no follow-up from user - closing
