### ISSUE TITLE
All totals showing as zero

### ISSUE THREAD

**Issue by glenviewjeff** [philipmulcahy/azad#152]
First there seemed to be a cache issue, as new purchases weren't showing up when I came back to scrape a few weeks later. After clearing the cache, now all fields in the "total" column are showing up as zero. Tax, gift, and refund are showing up properly. 

I just looked at the order page and it appears that Amazon is no longer showing order totals before clicking through to the invoice. I believe this is a recent and utterly obnoxious change.

**Comment by philipmulcahy** [comment]
Someone has posted a possible fix. I won’t have time to evaluate until the weekend. Likely to be an Amazon UI change.

Yours,

Philip

**Comment by glenviewjeff** [comment]
Yes, I believe they changed the UI, obnoxiously removing the total charge from the orders page, in yet another step to make customers' lives miserable, requiring tools like this one to manage their orders. Time was, Amazon used to actually email you receipts with order totals so you could search your emails to reconcile your credit card statements. :( Thanks for your work!

**Comment by nfuller286** [comment]
Having same issue.  Feels like a UI change.  Thanks!

**Comment by philipmulcahy** [comment]
v1.9.20 is pending chrome webstore review and assuming it gets approved, will automatically deploy soon afterwards. It typically takes 12-24 hrs.
Thanks to @pagliaccl for reporting the issue so quickly AND proving an effective pull request.

**Comment by philipmulcahy** [comment]
If you cannot wait: https://www.mulcahyfamily.org/azad/azad_7916f50b.zip (for those who know how to use unpacked chrome extensions that they _trust_)

**Comment by philipmulcahy** [comment]
v1.92.20 is out -> closing this issue.
