### ISSUE TITLE
Have the order of orders in the csv be newest on top and oldest on bottom (same as Amazon)

### ISSUE THREAD

**Issue by danniboy** [philipmulcahy/azad#156]
Would it be possible to have a setting where one can choose the ordering in the csv?

**Comment by ScottMcNay** [comment]
If you're opening in a spreadsheet application, you can enable filtering,
then sort by column.

Are you using an app which doesn't offer this capability?

**Comment by danniboy** [comment]
I am using an app that offers sorting. My question/suggestion was for the reports to maintain the order of Amazon. Is there some reason it changes the ordering?

**Comment by philipmulcahy** [comment]
I am not strongly motivated to fix this for a couple of reasons:
1) The fetch doesn't know some of the fields (like date) at the time it first lays out the table on screen. It's a trade off between seeing progress and getting things in the order you choose. Some people want it in order id order. You can sort by date in the default view once its rendered.
2) You can (as Scott points out) sort in whatever tool you consume the csv with.

**Comment by ScottMcNay** [comment]
I just tested this. If I'm in Data Table view (which provides sort
features) and sort by date, it then appears to download by date -- albeit
grouped by physical/digital.

--Scott.

**Comment by ScottMcNay** [comment]
Ok, ignore my previous reply; I tried sorting by amount, then downloading,
and it was still in order by date, grouped by physical/digital.
