### ISSUE TITLE
Incorrect total (Amazon UK 2008)

### ISSUE THREAD

**Issue by danniboy** [philipmulcahy/azad#157]
The report displays an incorrect total compared to the csv and the actual data. The shipping total is correct though.

The total should be 5760,58

![incorrect total](https://user-images.githubusercontent.com/201021/112832062-5325c880-9084-11eb-9295-f9cbda2d33a1.png)

[incorrect total.xlsx](https://github.com/philipmulcahy/azad/files/6221450/incorrect.total.xlsx)

**Comment by philipmulcahy** [comment]
1) was the sum correct for the visible orders?
2) is it still misbehaving in 1.9.21?

**Comment by danniboy** [comment]
Same issue. There were 20 orders that year so the report splits to two pages.

Page 1 gives these values
page=2191.22; all=4636.45
Page 2 gives these values
page=2445.23; all=4636.45

Page 1 is £1124.13 too low and I can't figure out that number. It is not the shipping and there were no refunds for any order that year.
Page 2 is correct

Page 1

`£148.31
£292.84
£45.97
£45.98
£698.93
£25.62
£117.97
£373.28
£441.20
£1,125.25`

Page 2

`£93.95
£15.83
£540.31
£61.75
£743.21
£34.03
£652.67
£91.46
£163.13
£48.89`

**Comment by philipmulcahy** [comment]
Does the console log reveal any failed order scrapes?

**Comment by danniboy** [comment]
Apologies for the late reply

[www.amazon_2008_1.log](https://github.com/philipmulcahy/azad/files/6387913/www.amazon_2008_1.log)

**Comment by philipmulcahy** [comment]
This has fallen into one of the capacious cracks in my mind - sorry for ignoring it in the current batch of fixes - I'll get on it next

**Comment by philipmulcahy** [comment]
omg! sorry this got dropped again. When 1.10.0 drops this week, would you be interested in having another shot at this together?

**Comment by philipmulcahy** [comment]
assuming this isn't a thing any more -> close
