### ISSUE TITLE
Scrape years earlier than 2004

### ISSUE THREAD

**Issue by glenviewjeff** [philipmulcahy/azad#160]
Could you please add buttons for years prior to 2004, going back to at least 2001? I have purchases dating back that far, and Amazon will show them correctly in my order history.

**Comment by philipmulcahy** [comment]
Hi Jeff,

It used to offer all the years that Amazon would admit to knowing about, but then I got drowned in angry complaints about older years not working. It appeared as if Amazon started to thin out or lose the older years’ data, and the extension was getting blamed for Amazon’s amnesia.

I “fixed” the problem by truncating the the list: https://github.com/philipmulcahy/azad/blob/8323e00e47e16c22c3e7a38c27ba7bbecab0bcd5/src/js/inject.ts#L86 <https://github.com/philipmulcahy/azad/blob/8323e00e47e16c22c3e7a38c27ba7bbecab0bcd5/src/js/inject.ts#L86>

It worked in that the frequency of complaints is lower and they tend to be more reasonable in tone, but I totally agree it’s not ideal.

If you’re really keen, you could build your own private version - you can just delete that line - no other change needed.

Yours,

Philip

**Comment by glenviewjeff** [comment]
That's pretty funny.. I can give it a shot; do I just package up the files into a zip?

**Comment by glenviewjeff** [comment]
It's not a huge deal; would be nice to have the data, but it would probably be easier just to copy/paste into a spreadsheet or something for the older data, given that I'd run it exactly once.
