### ISSUE TITLE
Scrape specific month/quarter

### ISSUE THREAD

**Issue by ADS1134** [philipmulcahy/azad#161]
Greetings,

It would be really appreciated, if we could only choose a specific month or quarter rather than the whole year; e.g. March 2021.

For people with high amount of orders it tooked time, because allready exported orders wil scraping again, sometimes it'll crash or Amazon block you for an hour, because of all the requests. I tried to export 40k oders, it wasn't an easy thing at all. :)

Thank you very much!

King regards.

**Comment by philipmulcahy** [comment]
Per https://github.com/philipmulcahy/azad/blob/master/README.md#commercial-features-20212022,
vote for this feature here: https://forms.gle/LNjkzMoQERSoz1wA9

**Comment by philipmulcahy** [comment]
I've got this working: see https://github.com/philipmulcahy/azad/blob/master/doc/commercial_features.md for how to get it!

**Comment by philipmulcahy** [comment]
Released in May (1.9.26) behind preview subscription paywall - will become free when lifetime donations to https://www.justgiving.com/fundraising/azad-pah reach GBP 5000 (slightly more than  USD 5000). Currently just below GBP 3600
