### ISSUE TITLE
Plugin freezes before displaying totals or csv files.

### ISSUE THREAD

**Issue by hawkingswheelchair** [philipmulcahy/azad#165]
Blank window with no information after scraping is finished.

**Comment by philipmulcahy** [comment]
Closing on assumption that 116 days without a response is most likely indicative of a solved problem - feel free to re-open if I am wrong.
p.s.
My right toes were run over by the real wheel chair in 1993 or 1994 - three times actually - forwards, backwards and then forwards again - I managed not to shout, and I suspect he had no idea the obstacle that was slowing him down belonged to anyone.
