### ISSUE TITLE
Have 103 orders in 2021 but only 93 are being exported

### ISSUE THREAD

**Issue by fusionenergy27** [philipmulcahy/azad#166]
I have followed the advice to logout, clear cookies and cache. I have reinstalled the extension. I have downloaded a log file as instructed. How do I send it to you. Hope you can help. Thanks

**Comment by philipmulcahy** [comment]
Send to ***@***.*** (I think).
Work is super busy at the moment: it might take me a while to get to it. Thanks for reporting!

Yours,

Philip

**Comment by fusionenergy27** [comment]
Hi Philip,

Thank you for your email. Unfortunately it appears that all the email
addresses have been redacted from your email. I will try and send the log
file to the email address in your help file.

Thanks again for your help.

Kind regards,

Ian
Kind regards,

Ian

**Comment by philipmulcahy** [comment]
I just expended as many as five whole minutes crafting this:
```
perl -ne  "m/([D0-9]\d\d-\d{7}-\d{7})/ and print qq/\$1\n/;" www.amazon.co.uk-1633438570863.log \
  | sort | uniq -c | wc -l
```
which returns 96 - e.g. there are 96 distinct orders in the log you provided (thanks), which is somewhere between 93 and 103.
This suggests that there may be two separate problems going on here...
1) Orders that are making into the log are not making it into the output view.
2) Some orders aren't even being picked up in the initial "index" scrape.

Let's work on (1) first:
I'd like you to share with me (by email - not this ticket) the order id from an order or two that IS in the log (I'll send you a sorted list by email), but not in the output view.

Yours,

Philip

**Comment by fusionenergy27** [comment]
Hi Philip. I was wondering if you have been able to make any progress on this problem? No problem if not as I understand how busy you are. I have tried to send you the missing order numbers via email but am unsure if they reached you as your email address was redacted in your original response. Yours, Ian

**Comment by philipmulcahy** [comment]
Hi @fusionenergy27,
I am back in the saddle and looking at back email this evening.

**Comment by philipmulcahy** [comment]
I've asked you to fetch a link and share the html with me (as an attachment over email).
Thanks,
Philip

**Comment by fusionenergy27** [comment]
Hi Philip. Thanks for your email. I have replied with the information you requested. Thanks Ian

**Comment by philipmulcahy** [comment]
Hi @fusionenergy27 I am back on the case, and I think I'm going to need another html file. I'll send the url to you over email.

**Comment by philipmulcahy** [comment]
... actually, I may have another way in - I will chew on it for a bit.
In the meantime, if you have 5 minutes, I'd like you to get me the url **and** html for the page of 10 order summaries that includes the order you've sent me the detail html for (id ends in 1160320). It'll mean some paging through by date, it could end up being very useful.

**Comment by philipmulcahy** [comment]
Yeah - I've faked a test that gets the code as far as trying to parse your order detail html, and it gets through it, so I think we're getting stuck in the order list html. I await your email (no hurry: it's not as if I've been super responsive!).

**Comment by fusionenergy27** [comment]
Hi Philip. I hope you are well. I was wondering if you received my files or should I send them again. Thanks

**Comment by philipmulcahy** [comment]
It’s not you, it’s me (!)
I’ve been saturated at work for the last few months, and azad has had to take a back seat. A couple of weeks ago I took a shot at working on the “give me a month’s worth of orders, a year takes too long” and realised I just didn’t have enough time to focus. There is a light at the end of the tunnel: I have managed to give back two of my four teams in the last week, and another one gets handed over next month - at that point I have only one team to manage (the right number) and intend to resume progress.
Thank you for being so patient!

Philip

**Comment by fusionenergy27** [comment]
Thanks Philip that's much appreciated. Please let me know if you need any more information. I look forward to hearing from you.

**Comment by philipmulcahy** [comment]
I am putting this in a group of issues that I think can be at least ameliorated by using timeouts and promise races. The challenge is how to report the failures in a way that allows further debugging.

**Comment by fusionenergy27** [comment]
Philip,

Thank you for all the work you have done.

I have run several extracts and unfortunately I am still missing 2 items. I
have attached the downloaded .csv file, a pdf screenshot the missing
orders, and the .html file of the same screen. The missing orders are
203-2142193-9808347 & 203-2687912-1043530.

Hope this helps.

Kind regards,

Ian

**Comment by philipmulcahy** [comment]
Hello @fusionenergy27  - would you mind testing out https://www.mulcahyfamily.org/azad/azad_fe509815.zip per https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version ?

If it _doesn't_ work, before capturing the log you'll need to turn on verbose logging. I've made a big change to how the requests to amazon are processed, which may improve results, but if it doesn't it should make it easier to work out what's happening.
Sorry it's taken so long - it's been a bit of an octopus of a change.

Yours,

Philip

**Comment by philipmulcahy** [comment]
v1.10.0 (in review with google) is about to roll out. It has significant changes in how requests to Amazon and the processing of the responses are managed.
If anyone sees stuck or missing orders from this (or subsequent) versions, it's going to be a lot easier to analyse the console log to figure out what orders have caused the problem. That will then enable us to choose which orders to look at more closely (by capturing a debug json file).
I'm going to close this ticket now because no-one's posted on it for a while. That's not to say that no order will ever confuse Azad ever again (get real - it's going to happen!), but I'd like to deal with those examples in new tickets from 1.10.0 onwards.

Yours,

Philip
