### ISSUE TITLE
Show order date in the items list view

### ISSUE THREAD

**Issue by evonder68** [philipmulcahy/azad#167]
I can't seem to get the items to show. This has worked in the past. The three check boxes do not seem to respond even after clearing the cache. The results always show the invoice link even when this isn't selected but never the "items not orders".

**Comment by philipmulcahy** [comment]
Hi evonder68
I just realised that orderdate was never in the item-only view code: this is an enhancement request (I suspect a pretty easy one).
I'll mark it as such and get to it when I've finished triaging the backlog of tickets that have built up while I've been ignoring Azad.
Thanks for reporting!
Philip
