### ISSUE TITLE
Single year button doesn't display a table

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#17]
Reported by Rebecca Simpson

**Comment by philipmulcahy** [comment]
Reported by Rebecca Simpson

**Comment by RebeccaSimpson18** [comment]
[www.amazon.com-1518990804958.log](https://github.com/philipmulcahy/azad/files/1735155/www.amazon.com-1518990804958.log)

Hello!  Attached is the log you requested. Thank you!

**Comment by philipmulcahy** [comment]
Thank you!
Welcome to github - I'm not exactly a native here myself.
I've added some log lines to the code so we can narrow down where it's getting stuck. It should finish publishing within 60 minutes - v1.7.13.
1) Would you mind re-trying 2017 and sending me the log again (please)?
2) Do all your years behave the same - e.g. nothing visible even after all the logging stops?
Philip

**Comment by RebeccaSimpson18** [comment]
Hello!  So sorry, this was intercepted by my spam filter. I will try again and report results. Thank you so much!

Get organized with Yahoo Mail 
 
  On Mon, Feb 19, 2018 at 1:57 PM, Philip Mulcahy<notifications@github.com> wrote:   
Thank you!
Welcome to github - I'm not exactly a native here myself.
I've added some log lines to the code so we can narrow down where it's getting stuck. It should finish publishing within 60 minutes - v1.7.13.
   
   - Would you mind re-trying 2017 and sending me the log again (please)?
   - Do all your years behave the same - e.g. nothing visible even after all the logging stops?   
Philip

**Comment by RebeccaSimpson18** [comment]
Here is the new log! Thanks!
[www.amazon.com-1519620080188.log](https://github.com/philipmulcahy/azad/files/1757253/www.amazon.com-1519620080188.log)

**Comment by philipmulcahy** [comment]
@RebeccaSimpson18 Thank you again!
I've just published 1.7.14, which logs every order line as it is written to the table, like this:
![image](https://user-images.githubusercontent.com/1668892/36690112-3f4cf00a-1b29-11e8-9373-d9b0f2a91458.png)

If we see such log lines, then I'm wondering if the next thing to look at is what the table element looks like:

![image](https://user-images.githubusercontent.com/1668892/36690512-72bccb76-1b2a-11e8-8416-84b30e959828.png)

If you click on the elements tab instead of the console tab, you can either scroll through hunting for the table element with id=order_table (laborious), or you can search (ctrl-F/cmd-F for windows/mac) for this pattern: //table[contains(@id,"order_table")]

I've clicked the little triangles on the left to show the \<tr\> elements - one per order.
Maybe you can't see the table because it's just not present, or maybe it's invisible for some reason...

**Comment by RebeccaSimpson18** [comment]
Hello!

Attached are images of the elemwnts tab.  The first, titled "elements" shows what I think you are looking for. 

The second, titled "display block" show a warning I noticed that is blocking a style sheet. I don't know what it means, or if it matters, but since something was blocking something I thought I'd mention it.
Finally, to confirm your earlier question, yes - all years appear to behave the same.  That is to say they only display digital orders and nothing from regular Amazon.  

Let me know if there is more I can help with. 
![display block](https://user-images.githubusercontent.com/36609280/36799432-08d68cea-1c62-11e8-9c39-08802e6f564f.JPG)
Thank you!

**Comment by philipmulcahy** [comment]
Hi @RebeccaSimpson18  and thank you once again!

This is so strange...

There appear to be two issues (let me know if I've misunderstood):
1) You're not seeing any orders displayed in a table, even after the orange progress counter thing in the top right corner has stopped doing stuff.
2) The log only shows digital orders (some ~45 of them), but you also have non digital orders.

Your lower screenshot shows the first 10 order rows (the DataTable library hides all but the first 10 by default), which is consistent with the logs (45 is greater or equal to 10).

What I see in my account (logs and html) looks basically identical except my table shows this:
![image](https://user-images.githubusercontent.com/1668892/36816845-0b85c472-1cd7-11e8-8b7c-de2ef5c841f9.png)

I'm wondering if you're able to share a screenshot of your equivalent display?

Sorry this is turning out to be such a pain!

Philip

**Comment by RebeccaSimpson18** [comment]
Hello!
In response:

1) I do see orders displayed in a table. 

2)But it will only pull the digital orders.  I really need to see the orders for regular products (need it for my taxes!).  It does not seem to be able to fetch these.

Below is a screenshot if the table that is displayed. 

Thanks!

![table](https://user-images.githubusercontent.com/36609280/36820162-62c0a9a4-1ca1-11e8-8276-8743a1d68cc4.JPG)

**Comment by philipmulcahy** [comment]
Hi Rebecca,

Thank you!

I think I'm able to reproduce your issue - it seems to be different behaviour on .com from the .co.uk and other non-US sites. I will work on a fix this weekend (as I have a couple of .com orders to play with).

If your tax return is urgent you _might_ want to look at the csv download feature Amazon offers on the .com site (but nowhere else) in case I don't come through fast enough.

Philip

**Comment by philipmulcahy** [comment]
Hi Rebecca,

1.7.15 being published now (might take an hour for it to propagate globally).
I'm feeling quite positive this'll nail the bug (famous last words!)
If it doesn't, the log would be really helpful!

Thank you so much again for being patient and helpful.

Philip

**Comment by RebeccaSimpson18** [comment]
Hooray!  It works!  Thank you so much, this will be extremely helpful.  

I appreciate you working on me with this, I've never done a project like this before and it was fun to learn and watch.  I hope your app continues to be super successful, you deserved it! :)

All the best,

Rebecca
