### ISSUE TITLE
Invoice URLs

### ISSUE THREAD

**Issue by chm3gt** [philipmulcahy/azad#171]
Firstly, cheers for making this extension, it's very useful.

Though I'm currently encountering problems with invoice URLs where they just go to a https://www.amazon.co.uk/errors/400.html page

I've tried clearing the cache.

How temporary are these links? It seems like they don't work within a matter of minutes. I ideally want the links in the csv file to be working, though I'm not sure if this is an issue with the app or just the way Amazon works.

**Comment by philipmulcahy** [comment]
Are you saying that they work for a few minutes and then stop working or that you're pretty sure that some of them never worked, but that you might have taken a few minutes to get to them?
Either way I can see this is undesirable, but it might be possible to investigate and fix the scenario where the urls scraped were immediately bogus - at least by not even showing those bad URLs.

**Comment by philipmulcahy** [comment]
I think that Amazon are doing it deliberately - gonna close this one unless anyone's got a viable idea for how to make it work.
