### ISSUE TITLE
Toolbar button doesn't appear on Amazon.ca with v 1.9.22

### ISSUE THREAD

**Issue by johnefrancis** [philipmulcahy/azad#172]
The toolbar button does not appear while accessing 

https://www.amazon.ca/gp/your-account/order-history

Chrome version 

Version 96.0.4664.45 (Official Build) (64-bit) 

Running on Ubuntu

I don't use the extension regularly, but I used it about 1 year ago and it worked great.

**Comment by philipmulcahy** [comment]
Hi @johnefrancis,
The extension is now controlled by a popup that you command to appear. To get it to display, you click on the extension's icon on the right hand side of the address bar. If it's not pinned, you click on the jigsaw piece icon and it shows all of the installed extensions, and then you click on the azad icon.

![image](https://user-images.githubusercontent.com/1668892/147834932-d530e6bd-7a1b-4fae-a83d-c94f0650e494.png)

I can't remember exactly when I changed it, but it was probably more than a year ago.

Yours,

Philip
