### ISSUE TITLE
Gift card order shows "Grand total:" in amount column

### ISSUE THREAD

**Issue by jaraco** [philipmulcahy/azad#174]
After running the plugin, I see the following in the output:

![image](https://user-images.githubusercontent.com/308610/146963148-a97d5571-ca32-4908-b914-1e0f513d4d96.png)

The "Grand Total:" in the amount column subsequently breaks the data import.

Here's what that order looks like:

![image](https://user-images.githubusercontent.com/308610/146963444-0a258d0c-83d8-488d-9261-54ca78abd865.png)

Here's a snippet of the HTML (sadly, Github is injecting garbage characters):

```
--
<h5 class="a-spacing-micro a-text-left">
  | Order Summary
  | </h5>
  |  
  | <div class="a-row">
  | <div class="a-column a-span7 a-text-left">
  | <span class="a-color-base">
  | Item(s) Subtotal:
  | </span>
  | </div>
  | <div class="a-column a-span5 a-text-right a-span-last">
  | <span class="a-color-base">
  | $100.00
  | </span>
  | </div>
  | </div>
  |  
  |  
  | <div class="a-row a-spacing-mini">
  | </div>
  |  
  |  
  | <div class="a-row">
  | <div class="a-column a-span7 a-text-left">
  | <span class="a-color-base">
  | Total before tax:
  | </span>
  | </div>
  | <div class="a-column a-span5 a-text-right a-span-last">
  | <span class="a-color-base">
  | $100.00
  | </span>
  | </div>
  | </div>
  |  
  |  
  | <div class="a-row">
  | <div class="a-column a-span7 a-text-left">
  | <span class="a-color-base">
  | Estimated tax to be collected:
  | </span>
  | </div>
  | <div class="a-column a-span5 a-text-right a-span-last">
  | <span class="a-color-base">
  | $0.00
  | </span>
  | </div>
  | </div>
  |  
  |  
  | <div class="a-row a-spacing-mini">
  | </div>
  |  
  |  
  | <div class="a-row">
  | <div class="a-column a-span7 a-text-left">
  | <span class="a-color-base a-text-bold">
  | Grand Total:
  | </span>
  | </div>
  | <div class="a-column a-span5 a-text-right a-span-last">
  | <span class="a-color-base a-text-bold">
  | $100.00
  | </span>
  | </div>
  | </div>
  |  
  |  
  |  
  |  
  |  
  |  
  | </div>
  | </div></div>
  | </div></div>
  |  
  |  
  |  

```

**Comment by philipmulcahy** [comment]
Would you be willing to send me the order dump json file for an example order, such as the one above? Instructions on how to do that are here: https://github.com/philipmulcahy/azad#how-to-save-and-send-an-order-debug-json-file
I cannot guarantee to be able to work on this immediately, but it seems very soluble.

Yours,
Philip

**Comment by jaraco** [comment]
Sent to the address as requested. Thanks for your help! Let me know if there's more I can do.

And Merry Christmas.

**Comment by philipmulcahy** [comment]
Hi @jaraco,
https://www.mulcahyfamily.org/azad/azad_3d527d96.zip is a fix candidate - would you mind taking it for a spin and reporting back here?. Instructions on how to use a private version are [here](https://github.com/philipmulcahy/azad#how-to-try-out-an-experimental-version).
Yours,
Philip

**Comment by jaraco** [comment]
Nice! It's looking good.

![image](https://user-images.githubusercontent.com/308610/147623362-b1267660-d4f4-4b7b-8d6a-4a1865a20f8c.png)

Now the amount is showing up correctly. The payments still shows up as UNKNOWN, but that may be intentional and isn't nearly as important as the amount column.

Declaring success. Thanks Philip!
