### ISSUE TITLE
Promotions are not tracked

### ISSUE THREAD

**Issue by daniloascione** [philipmulcahy/azad#176]
Only the full price of the article is reported: in case of promotions (eg. lightning deals) the actual price is not displayed.
Not sure if this is possible to track at article level, since the promotions are applied to the order total.

Thanks for your effort!

**Comment by fbietlot** [comment]
FYI I have apply a small enhancement **(for amazon.fr) ** on my forked version https://github.com/fbietlot/azad/issues/8

**Comment by philipmulcahy** [comment]
I am going to close this as likely not to be addressed in the near future (not saying it's a bad idea though).
