### ISSUE TITLE
json debug right click action doesn't work from items list view

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#179]
During investigation of #162, we've discovered that the order json dump tool doesn't work from the items list page.
If the problem is wider than this, please help characterise it here - we can always retitle.

**Comment by EricM81** [comment]
Also for the orders list page under two scenarios:
* when the payment method is reported as `UNKNOWN;` 
* for digital orders

**Comment by philipmulcahy** [comment]
Dunno about digital orders, but I've got it working on the items page - the cause was really, really embarrassing.

**Comment by philipmulcahy** [comment]
(I think debug dumps not working on the orders page should be another bug ticket)

**Comment by philipmulcahy** [comment]
fixed in 1.9.23
