### ISSUE TITLE
scrape shipping date

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#180]
Shipping date has been requested at least twice on the chrome web store support page.

**Comment by Wroooom** [comment]
Make it three! I came from the web store looking for this feature and this would make it perfect:
Shipping Date / Delivered / and perhaps delivered too also!

**Comment by polychromeuganda** [comment]
The requested feature is probably unitary, in that scraping both dates is as easy as scraping one BUT requested feature will run into a problem when implemented that may limit its utility in some instances.

The explanation can be simplified to this: when there are different prices for an item using a single ASIN and the total of promotional credits is >= the smallest increment between two prices it isn't always possible to know if a shipment used the promotional credits or the discounted item or both. The previously available CSV data had a different but similar ambiguity when a credit from a gift card was applied to an order.

Tracking information isn't available on the web site for an order after the return-before date has passed. A pseudo tracking ID concatenating a Un-Carrier the delivery date and group on the order page could be used to replace it e.g. NONAME2023033100.1The transactions on the order detail are paired with a shipment date, but items are reported by date delivered. Multiple shipments may be associated with either or both dates. The transaction detail reports the amount charged for a shipment date, but the assignment of credit from promotions in an order to transactions often doesn't match the promotions applied to the items shipped that day.

It will not be possible to unambiguously assign ASINs purchased in a quantity > 1 at different prices to a particular shipment using only the information available on the user's web pages for the order history.  (e.g. by purchasing 1 new and 1 amazon warehouse deal of the same ASIN). Attempting to disambiguate the assignment of items to shipments using the payment transactions is not always possible. For example if the is a $5 promotional credit for some item in the order and an Amazon warehouse item discounted by $5. If the vendor is also scraped for each delivered item, the ambiguity is less common but still occurs when multiple items at varying discounts and multiple promotions also exist. 

There can be multiple ship dates for an order and multiple shipping dates for items that were ordered in quantity > 1.  An order containing an item quantity >1 (with same ASIN) ordered from multiple vendors may be at different prices. There was an unambiguous breakdown of an order with OrderID  with N shipments identified by a ShipmentID that is the concatenated carrier and tracking number. Treating each OrderID and Shipment ID pair as if it was an order does succeed for the purpose of building up an order as a set of bills of lading containing items matching the order in the aggregate by using the ASIN and price as a concatenated pair. This requires having an unambiguous shipment ID for each item and then assigning promotional credits to a shipment date to reach the transaction amount. This method has failed twice in 3,700 orders. Sometimes the internal procedure Amazon uses to assign value from an order to a shipping date can't be attributed to a rational process. A best-fit process would have to be used to ignore the unattainable goal.

[The formerly available csv data didn't report payment transactions and was ambiguous in the assignment of gift card credit creating an ambiguity in the merchandise total for transactions on a shipment date leading to the same ambiguity as above.] 

If you can't quite figure out why there would ever be a problem, the explanation can be simplified to this when there are multiple prices for an item using a single ASIN and the total of promotional credits is >= the smallest increment between two prices it isn't always possible to know if a shipment used the promotional credits.

**Comment by philipmulcahy** [comment]
@polychromeuganda did you mean to post that on this particular ticket? It's very interesting, but seems to address a bigger space than "we want shipping dates". For the avoidance of doubt, azad's mission has deviated very, very far from rigorous correctness. We can console ourselves with the fact that it's a scraper - rigour is in short supply in our source material. 

When filing this particular ticket, I was aware that the relationship of orders and shipping events isn't necessarily a zero or one type of thing - I intended to do something flaky like look at a few vanilla orders and see what fields might be easily scraped.

**Comment by philipmulcahy** [comment]
merged to #221
