### ISSUE TITLE
Any chance of adding amazon.co.jp?

### ISSUE THREAD

**Issue by discoltk** [philipmulcahy/azad#182]
I'm happy to provide debugging if you can add the JP site. The order history page looks the same superficially, not sure what the hurdles might be.

Thanks!

**Comment by philipmulcahy** [comment]
You could (temporarily) share your account details with me, which would be easiest, but if it were me, I wouldn't want to do so - you've got no idea what I'd do!
The next best thing is to start sharing URLs.
Off the top of my head, I'd need example URLs for
1) the first 10 orders in 2022, like https://www.amazon.co.uk/gp/your-account/order-history?orderFilter=year-2022&ref_=ppx_yo2_dt_b_filter_all_y2022
2) a link direct to one of those orders: https://www.amazon.co.uk/gp/your-account/order-details/ref=ppx_yo_dt_b_order_details_o06?ie=UTF8&orderID=206-0579925-2601789
3) a similar one, but for a digital item

Then I could send you a test build and we could go from there...
Be aware, I've not got a huge amount of spare time at the moment, so you're going to need to be patient!

Philip

**Comment by ScottMcNay** [comment]
Does .co.jp support an English version?

--Scott.

**Comment by philipmulcahy** [comment]
commit 6e62ecc8e1fedd6e8557c07ccf41f0bf0b06fecf has .co.jp added in the right places. I think it's gonna need the english version of the site (which is what shows when I, an english speaker visit amazon.co.jp) to work properly.

1.9.25 is going to be the next version - think weeks not months.
Please let me know if it doesn't work.
I'll close this issue after that release - feel free to re-open it and post problems after that version is released.

**Comment by philipmulcahy** [comment]
I messed up 1.9.25 and never released it - never fear: 1.9.26 went live a few days ago.
