### ISSUE TITLE
Add support for payment method Direct Debit without payments

### ISSUE THREAD

**Issue by jjeising** [philipmulcahy/azad#185]
amazon.de (and maybe others) support [direct debit](https://www.amazon.de/-/en/gp/help/customer/display.html?nodeId=GZQJ5W5UN32NC9QH) as a payment method. In this case the payment method is listed as
```
Direct Debit | Last digits: XX
```
but no transactions are listed:
![payment](https://user-images.githubusercontent.com/40333/156895806-877257e8-1744-4f05-8ba3-e38daf2b6cb2.png)
`strategy_1` fails, as there are no transactions, `strategy_2` fails, as the payment amounts are missing:
https://github.com/philipmulcahy/azad/blob/45bcf99d06d26cfe54b069e1081aef9098ab3493/src/js/extraction.ts#L103-L106

**Comment by philipmulcahy** [comment]
Might you be willing to send me (azadextension.gmail.com, not here, so no-one else gets to see the html) the html from the payment information page you show above? If so, please put #185 in the subject line.
Then, post here to say you've done it - I don't look at that email box unless I know there's something good there.

**Comment by philipmulcahy** [comment]
no response from requestor -> closing
