### ISSUE TITLE
Some US digital titles are blank

### ISSUE THREAD

**Issue by ScottMcNay** [philipmulcahy/azad#187]
Some US digital titles are blank; they turn out to be the monthly Comixology Unlimited, Kindle Unlimited, and Amazon Music Unlimited memberships (I need to turn off two of those).

**Comment by philipmulcahy** [comment]
Hey Scott - might you be able to get an order debug json file for one or two of those orders?

**Comment by philipmulcahy** [comment]
Is this still a thing @ScottMcNay?
I've been working really hard on bugs for the last few weeks (as opposed to feature requests), and this just reappeared on my radar. An order debug json file is definitely the way to go if it is still happening.

**Comment by philipmulcahy** [comment]
I'm going to assume this is not a thing any more - if it is, then please feel free to re-open and surrender a json file :)
