### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by iphark** [philipmulcahy/azad#188]
Hi! 

AZAD unfortunately does not work. Before I get into a long description, here is a picture showing my issue:

![image](https://user-images.githubusercontent.com/33488377/158367189-03b9ed98-13f3-4b8a-a96d-656774f45252.png)

It never shows me the years or anything. I tried reinstalling, logging out and into amazon, refreshing, closing and opening chrome, different order pages, updated chrome.... but it did not help.

I read the README and looked through the issues, but it seems I'm the only one...

sites I tried:
https://smile.amazon.de/gp/css/order-history?ie=UTF8&language=en&ref_=nav_AccountFlyout_orders&
https://smile.amazon.de/gp/css/order-history
https://smile.amazon.de/gp/your-account/order-history?opt=ab&digitalOrders=1&unifiedOrders=1&returnTo=&__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&orderFilter=year-2022
and others

**Comment by iphark** [comment]
I had the genius idea of not using smile.amazon, instead just amazon.

Now it works.

**Comment by ScottMcNay** [comment]
It's supposed to work for Smile.

--Scott.

**Comment by philipmulcahy** [comment]
Hi Benjamin and Scott,
1) sorry for being so unresponsive - I’ve been doing double duty at work for the last few months, and there’s a shortage of time (and energy) left for azad, but there is a dim light at the end of the tunnel.
2) Smile works (or worked) for some regional sites, but I don’t know if that includes .de from memory. If it’s just that we’ve not added the relevant template strings, that would be an easy fix. I would happily merge a (tidy) pull request if the author shows a screenshot of it working…

Yours,

Philip
