### ISSUE TITLE
Incorrect CSV parsing issue

### ISSUE THREAD

**Issue by BrunoRomes** [philipmulcahy/azad#189]
Hi,

I've been seeing some incorrect CSV parsing issue. For some rows the `to` column becomes ` ` and all the remaining of the data in the row gets an offset of 1 (so `date` contains the data from `to`, `total` is the date and so on).

This leads to inconsistent number of columns.

This did not happen in February as far as I can tell, starting at some point in March.

**Comment by philipmulcahy** [comment]
No code has changed in the extension, so I wonder if it is being triggered by your Amazon data.
When you say “parse”, I assume you actually mean “generate”?
Have you figured out what is wrong with the csv? What tool are you using to look at it with? Excel or something else?
I cannot remember if I hand coded the generation or if it is a library, but csv problems tend to come in two common categories:
1) poor encoding: omitting to escape/quote/strip special chars like commas and quotes and similar… my kind of bug!
2) standards mismatch: your parser thinks csv works differently to my encoder. There isn’t one standard definition of csv, so this situation can lead to name calling. Excel used to blow up if the first cell of a csv was ID (for example).

Yours,

Philip

**Comment by BrunoRomes** [comment]
Yes, in this case by `parse` I mean `export` the CSV file.

And indeed I think the issue was with the tool I was using (LibreOffice Calc) to inspect the csv file. By default, it breaks the cells by `,` and `;`. Upon further csv inspection (in a text editor), the description of the order is not wrapped in `"` for some rows, and all orders end in `; `, so the tool was actually splitting the columns there.

Thanks for your promptly response.

**Comment by ScottMcNay** [comment]
See this page:
https://help.libreoffice.org/6.3/en-US/text/scalc/guide/csv_files.html

This is for importing, not for directly opening, which is what you probably
good. If LibreOffice automatically accepts semicolons, maybe a change/bug
request should be submitted.

I found this:
https://www.ietf.org/rfc/rfc4180.txt

--Scott.
