### ISSUE TITLE
amazon.com report doesn't include digital orders

### ISSUE THREAD

**Issue by benjaminjkraft** [philipmulcahy/azad#19]
I don't think I did anything unusual but let me know if there's any more detail to include.  Chrome 65.0.3325.146 64-bit on Ubuntu, extension v1.7.16.

**Comment by philipmulcahy** [comment]
Ah - interesting - I fixed a digital-only issue the other day - maybe we've swung too far the "other way"?

What would be very, very useful is an example URL from you similar to this one that returns both digital and non-digital orders...

https://www.amazon.co.uk/gp/your-account/order-history?opt=ab&digitalOrders=1&unifiedOrders=1&returnTo=&orderFilter=year-2018

Also, would you mind grabbing the log after running the extension again?
# Chrome developer console (three dot icon/button on right hand side|More tools|Developer Tools)
# Click on Console (in a bar near the bottom normally)
# Press the orange year button you want to fetch
# Watch the console fill up with logs, and wait for stuff to stop happening in the counters on the top right hand side.
# Right click somewhere in the console logs | Save as... (choose a file name)
# Drag the file to a comment box in this ticket.
[although order ids end up in the log (and offer useful clues about digital/non-digital), I and others cannot use them to look at your orders or other account info.]

This might enable us to figure out what's going wrong without troubling you further.

Thank you very much for providing feedback!

Philip

**Comment by philipmulcahy** [comment]
@benjaminjkraft is this still a problem?

**Comment by benjaminjkraft** [comment]
Thanks for the response, and sorry for the delay!  I didn't figure out a similar URL that got both -- the UI doesn't seem to have a view that shows both and no obvious twiddling of the URL parameters got it to work.  https://www.amazon.com/gp/your-account/order-history/?digitalOrders=1&orderFilter=months-6&unifiedOrders=0 loads digital orders, but if I set digitalorders=1&unifiedOrders=1, it goes back to just non-digital.

Here's my log: [www.amazon.com-1525563429107.log](https://github.com/philipmulcahy/azad/files/1977185/www.amazon.com-1525563429107.log).

**Comment by philipmulcahy** [comment]
1.8.1 (propagating now - give it 60 minutes from when I post this) might fix the issue. I was using a different URL template for www.amazon.com than for any of the other configured sites - not any more.
Let me know...
Philip

**Comment by benjaminjkraft** [comment]
Sadly, still no dice.  Here's the new log, from 1.8.1: [www.amazon.com-1525671895891.log](https://github.com/philipmulcahy/azad/files/1978592/www.amazon.com-1525671895891.log)

**Comment by philipmulcahy** [comment]
Thanks!
I'm going to petition a US colleague to play with URLs this week.

**Comment by philipmulcahy** [comment]
OK - we managed to reproduce on my colleagues acct.
The .com urls definitely behave differently:

Non-digital Orders: https://www.amazon.com/gp/your-account/order-history/ref=oh_aui_menu_date?ie=UTF8&orderFilter=months-6

Digital Orders: https://www.amazon.com/gp/your-account/order-history/ref=oh_aui_menu_yo_new_digital?ie=UTF8&digitalOrders=1&orderFilter=months-6&unifiedOrders=0

There's no technical barrier to calling both URLS (and paging through them) - I just need to add the logic to make the US behaviour special. I'll work on it in the next couple of weeks if I can find some spare time.

**Comment by philipmulcahy** [comment]
1.8.3 (pushing out right now) has an experimental fix: it uses both of the URL patterns ^.
If it doesn't work, another log would be very useful. If it does work, please close this ticket.
Thank you Benjamin!

**Comment by philipmulcahy** [comment]
@benjaminjkraft just in case you didn't get notified of the post above

**Comment by benjaminjkraft** [comment]
Sorry, was just away for the weekend :-) .  It works great -- thanks so much!
