### ISSUE TITLE
Scrap from mobile app

### ISSUE THREAD

**Issue by tonyxiao** [philipmulcahy/azad#193]
I wonder if amazon's mobile app has a private API that we could use instead of scraping the HTML on the website. Have you investigated it?

**Comment by philipmulcahy** [comment]
Wouldn’t that be nice? I foresee some problems though...
1) they could change it very quickly
2) it might already be encrypted/authorised
3) it’d mean us crossing a line - in the UK (where I live) that line is called the computer misuse act 1990. The US version is more exciting.

Thanks for the suggestion!
