### ISSUE TITLE
smile.amazon.de seems broken

### ISSUE THREAD

**Issue by rohabu** [philipmulcahy/azad#198]
Hi!

i've installed the extension and navigated to my order history:

https://smile.amazon.de/gp/css/order-history?ref_=nav_AccountFlyout_orders

When i click on the (pinned) extension no buttons for the years are shown and the activity label states "idle".
The buttons above for clearing the cache and for forced logoff are not reacting.

I've cleared amazon cookies like stated in the help (https://github.com/philipmulcahy/azad/blob/master/README.md) but nothing changed.
I disabled my piHole AdBlocker but that also didn't changed anything.

Is it eventually broken for .de? Can i test something else? Can i provide more data?

best regards
Rolf

**Comment by philipmulcahy** [comment]
Does it work for amazon.de <http://amazon.de/>?

**Comment by telepath** [comment]
No, neither seems to work.

**Comment by telepath** [comment]
[www.amazon.de-1665659696723.log](https://github.com/philipmulcahy/azad/files/9776038/www.amazon.de-1665659696723.log)

**Comment by philipmulcahy** [comment]
they turned smile off, so this is obsolete.
I need to get around to removing the references to smile in the code.
