### ISSUE TITLE
Seems to lock up on my order 203-8539891-3708342

### ISSUE THREAD

**Issue by Fma965** [philipmulcahy/azad#2]
Hey, it seems to lock up on this order...

203-8539891-3708342

which is just a USB 2.0 to TTL UART 6PIN CP2102 Module Serial Converter

any ideas why?

![image](https://user-images.githubusercontent.com/1707290/28238470-effc81ee-694b-11e7-91b0-4c4467f338aa.png)

**Comment by philipmulcahy** [comment]
Strange…

If it were my account I’d attack this using the debugger built into chrome, and narrow down on the suspect code location using breakpoints (having inserted a debugging line into the code that only fires if we’re looking at the poison order).
Is this within your capabilities?
The steps to do so would be something like this:
1) disable the extension from the web store: chrome://extensions <chrome://extensions> and then uncheck the enabled box
2)  download the code (you’ve found it already!)
3) tell chrome about it: I think this is on the same chrome://extensions <chrome://extensions> page - you just show it the folder where the code is.
4) check it works the same
5) put in a line just under https://github.com/philipmulcahy/azad/blob/master/order.js#L68 <https://github.com/philipmulcahy/azad/blob/master/order.js#L68>
```
If this.id == ‘your order id’ {
  alert(‘blah’);
}
```
Put  break point on blah
6) step through the code after you hit the breakpoint.
7) fun
8) profit

Thoughts?
p.s. I’m wondering if I should have asked you to describe how you know it’s locking up on that particular order.
p.p.s There is some evidence that Amazon are beginning to mess the extension up by rate limiting the order fetch queries - they may be doing this by serving captcha type pages, which the extension is unequipped to handle (or even report) right now. More info would be great if you see this.

Philip

**Comment by philipmulcahy** [comment]
Closing: I'm assuming it's not an issue any more - let me know if I'm wrong.

**Comment by ScottMcNay** [comment]
You didn't reply to Fma965 by name; maybe didn't get notified?
