### ISSUE TITLE
Make azad work in India

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#20]
from "Soma Sekhar Kunchi" on feedback for https://chrome.google.com/webstore/detail/amazon-order-history-repo/mgkilgclilajckgnedgjgnfdokkgnibi/support?hl=en...

Hi,
I am from India. As i see it doesn't work for amazon india. 
Can you please extend this extension to AMAZON.in

https://www.amazon.in/gp/your-account/order-details/ref=oh_aui_or_o00_?ie=UTF8&orderID=

Thanks

**Comment by philipmulcahy** [comment]
v1.7.18 has experimental amazon.in support.

**Comment by philipmulcahy** [comment]
closing: no response from Soma.

**Comment by avinashdhoot** [comment]
Request support for Amazon.in. Am able to pick up historical orders from US, but nothing from India is fetched.

If it is experimentally supported in v1.7.18, how may I try this version in my chrome extension?

Will be happy to help code too :-)

**Comment by philipmulcahy** [comment]
Hi avinashdhoot.
Thanks!
I don’t have a .in account - are you able to attach your console logs to this ticket so we can debug together?
Philip

**Comment by avinashdhoot** [comment]
Surely. Give me a few days.

**Comment by avinashdhoot** [comment]
Hi Philip,

Thanks for responding. 

Attached below are the console logs, and the CSV file (zipped) that gets generated.

Avinash

[www.amazon.in-1543964512287.txt](https://github.com/philipmulcahy/azad/files/2646502/www.amazon.in-1543964512287.txt)

[amazon_order_history.zip](https://github.com/philipmulcahy/azad/files/2646503/amazon_order_history.zip)

**Comment by philipmulcahy** [comment]
Thank you!
It might be a couple of days until I get time to look at them - don’t worry - I’ve not forgotten!

**Comment by philipmulcahy** [comment]
Hi avinashdhoot,

1) I'm looking at one of your CSV file's orders - "Agro Fresh Black Pepper, 100g; ..." I see more than four items - they're semicolon separated - are you saying that only four of them appear in the GUI version?

2) I don't understand how this could happen unless you started on the .com site. Clicking on an orange button doesn't advance to a new page - it re-writes the existing page. It might be worth trying this (as an experiment. i) go to example.com ii) go to amazon.in/orders iii) press an orange button and let it do its stuff iv) press back. I'd expect you to end up on example.com

Sorry for slow turn-around!

Philip

**Comment by avinashdhoot** [comment]
Hi Philip,

    1. Yes, GUI shows 4 items, and then a link to all the full list items.
The words "See all 25 items" is hyperlinked to the full list. Here are the
screenshots.
        a. https://i.imgur.com/acvUzwv.png
        b. Complete order on clicking the link "See all 25 items" -
            i. https://i.imgur.com/dd6myHc.png
            i. https://i.imgur.com/jQW1eGm.png
            i. https://i.imgur.com/p0oEG8O.png
            i. https://i.imgur.com/nSvUM1v.png

    2. Went to Amazon.com; went to Amazon.in/orders; pressed orange button
"2018"; pressed "back". Pressing back leads me directly to Amazon.com & not
Amazon.in/orders

Did this on my own next:

    3. Went to Amazon.in; went to Amazon.in/orders; pressed orange button
"2018"; pressed "back". Pressing back leads me directly to Amazon.in & not
Amazon.in/orders

Please let me know how I may help further.

Thanks,
Avinash

**Comment by philipmulcahy** [comment]
@avinashdhoot 
1) I understand now. Thanks for persisting! I think this is going to require some work. It's interesting that your screenshot shows four in the abbreviated list, but the extension is getting 10. I've made https://github.com/philipmulcahy/azad/issues/42 so we don't keep posting on this closed issue.
2) is expected+intended - the stuff the orange button displays is a re-written Amazon.in/orders - the browser doesn't recognize it as another page, so pressing back takes you to the page in your history immediately before /orders e.g. amazon.in
3) ditto
