### ISSUE TITLE
Issues with a year of data on www.amazon.ca with audible.ca links

### ISSUE THREAD

**Issue by jc259** [philipmulcahy/azad#201]
Running on amazon.ca 

I've used the plugin to download all 2015-2022 however 2019 errors out.  There are 230 items 10 show as error once the job finishes running 1 shows up as a cache_hit even after clearing the cache.

I have deleted all cookies (site data), logged out, restarted, tried a different machine, cleared cache, force logged out.
Tried rerunning with different combinations of the check boxes in the plugin.

1) Well the job is running I see multiple of the following  show up above the table that is building itself then they disappear and the table is left.  These all seem to have www.audible.ca in them.  

"HTTP0: too many redirects when fetching https://www.amazon.ca:443/gp/redirect.html/ref=ppx_yo_dt_b_amzn_o07aud_?_encoding=UTF8&location=https%3A%2F%2Fwww.audible.ca%2Forder-detail%3ForderNumber%3DD01-2269741-4608260%26orderType%3DREGULAR&source=standards&token=4EE094C6DCA300292B9FF579CEF4808E5207A537 which has been redirected You might want to consider using the "force full log out" button and logging yourself back into Amazon."

2) After the table is built there are only 130 items in the table even though the plugin shows 230 complete and it won't download the spreadsheet. I've just copy pasted the plain table to check it.

3) 10 rows have pending items showing in some of the cells. All of these have order numbers with a D in front and are audbile.ca links

**Comment by jc259** [comment]
In the report that does get produced there are some D0X-XXXXXX-XXXXX order from audible which have their data populated. It's only 10 which have the pending status in their info.   

And as I mentioned the report still only has 130 lines instead of the 230 mentioned in the plugin dialog showing compelete.

**Comment by jc259** [comment]
Emailed console log to azadextension@gmail.com

**Comment by jc259** [comment]
First errorin the log  is below . If I grab the redirect link (just after this sentence) it does work when pasted into chrome. "https://www.amazon.ca/gp/redirect.html/ref=ppx_yo_dt_b_amzn_o07aud_?_encoding=UTF8&location=https%3A%2F%2Fwww.audible.ca%2Forder-detail%3ForderNumber%3DD01-2269741-4608260%26orderType%3DREGULAR&source=standards&token=4EE094C6DCA300292B9FF579CEF4808E5207A537"

First error in console log.
Access to XMLHttpRequest at 'https://www.audible.ca/order-detail?orderNumber=D01-2269741-4608260&orderType=REGULAR' (redirected from 'https://www.amazon.ca/gp/redirect.html/ref=ppx_yo_dt_b_amzn_o07aud_?_encoding=UTF8&location=https%3A%2F%2Fwww.audible.ca%2Forder-detail%3ForderNumber%3DD01-2269741-4608260%26orderType%3DREGULAR&source=standards&token=4EE094C6DCA300292B9FF579CEF4808E5207A537') from origin 'https://www.amazon.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
signin.ts:74 

HTTP0: too many redirects when fetching https://www.amazon.ca:443/gp/redirect.html/ref=ppx_yo_dt_b_amzn_o07aud_?_encoding=UTF8&location=https%3A%2F%2Fwww.audible.ca%2Forder-detail%3ForderNumber%3DD01-2269741-4608260%26orderType%3DREGULAR&source=standards&token=4EE094C6DCA300292B9FF579CEF4808E5207A537 which has been redirected 
You might want to consider using the "force full log out" button and logging yourself back into Amazon.

**Comment by H-Milch** [comment]
Same Problem here.
3 Errors are shown then  only blank page
Happend only when show items not orders is choosen.
Erros like this:
TTP0: too many redirects when fetching https://www.amazon.de:443/gp/redirect.html/ref=ppx_yo_dt_b_amzn_o09?_encoding=UTF8&location=https%3A%2F%2Fwww.audible.de%2Forder-detail%3ForderNumber%3DD01-4957045-4680655%26orderType%3DREGULAR&source=standards&token=02DF8829EB6F0E002DDC876B597C526D2F0C7F94 which has been redirected You might want to consider using the "force full log out" button and logging yourself back into Amazon.

**Comment by philipmulcahy** [comment]
@H-Milch suggests that it's an item page that's blowing us up.

everyone: this _might_ be that you've been logged out of some of Amazon but not all of it. The force logout button is designed to reset you forcefully (you'll have to log back in after pressing it). Hypothesis: maybe you've got some good results in azad's cache, but by the time you got to the problem, some part of Amazon had had enough (either based on time, or how many requests azad had been hitting it with). After logging back in, if you go straight to the year that is causing problems, does it still break?

**Comment by philipmulcahy** [comment]
1.9.34 has some improvements in how Azad handles "bad" orders - e.g. ones where its parsing code is surprised by something in the order. I identified various scenarios where it would cause the response to be disproportionate instead of just skipping the "bad" order.
