### ISSUE TITLE
CSV will not get downloaded

### ISSUE THREAD

**Issue by adrian-vogler** [philipmulcahy/azad#205]
I have a problem because the CSV will not get downloaded.
I wait for the scraping to finish - no download.
I click on download spreadsheet - no dwonload.

**Comment by wrylee** [comment]
I had the same problem on Edge but it worked correctly on Chrome. I did only a single full year, and it took a bit. I thought it was hung, it eventually completed.

**Comment by philipmulcahy** [comment]
@wrylee You may be using edge, but I'm not supporting it on edge - sorry!
@adrian-vogler:
I need more help than this.
Here's what you could do to give some clues:
1) open chrome dev tools
2) get the console up (see screenshot below) - on the mac, pressing esc once the dev tools are open toggles the console.
3) get your output table scraped
4) clear the console (right click and choose the right option)
5) press the blue csv button
6) capture the messages (including the filenames on the right hand side)  and paste into this thread.

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/1668892/228986576-c13d9f76-92a4-4384-9048-f808a81bfdcd.png">

**Comment by drewclauson** [comment]
I'm having this issue, where in Chrome, it doesn't let me download the CSV.  Here is my developer console output when I click the Download CSV button.

![image](https://user-images.githubusercontent.com/10655807/235196963-fa1e60ea-1009-499e-b133-5dfdb6958fd0.png)

**Comment by philipmulcahy** [comment]
@drewclauson I am going to guess this is a problem with retrieving the extension's settings.
I've been making a lot of (as yet unreleased) changes to this code recently - would you mind trying out https://www.mulcahyfamily.org/azad/azad_b036b359.zip and see if it works better?

**Comment by philipmulcahy** [comment]
@drewclauson  https://github.com/philipmulcahy/azad#how-to-try-out-an-experimental-version

**Comment by drewclauson** [comment]
> @drewclauson https://github.com/philipmulcahy/azad#how-to-try-out-an-experimental-version

I’ll check it out, thank you!

**Comment by philipmulcahy** [comment]
assuming this is fixed - please reopen with feedback if it isn't - thanks
