### ISSUE TITLE
Easy Book Prep Proposal (NOT MALWARE!)

### ISSUE THREAD

**Issue by JannellEzPrep** [philipmulcahy/azad#208]
Hello, I work with a company called Easy Book Prep (a legally registered company) where we provide inventory tracking software and book-prepping services to Amazon Book Arbitrage sellers. Here is the [link to our website](https://ezbookprep.com/home-page48128874).
We have developed an extension that automatically takes our client’s Amazon order data and uploads it to our inventory tracking system with the click of a button. For the past 5 years, our extension has been able to do this by downloading the order reports that Amazon provided and extracting the data from that to our system. However, Amazon recently decided to stop generating these order reports which as you can imagine, is bad news for us as our extension has no other way of getting our clients’ order history. 
 
This is where you come in, your scraping software could be just the thing that we need to keep our business running as it has for the past 5 years by providing a way for clients to efficiently and conveniently upload their order history data in order to track their ever-growing inventory. We would like to set up a meeting with you and the CEO so that we can come up with some sort of proposal that will work for everyone and to get into the full details of how your software can help us. I sent you an email that has the link to schedule the meeting. We would at the very least, like to have a conversation with you. If you are not interested, please let me know. But if you are, we look forward to hearing from you soon. Thank you.

**Comment by philipmulcahy** [comment]
We're talking via private email, so I'll close this.
