### ISSUE TITLE
Adding Tax and Shipping Columns to "Items Not Orders"

### ISSUE THREAD

**Issue by DerekCarty** [philipmulcahy/azad#211]
When you use this to pull entire orders, it has columns for things like Tax and Shipping. But when you select "Show items not orders", it just gives you the base price for each item but doesn't include the associated tax or shipping. Would it be possible to add this for individual items? Thanks so much for your great product!

**Comment by philipmulcahy** [comment]
I don't think doing this is feasible. Amazon doesn't break the tax (or other charges) down per item (or at least they don't do so on the sample of multi-item orders I've just looked at in my .co.uk account), so our code would have do interpolate it (perhaps pro-rata), which 1) may not be correct and 2) users can do for themselves.
Am I missing a piece of the puzzle?

Yours,

Philip

**Comment by philipmulcahy** [comment]
feel free to reopen if you can see where amazon is providing this breakdown
