### ISSUE TITLE
Enhancement: Add status info - order has shipped or has been delivered

### ISSUE THREAD

**Issue by ibuytomuch** [philipmulcahy/azad#213]
Amazon USA
Amazon address 
https://www.amazon.com/gp/your-account/order-history/ref=ppx_yo_dt_b_orders_bap_c?ie=UTF8&orderFilter=months-3

Request for additional order status information in the Order History Report to show that an order has shipped or has been delivered.  This information can be extracted from two lines shown on the **Your Orders** page just below the ORDER PLACED… box:

Line One shows an order status followed by a date.  Two examples:
  "Arriving May 15-May31"  <-- indicates this order has shipped.
  "Delivered Apr 24, 2023"  <-- indicates this order should have been received.
Line Two is an optional note immediately under Line One and may or may not be blank.  A typical example:
  "Package was left inside the residence’s mailbox"

This will allow the customer to anticipate the arrival of an order and to identify a delivery problem if the status indicates the order was delivered but the customer has not received it.  This screen shot shows two orders on the Your Orders page:

![20230502_122818](https://user-images.githubusercontent.com/132399835/235786828-ec4d4b85-2787-401b-a972-84aa8a06c926.jpg)

I order much from Amazon but I'm not a programer and so cannot offer any code suggestions.  However, I'm sure a LOT of users would appreciate this additional order-tracking information if someone were to implement it.  Thanks.

**Comment by philipmulcahy** [comment]
yep - there are a lot of commercial users that want this - I am going to try for it in the second batch of preview features once we see how well https://www.justgiving.com/fundraising/azad-pah out of the first batch of quid-pro-quo features (single month downloads and ASINs).

**Comment by philipmulcahy** [comment]
merged to #221
