### ISSUE TITLE
REQUEST: add option to change the sepperator from "," to ";"

### ISSUE THREAD

**Issue by eXc0LIn** [philipmulcahy/azad#214]
Please delete or move this Request to the right place if i am wrong here.

Request:
Is it possible to add a option/ setting for the csv export to change the col seperator from "," to ";" ?

Reason:
If i export the csv the collums make no sence because some are bound together and some are seperated at the wrong possitions.
I cant work with the csv export without alot of work/ editting with notepad++.

**Comment by philipmulcahy** [comment]
1) there are various dialects of CSV, that handle embedded separators differently. Are you sure you understand what dialect AZAD is using? The code is [here]( https://github.com/philipmulcahy/azad/blob/b036b3590a488bcd35b032ee0d093c260a74a1d2/src/js/csv.ts#L74).

2) have you thought about what you're going to do if there are real semi-colons in the data?

3) if you're still sure you want it (I cannot imagine anyone else will), a £1000 charity donation at https://www.justgiving.com/fundraising/azad-pah where you put "#214" in the comment (and then ping me here to get my attention) will do the trick: it might take me up to a month to find the time to do it.

Yours,

Philip

**Comment by philipmulcahy** [comment]
I assume silence == "polite decline of your kind offer".
