### ISSUE TITLE
Enhancement: Add 'Est. Tax Value' Field?

### ISSUE THREAD

**Issue by gamegrrl** [philipmulcahy/azad#215]
Apologies in advance if I'm not properly structuring my request. This is my first time on Github.

Would it be possible to add the 'Est. Tax Value' field? This is useful for Amazon Vine members who need that number to keep track of this field total which ends up being a part of their 1099-NEC grand total at tax time.

I also came here to ask about including the ASIN field, but it looks like maybe that got downvoted?

**Comment by philipmulcahy** [comment]
Est Tax: sounds do-able, but we’re going to need a little help from you unless you’re in the UK - you can start by sending an order debug dump file (see GitHub readme) to me at the extension's gmail address (azadextension@…), with #215 somewhere in the subject line. Then post back here to let me know it’s in the gmail account (I don’t look at it unless I know there’s something for me there - it gets lots of requests from scumbags who want to use the extension to distribute malware).

ASIN - deployed progressively yesterday and today in 1.9.26. This was very popular amongst commercial users, and was relatively easy to deliver (in the items not orders mode). Until charity donations reach GBP 5000, I’m keeping it behind the subscription paywall (currently priced $5/year for all preview features, though might get more expensive depending on how much work I do). The subscriptions go to the same charity (less the platform fees for stripe, extpay and JustGiving), and contribute to the GBP 5000 target. Once that’s reached, the batch 1 features become free.

Yours,

Philip

**Comment by philipmulcahy** [comment]
4 months on and no response: assuming no longer needed -> close
