### ISSUE TITLE
2 Feature requests. 

### ISSUE THREAD

**Issue by mendelsphotography** [philipmulcahy/azad#217]
1. To better visualize an order with various items and prices, one option may be to display them in separate rows. Another approach could be to add a column indicating the number of items contained in each order.
2. Refund dates. Add the date refund is issued.

**Comment by philipmulcahy** [comment]
I need one issue per request and the title needs to be descriptive enough to tell them apart.
Sorry!

**Comment by philipmulcahy** [comment]
Thank you!
