### ISSUE TITLE
Feature request: better visualize an order with various items and prices.

### ISSUE THREAD

**Issue by mendelsphotography** [philipmulcahy/azad#219]
To better visualize an order with various items and prices, one option may be to display them in separate rows. Another approach could be to add a column indicating the number of items contained in each order.

Currently, it's all squeezed into 1 row and pricing together.

**Comment by philipmulcahy** [comment]
have you played with the items-not-orders view?

**Comment by philipmulcahy** [comment]
no response in 9 months -> closing
