### ISSUE TITLE
order delivery status

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#221]
This issue combines work on three previous requests:
#118, #180, #213 which I am closing with a comment pointing at this issue.

**Comment by philipmulcahy** [comment]
I've been reaquanting myself with xpath queries
here's one that finds items links in an order detail page (one order)
```
//div[contains(@class, ' shipment ')]//a[@class='a-link-normal' and contains(@href, '/gp/product/') and normalize-space(text())]
```
You'll notice that there is div whose classes include 'shipment': there can be more than one shipment
e.g. orders contain a list of shipments, each of which contain a list of items
I guess items that are not allocated to a shipment either get a dummy shipment or maybe no shipment.
Time to buy a cheap, long-lead item that I actually want.
Given we're already finding all the items, maybe we can find shipment elements by tracking back up from the item?

**Comment by philipmulcahy** [comment]
OK: I've made some progress, and some discoveries:
some orders (such as an example in my .co.uk account with id ending in 6100313, which is about 6 months old), have a shipment element, but no delivery info EXCEPT for a "transaction" element (in a box somewhere above the shipment element).
```
<div class="a-box-inner">
  <div aria-live="polite" class="a-row a-expander-container a-expander-inline-container show-if-no-js">
    <a href="javascript:void(0)" data-action="a-expander-toggle" class="a-expander-header a-declarative a-expander-inline-header a-link-expander" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:true, &quot;expand_prompt&quot;:&quot;&quot;, &quot;collapse_prompt&quot;:&quot;&quot;}"><i class="a-icon a-icon-collapse"></i>
      <span class="a-expander-prompt"> Transactions </span>
    </a>
    <div aria-expanded="true" class="a-expander-content a-expander-inline-content a-expander-inner a-expander-content-expanded" style="overflow: hidden; display: block;">
      <div class="a-row">
        <span class="a-color-secondary"> Delivery 1: </span> 
        <span>
          9 January 2023 - AmericanExpress ending in 1013:
          <nobr>£6.05</nobr>
        </span> 
      </div>
      <br>
      Total:
      <nobr>£6.05</nobr>
    </div>
  </div> 
</div>
```
In this order, I cannot find any information about delivery - e.g. whether it was delivered, tracking etc. It looks like maybe delivery is "assumed" after a certain amount of elapsed time. Displaying "unknown" for status is better than saying undelivered, but it's gonna look messy. I think I'd rather do that than confidently say "delivered" and face the wrath of users whose stuff never showed up.

I suspect we're heading towards a 3+ strategy strategy:
I) recent physical orders with delivery and maybe tracking info
II) old physical orders
III) digital orders: no delivery info ever

**Comment by philipmulcahy** [comment]
At 82d9773..19eec1f It's all looking pretty encouraging except for one failing test: items for the regression test 112-1097135-4205023_2021-03- 20 are {} instead of a longish list of groceries.

**Comment by philipmulcahy** [comment]
https://www.mulcahyfamily.org/azad/azad_a0b77160.zip has a beta build that has shipment info in the items table.

I'm particularly interested in feedback (here) on these three areas:
1) have I missed an obvious easy win in terms of the columns, formatting etc?
2) if you're using this on a site that doesn't use english, then sharing some order debug files would enable me to get shipping scrapes working properly for your language.
3) usability bugs for english language Amazon site users

please include the version (a0b77160 in this case) with your feedback.

Yours,

Philip

**Comment by philipmulcahy** [comment]
https://www.mulcahyfamily.org/azad/azad_39b5aa6b.zip has a beta build that has shipment info in the items table.

I'm particularly interested in feedback (here) on these three areas:

have I missed an obvious easy win in terms of the columns, formatting etc?
if you're using this on a site that doesn't use english, then sharing some order debug files would enable me to get shipping scrapes working properly for your language.
usability bugs for english language Amazon site users
please include the version (https://github.com/philipmulcahy/azad/commit/39b5aa6bf2ff58bd59764c4aa2e0b952bebd6652 in this case) with your feedback.

Yours,

Philip

**Comment by philipmulcahy** [comment]
a bunch of folks have downloaded the test build above, but no feedback has resulted.
I, for one, found a bug: some items are duplicated - this is fixed in a private build.

**Comment by philipmulcahy** [comment]
v1.9.31 released globally - let the bug reports flow

**Comment by mloraditchhelion** [comment]
Just now finding this utility, love it and have paid for support. Would really like the actual tracking number in the reports. The reports help tracking orders but having this right there is easier to match up with other systems.

**Comment by mloraditchhelion** [comment]
I don’t need links. I literally just want a column with the tracking numbers so if it’s UPS its 1Z0627EX0314105999
Or an amazon type tracking 
TBADD0000404584

does that make sense?
