### ISSUE TITLE
Amazon Rewards Points

### ISSUE THREAD

**Issue by LRNewton** [philipmulcahy/azad#223]
There appears to be no way to see if you used Amazon Visa Rewards points to pay for all (or part of an order.)
Am I missing something?

**Comment by philipmulcahy** [comment]
I think you are not wrong: I've never heard of Amazon Visa Rewards, and so don't have the ability to play with it/them on my account.
I'll leave this open to see who else votes for it.

**Comment by LRNewton** [comment]
Amazon (like eBay, Venmo, the airlines, Disney, etc.) has 
it's own branded credit card.
When you shop using the credit card, you earn "rewards points."
When you shop at Amazon using the credit card - you earn 5% - so you might want to look at getting one.
You can use the points (like cash) to make purchases on Amazon.
I have attached two examples of orders using "rewards points."  One is a partial pay with points, the other is fully paid with points,
I have also included the lines from the CSV file that were generated from these transactions - so you can see the issue.
I would be happy to help you troubleshoot the issue, if you like.
 
 
----- Original Message -----
From: Philip Mulcahy ***@***.***>
Reply-To: philipmulcahy/azad ***@***.***>
To: philipmulcahy/azad ***@***.***>
Cc: LRNewton ***@***.***>, Author ***@***.***>
Sent: 7/9/2023 1:54:44 PM
Subject: Re: [philipmulcahy/azad] Amazon Rewards Points (Issue #223)



I think you are not wrong: I've 
never heard of Amazon Visa Rewards, and so 
don't have the ability to play with it/them on my account.
I'll leave this 
open to see who else votes for it.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by philipmulcahy** [comment]
I am keen not to create the (false) impression that I am likely to be able to prioritise this in the near future, but I'm not seeing any attachments on your post. Maybe ones on email replies get stripped off by github, and you have to attach them directly in the website?

**Comment by philipmulcahy** [comment]
no response from user in more than half a year-> closing
