### ISSUE TITLE
Application crashes on orders with at least 64 items

### ISSUE THREAD

**Issue by whytheheckme** [philipmulcahy/azad#233]
Hello,

This is my first time using the tool, but I was facing an issue where any report request would hang with a certain number of queries remaining. Using the developer console, I tracked down which page and order it was hanging on, and I noticed that the abnormal thing about this order was the number of unique items, there were 64. After I archived the order, the issue went away.

Thanks,
Jacob

**Comment by philipmulcahy** [comment]
Thanks for reporting!How would you feel about saving the html for the order detail page and the index page (the one that has 10 orders including the bad one) to ***@***.***? As a bonus, could you also give me the second and last/final pages of the detail page?That might make it possible for me to reproduce and hopefully fix the problem.Sent from my phoneOn 28 Aug 2023, at 08:26, whytheheckme ***@***.***> wrote:﻿
Hello,
This is my first time using the tool, but I was facing an issue where any report request would hang with a certain number of queries remaining. Using the developer console, I tracked down which page and order it was hanging on, and I noticed that the abnormal thing about this order was the number of unique items, there were 64. After I archived the order, the issue went away.
Thanks,
Jacob

**Comment by philipmulcahy** [comment]
I cannot find a response in azadextension@gmail.com, so closing - if I'm wrong and you did follow up, then please re-open and chastise me here!
