### ISSUE TITLE
Donation not recognized - can't access additional features

### ISSUE THREAD

**Issue by dshakesp** [philipmulcahy/azad#241]
Hi,

I just donated to PAH and then logged back into your Amazon Report extension and keep getting message that my email address is not in your records so I can't access the premium features.

Please see attached screenshot of payment

Thanks, David
![Screenshot 2023-09-23 203517](https://github.com/philipmulcahy/azad/assets/145880245/7cf20a41-27e4-4e40-81f0-6fbd475e96f4)

**Comment by philipmulcahy** [comment]
Thank you for donating!The premium subscription is accessed via a different route: you need to click on the grey/text button on the control pop up and then one of the three buttons on the revealed wall of text about premium features (I cannot remember what the title of the right one is: am away from civilisation this weekend). This button takes you to another popup controlled by ExtensionPay and Stripe that handles subscriptions and links them to your email. You can go to this same page to re-login and check status if the premium stuff stops working. Right now the only paywalled feature is some columns that show shipments and tracking links for recent orders: everything else is free. It is my intention that free features remain free (no bait and switch).Sent from my phoneOn 24 Sep 2023, at 01:37, dshakesp ***@***.***> wrote:﻿
Hi,
I just donated to PAH and then logged back into your Amazon Report extension and keep getting message that my email address is not in your records so I can't access the premium features.
Please see attached screenshot of payment
Thanks, David

**Comment by philipmulcahy** [comment]
I added this section to the README: https://github.com/philipmulcahy/azad/blob/master/README.md#i-subscribed-but-i-am-not-getting-premium-features
