### ISSUE TITLE
Purchases before 1/4/2023 are missing

### ISSUE THREAD

**Issue by rmj007** [philipmulcahy/azad#242]
Purchases before 1/4/2023 are missing - I have cleared cache, restarted browser, 'puter - the scrape does not include transactions on 1/1/23 for me.  BTW - I contributed $$ but my email was never added to the registered list.  - How to fix?

Thank you for your efforts - definitely a consumer need.

**Comment by philipmulcahy** [comment]
Hello @rmj007!

On $$, have you seen [this article](https://github.com/philipmulcahy/azad#i-subscribed-but-i-am-not-getting-premium-features)?

On missing orders, 
Definitely not related to paywall - sounds like it might be a bug.
ii) we've got two routes we could go down
a) I have nearly put the finishing touches to a change to how the extension does result caching, mostly to deal with errors being silently swallowed. I intend for it to go live in the next week (work schedule permitting) - you might want to wait for it - it will be 1.9.33 (or higher if I mess up on the first try). If there's something "poisonous" about one or more of your orders then it has a better chance of making it through the scrape, or at least better describing the problem in the log.
b) use this ticket for a debugging exercise. As you might imagine, your post doesn't give me nearly enough to work with on its own, as I don't have access to your amazon account. The next thing to share would be a console log, which you can attach here. I cannot promise to work on it quickly though - I am totally stretched at my day job at the moment, and I have at least two bugs impacting multiple users to sort out first.

Yours,

Philip

**Comment by philipmulcahy** [comment]
Sorry for delay on 1.9.33 - I'm trying to get another feature (that will be released at the same time) validated. Would you like a private build of it?
It would require you to manually install it - not at all fiddly, but you need to be careful who you accept code like this from: there are no protections from any "evil" code you might install. Any test builds from me will come from "mulcahyfamily.org/azad"

**Comment by philipmulcahy** [comment]
1.9.34 went live last night. Please reopen this issue if that didn't improve things.
