### ISSUE TITLE
Paid for 1 time donation. Can't sign in

### ISSUE THREAD

**Issue by Snoodleboodle** [philipmulcahy/azad#245]
Put my email on the donation. Email receipt came to me. When I attempt to use that email to sign in it tells me there's no record of it.

**Comment by philipmulcahy** [comment]
Nice handle!Have you read the readme? In particular:  https://github.com/philipmulcahy/azad#i-subscribed-but-i-am-not-getting-premium-featuresIf that didn’t work, you’re going to have to share some details: email address, date and rough time, country the card is in, and last four digits. Do that in an email to the extension’s address, not here, but reference your handle and the ticket id in the subject.Sent from my phoneOn 4 Oct 2023, at 23:12, Snoodleboodle ***@***.***> wrote:﻿
Put my email on the donation. Email receipt came to me. When I attempt to use that email to sign in it tells me there's no record of it.

**Comment by Snoodleboodle** [comment]
I did look at that readme. Truth be told...I'm trying to get taxes done...and I don't know if my working on trying to get this to work will take me more or less time that just inputting everything. I looked at my bank account this morning and I was double charged for the donation. One time it showed it in caps...the next time in lower case. Weird. 

I'm up against a deadline and can't be spending time reading on the intricacies of the apps workings. I have no idea what "do that in an email to the extensions address" means. I'll tell you the email was wfgsnix@yahoo.com...the afternoon of 10/4...USA...0314. If its easy to help me...let me know...if it requires me to do a bunch of things...just don't worry about it. I'm happy to support the cause...if even I can't use the app.

**Comment by philipmulcahy** [comment]
I see no stripe payment for your email address:
<img width="1041" alt="image" src="https://github.com/philipmulcahy/azad/assets/1668892/3569b276-66f3-4c9e-ad86-894e78bd578c">,

and here are the recent altruistic (non-subscription) donations (none include your email address):
<img width="629" alt="image" src="https://github.com/philipmulcahy/azad/assets/1668892/e466bf24-4cfc-451d-9932-7b0aef9a22dd">

I am wondering if you're one of the $2 anonymous donations (_not subscriptions_) - perhaps you shared your email address with JustGiving and clicked on the "remain anonymous".
If that's the case you might want to consider my immediate thoughts:
1) thank you for your donation!
2) how would I know who you are? I am not JustGiving, and you have asked them not to share your details.
3) given the value of the skills required to develop and maintain the extension (I know how long it took me, and I know how much I get paid in my day job, using a related skill set), you might want to consider the value of the freely given time you have consumed with this ticket while you are unwilling to read basic self help documentation I have provided - I would rather spend my donated time working on new features for users and hopefully generating more revenue for the hospice.
4) you probably don't need the premium features to get the info you want for your tax return - the stuff you need is free: you should spend your time figuring out how to use the extension.
5) You've had two at least two steers to read the subscription instruction (once in the extension's interface, and once in my initial response) AND you shared your email address with the internet despite me warning you not to.
