### ISSUE TITLE
Support for Amazon.sa

### ISSUE THREAD

**Issue by waseem7** [philipmulcahy/azad#246]
To support Saudi Arabia Amazon site

www.amazon.sa

**Comment by philipmulcahy** [comment]
Hello @waseem7,

If I create a test build of this, will you test it and report back results? (I don't want to release it unless I know it works, or people will whinge).

Yours,

Philip

**Comment by philipmulcahy** [comment]
first pass is likely to work only on the english version of the site:

<img width="718" alt="image" src="https://github.com/philipmulcahy/azad/assets/1668892/e9416385-e3d2-4890-99ae-77a15b04ec51">

**Comment by philipmulcahy** [comment]
https://www.mulcahyfamily.org/azad/azad_8206f26f.zip has no chance of working unless you've done the english thing in the post above.
Then: https://github.com/philipmulcahy/azad#how-to-try-out-an-experimental-version

**Comment by shkgleb** [comment]
Hello, @philipmulcahy 

I successfully tested this build on the amazon.ae domain, by adding "https://www.amazon.ae/*" to the content_scripts.matches[] in the manifest.json file, and everything works perfectly.

However, I encountered a minor issue: while processing 300 orders (thousands of items), Amazon started giving a 503 error. The solution was found by reducing the number of concurrent connections from 6 to 1, changing "this.CONCURRENCY = 1; //6". Also, I noticed that the parsing process unexpectedly stopped a couple of times without any errors or results, as if the process terminated on its own.

Either way, thanks for your work!

**Comment by philipmulcahy** [comment]
Oops - I never saw your post before today @shkgleb - I was just about to delete the development branch! Sorry
1) thank you for looking!
2) I think that the getting stuck _might_ have been solved - can I send you another dev build? (As well as accidentally ignoring you, I was working on a new scheduling model, that provides better transparency in the logs as to what's gone wrong, and during this I found a few corner cases). I cannot make concurrency 1 the default or the users will come for me with pitchforks (it'd be too slow for the power users) - is it possible the SA site has lower rate limits?

Yours,

Philip

**Comment by philipmulcahy** [comment]
https://www.mulcahyfamily.org/azad/azad_7b1d4a30.zip - let me know how it works.
If it misbehaves out of the box (before you've hacked it down to no parallelism), then would you mind sharing a console log (with all log levels turned on)?

Thank you!

**Comment by Onurrr** [comment]
> Owner

Just tested this version on .ae ( by changing the url in the manifest file) like [shkgleb](https://github.com/shkgleb) mentioned before.

Looks like it's working fine, might need some extra testing on .SA version though.

<img width="312" alt="Screenshot 2024-01-02 at 09 16 50" src="https://github.com/philipmulcahy/azad/assets/9193729/99264cd3-b129-4950-8dc8-5c24cf051791">

**Comment by philipmulcahy** [comment]
those POST and GET errors are amazon javascript doing background stuff that get interleaved into the azad logging - they're annoying but irrelevant.

I will add .ae to the manifest and update the chrome store page to mention it - expect a release in about a week - thank you for testing!
