### ISSUE TITLE
Digital orders showing incorrect tax amount

### ISSUE THREAD

**Issue by danniboy** [philipmulcahy/azad#249]
The report has the correct total amount but the tax amount is not the tax amount but rather the subtotal/total before tax.

I also noticed that an order that is for a digital purchase gets a digital order number in the report but amazon.com does not show it as a digital order (ID order number but rather like a regular order).

There was another issue with the items field being blank for digital orders and I have the same issue.

I do not want to start another thread but where should I ask a question regarding the shipment/tracking option?

**Comment by philipmulcahy** [comment]
Sending me an [order debug dump file](https://github.com/philipmulcahy/azad#how-to-save-and-send-an-order-debug-json-file) for an impacted order to azad_extension@gmail.com with #249 in the subject line is the right next step.

**Comment by danniboy** [comment]
I just sent the email.


> Sending me an [order debug dump file](https://github.com/philipmulcahy/azad#how-to-save-and-send-an-order-debug-json-file) for an impacted order to [azad_extension@gmail.com](mailto:azad_extension@gmail.com) with #249 in the subject line is the right next step.

**Comment by philipmulcahy** [comment]
got 'em: it might be a few days until I get enough time to look at this properly, but you should have me set up to make progress - thanks!

**Comment by philipmulcahy** [comment]
[Tracking/shipping](https://github.com/philipmulcahy/azad/blob/master/doc/img/items_csv_2023-12.png) is mostly working now, and gets a bit better in the forthcoming (next 48hrs depending on google's review process) v1.10.0 - most of it is behind the paywall: sorry. This is for two reasons (1 - revenue from commercial users, who don't seem to do much altruistic donation; 2 - limits number of complaints about teething troubles)

Meanwhile, I've just strafed the supplicants on a few other bugs for more info, but this is the only one I have a clear workfront - expect some movement...

Yours,

Philip

**Comment by philipmulcahy** [comment]
I've now built a (failing) integration test that reproduces a tax example you provided:
```
  {
    "test_id": "ORDER_SCRAPE_amazon.com_D01-4607619-0755448_2023-11-08",
    "passed": false,
    "defects": [
      "us_tax should be \"$1.42\" but we got \"$15.99\""
    ]
  }
```
how hard can it be to get it to pass.

**Comment by philipmulcahy** [comment]
1) on tax, how does https://www.mulcahyfamily.org/azad/azad_844b9078.zip look? (see [how-to-try-out-an-experimental-version](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version)) - if it looks good I'll queue it up for the next release.

2) _"I also noticed that an order that is for a digital purchase gets a digital order number in the report but amazon.com does not show it as a digital order (ID order number but rather like a regular order)."_
I'm not sure I understand this. Is D01-4607619-0755448 one of those? In the order detail page, the most descriptive text provided is "Legacy Ad-Free [Apps for Android] Sold By: WarnerMedia Global Digital Services, LLC", which makes me think that it's a movie stream or similar, and Amazon has failed to display it. If it's not on this page, it's going to be hard to get more detail than that.

3) In one of your emails, you mention _"Would it be possible to get a checkbox to exclude the item field from the scrape? Perhaps there aren't many that want that feature but I assume it would speed things up for those that do not need it."_
I scrape the items from the order detail page, which also supplies some of the per-order info (such as tax), so we'd not be able to skip fetching that page per order. I don't think there are any/many fetches at per-item cardinality. You might counter with _"but we could save some time not bothering to do the item processing even if we still have to fetch the order detail pages"_ - you'd be right, but it'd be a tiny saving - the vast majority of the time consumed is spent waiting for page fetches - extraction from those pages is pretty quick in comparison.
