### ISSUE TITLE
Recognize Refunds

### ISSUE THREAD

**Issue by blacktemplar** [philipmulcahy/azad#25]
I just saw that orders which got sent back and refunded are listed as expenses, is it somehow possible to recognize refunds and add a column or something with refunded or even don't list the expense.

**Comment by philipmulcahy** [comment]
You tell me: I haven’t found a way yet.
If you can figure out a way YOU could do it (as a human being clicking links) and explain it, then maybe we can add it as a feature (there’s no doubt it’d be useful…)

Philip

**Comment by blacktemplar** [comment]
I just checked my order history to find a few examples, it shouldn't be a big problem to parse that info.
First of all you see it in the orders list where normally the title says Delivered {date} it says Refunded. If an order has multiple items and only a part of them got refunded its splits the items and has one category Refunded (the same as it splits items if they got delivered on different dates).

Furthermore, in the Order details page you have an additional column in the Order Summary. Below the Grand Total there is a green column Refund Total which has a hover which also gives the refunded VAT. Then there is another field which you can open by clicking on Transactions and it shows when you got your refund.

Here is a screenshot of one example order detail:

![screenshot_20180702_113808](https://user-images.githubusercontent.com/3133334/42164699-2665ce72-7e07-11e8-9469-c5fada13664b.png)

**Comment by philipmulcahy** [comment]
This looks promising - might be a few days before I've got time - I'll update this ticket when I start work.
I've just merged a pull request from another user who didn't want to wait for me (if you're feeling keen).

P

**Comment by philipmulcahy** [comment]
Yay! Thanks @blacktemplar  I'll close this ticket.
Internationalization strategy: wait for de and fr/ca users to complain and provide the strings we need.
