### ISSUE TITLE
amazon.de no values for total

### ISSUE THREAD

**Issue by jonajp1** [philipmulcahy/azad#250]
On amazon.de there are no values for each total. At least each value is 0.00
![image](https://github.com/philipmulcahy/azad/assets/118084793/2f311260-b836-4a0a-824a-533cfc90b51f)

**Comment by philipmulcahy** [comment]
that's hard for me to debug: I've not got a .de account.
1) Does anyone else in Germany have the same problem?
2) If so, how are your chrome debugging skills?

**Comment by philipmulcahy** [comment]
I'm wondering if it is something to do with the numeric format... maybe it doesn't know that commas can be decimal separators as well as dots? Next time I have some time, I'll take my .fr account for a spin and see if I can reproduce.

**Comment by jonajp1** [comment]
> I'm wondering if it is something to do with the numeric format... maybe it doesn't know that commas can be decimal separators as well as dots? Next time I have some time, I'll take my .fr account for a spin and see if I can reproduce.

That were my first thoughts. I also think that the numeric format could be the reason. 
I read in the chrome reviews that another German Account has the same issue. 
I never tried chrome debugging, but I'm open to lern it.

**Comment by Chriss122** [comment]
ye, that must be the issue. 
I've noticed this also with my german account (, and .) are not correct recognized for German Accounts.

It would be glad to have an bugfix here or got someone a workaround to change it on our German site?

**Comment by philipmulcahy** [comment]
It’s near the front of my queue - I’m working on finishing a big change to how queries are processed (that’s been coming for a long time), and when that’s working, I’ll switch to a short list of comparatively easy bug. This is one of them - probably the easiest to fix, so likely to be first or second that I attempt.

Yours,

Philip

**Comment by philipmulcahy** [comment]
#209 is nearly done - I'm planning to work on this one next - I'm stuck at home doing an oncall shift on this coming Saturday (2023-12-23), so if it's quiet, that's when I'll get time to concentrate.

**Comment by philipmulcahy** [comment]
I think I may have got this working in: https://www.mulcahyfamily.org/azad/azad_2bf5f4ed.zip
Here's how to use such a test build: [how-to-try-out-an-experimental-version](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version).

This build also contains the latest work on #209 (shipments and csv download improvements).

I may not release this to the webstore version until I've slain a few other tickets that are in my queue, but feedback about whether it works or not for you would be super useful.

**Comment by Chriss122** [comment]
> I think I may have got this working in: https://www.mulcahyfamily.org/azad/azad_2bf5f4ed.zip Here's how to use such a test build: [how-to-try-out-an-experimental-version](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version).
> 
> This build also contains the latest work on #209 (shipments and csv download improvements).
> 
> I may not release this to the webstore version until I've slain a few other tickets that are in my queue, but feedback about whether it works or not for you would be super useful.

Thank you for your effort, I will test it as soon as possible and give you feedback. =)

**Comment by philipmulcahy** [comment]
pushing in v1.10.0: should be with y'all inside of 48h (google code review permitting)

**Comment by Chriss122** [comment]
> pushing in v1.10.0: should be with y'all inside of 48h (google code review permitting)

Thanks for that, I've tested it with the v 1.10.0 and not the experimental.

The recognition of the amounts now looks correct again in the list. However, no total "all" is generated or not totaled. 
Here I see again that the "all" = 0.00 and not 0,00 (possibly just a small error) =)?
Here is a screenshot.

![Screenshot](https://github.com/philipmulcahy/azad/assets/22147563/94926279-9cab-42f9-a87c-f9ad04de9180)


I wish you a happy new year
Greetings
