### ISSUE TITLE
Invoice Links selected, but not displayed or in .csv. Same as #225 

### ISSUE THREAD

**Issue by Sunshine-Oh-My** [philipmulcahy/azad#251]
Hi Philip. I have the same problem as above as a closed ticket #225 . It affects all orders, including previous years. Every other column works fine. Neither the displayed table or the excel spreadsheets have the invoice links. Shows the column with "invoice" title but all cells are blank for all orders.  I created a log file and screenshots. I sent an email with the ticket number225.  Thank you for your help. This is a great app!

**Comment by philipmulcahy** [comment]
deduping this to the now reopened #225
