### ISSUE TITLE
taxes are not displayed correctly on amazon.ca

### ISSUE THREAD

**Issue by belilan** [philipmulcahy/azad#258]
in Canada, we have several taxes, a federal one and a provincial one, depending which province you live in.
the results I got are completely incorrect.
Here is an examlple wher 2 taxes have been applied.

![image](https://github.com/philipmulcahy/azad/assets/155858707/5dd5a7a0-639c-4395-a53b-1377ec3d260f)
![image](https://github.com/philipmulcahy/azad/assets/155858707/79fa7e75-aebb-49d5-80d6-ae614f9b8125)

The total is correct: 15.52
The VAT column in the results is actually the item subtotal (total without taxes), but thats' fine, I'd just have to rename the column.
**The GST column is "0", instead of "0.69".**
The PST is correct.
I have checked the whole file, the GST column is always "0".

Thank you.

**Comment by philipmulcahy** [comment]
Please send debug json for an example order that exhibits the bad behaviour. (See the readme file to find out how)Sent from my phoneOn 7 Jan 2024, at 00:44, belilan ***@***.***> wrote:﻿
in Canada, we have several taxes, a federal one and a provincial one, depending which province you live in.
the results I got are completely incorrect.
Here is an examlple wher 2 taxes have been applied.
image.png (view on web)
image.png (view on web)
The total is correct: 15.52
The VAT column in the results is actually the item subtotal (total without taxes), but thats' fine, I'd just have to rename the column.
The GST column is "0", instead of "0.69".
The PST is correct.
I have checked the whole file, the GST column is always "0".
Thank you.

**Comment by belilan** [comment]
Hello, I have sent the json file by email.
I had to zip it since it was rejected by google.
Please confirm that you got it.

Thank you.
Alain



De : Philip Mulcahy ***@***.***>
Envoyé : Sunday, January 07, 2024 07:55
À : philipmulcahy/azad ***@***.***>
Cc : Alain Bensimon ***@***.***>; Author ***@***.***>
Objet : Re: [philipmulcahy/azad] taxes are not displayed correctly on amazon.ca (Issue #258)

Please send debug json for an example order that exhibits the bad behaviour. (See the readme file to find out how)Sent from my phoneOn 7 Jan 2024, at 00:44, belilan ***@***.***<mailto:***@***.***>> wrote:﻿
in Canada, we have several taxes, a federal one and a provincial one, depending which province you live in.
the results I got are completely incorrect.
Here is an examlple wher 2 taxes have been applied.
image.png (view on web)
image.png (view on web)
The total is correct: 15.52
The VAT column in the results is actually the item subtotal (total without taxes), but thats' fine, I'd just have to rename the column.
The GST column is "0", instead of "0.69".
The PST is correct.
I have checked the whole file, the GST column is always "0".
Thank you.

**Comment by philipmulcahy** [comment]
got it - thank you!

**Comment by philipmulcahy** [comment]
Hello @belilan!

Would you mind taking https://www.mulcahyfamily.org/azad/azad_16f86617.zip for a spin and see if it fixes the problem?
Here's how to use it: https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version

Yours,

Philip

**Comment by philipmulcahy** [comment]
I took a chance and included it in 1.10.1, which is rolling out in the next 48 hours.
It'd be great to know if it's worked!

**Comment by belilan** [comment]
Hi philip, yes it worked.
There’s still the VAT column that needs to be renamed, but that’s really minor.
The most important is that both GST and PST columns were populated.

Thank you so much for your support.
Alain

Envoyé de mon iPhone

Le 7 janv. 2024 à 17:44, Philip Mulcahy ***@***.***> a écrit :

﻿

I took a chance and included it in 1.10.1, which is rolling out in the next 48 hours.
It'd be great to know if it's worked!

**Comment by philipmulcahy** [comment]
cool!
I'd completely missed the VAT thing - let me git it some more thought.

**Comment by philipmulcahy** [comment]
first attempt fixed it for .ca and broke .co.uk - regrouping now

**Comment by belilan** [comment]
OMG.

De : Philip Mulcahy ***@***.***>
Envoyé : Monday, January 08, 2024 17:33
À : philipmulcahy/azad ***@***.***>
Cc : Alain Bensimon ***@***.***>; Mention ***@***.***>
Objet : Re: [philipmulcahy/azad] taxes are not displayed correctly on amazon.ca (Issue #258)


first attempt fixed it for .ca and broke .co.uk - regrouping now

**Comment by philipmulcahy** [comment]
Nailed it - I don't think I need you to test, but the code went in fb837af, and is in the queue for the next .

**Comment by belilan** [comment]
Awesome.
Thank you

Envoyé de mon iPhone

Le 8 janv. 2024 à 18:31, Philip Mulcahy ***@***.***> a écrit :

﻿

Nailed it - I don't think I need you to test, but the code went in fb837af<https://github.com/philipmulcahy/azad/commit/fb837affc55c5d4c6651709ac893da638f21919c>, and is in the queue for the next .

**Comment by philipmulcahy** [comment]
v.1.11.0 in review with the webstore: expect it to deploy in the next week
