### ISSUE TITLE
Additional Taxes

### ISSUE THREAD

**Issue by LTBComputers** [philipmulcahy/azad#26]
You guys are awesome! Would it be possible to add the actual taxes to the csv out put? In Canada we have two taxes which show as GST/HST and PST/RST/QST. This extension would be much more useful to Canadians if it showed each of these as a seperate column. This is what it looks like from an amazon order.

Order Summary
Item(s) Subtotal: CDN$ 39.99
Shipping & Handling: CDN$ 0.00
Total before tax: CDN$ 39.99
Estimated GST/HST: CDN$ 2.00
Estimated PST/RST/QST: CDN$ 2.80
Grand Total: CDN$ 44.79

**Comment by philipmulcahy** [comment]
What URL does that come from? (It’d reveal your order id but that’s pretty useless from a privacy invasion perspective).

**Comment by LTBComputers** [comment]
https://www.amazon.ca/gp/your-account/order-details/ref=oh_aui_or_o01_?ie=UTF8&orderID=701-0042736-4947442

I actually got it working, I just rewrote the extension and cloned the vat function adding:

const cad_gst = function(){
                            let a = getField(
                                ['GST', 'HST'].map(
                                    label => sprintf(
                                        '//div[contains(@id,"od-subtotals")]//' +
                                        'span[contains(text(),"%s") and not(contains(.,"Before"))]/' +
                                        'parent::div/following-sibling::div/span',
                                        label
                                    )
                                ).join('|'),
                                doc,
                                doc.documentElement
                            );
                            if( a !== "?") {
                                return a;
                            }
                            a = getField(
                                '//*[text()[contains(.,"GST") and not(contains(.,"Before"))]]',
                                doc,
                                doc.documentElement
                            );
                            if( a !== null ) {
                                const b = a.match(
                                    /VAT: *([-$£€0-9.]*)/);
                                if( b !== null ) {
                                    return b[1];
                                }
                            }
                            a = getField(
                                '//div[contains(@class,"a-row pmts-summary-preview-single-item-amount")]//' +
                                'span[contains(text(),"GST")]/' +
                                'parent::div/following-sibling::div/span',
                                doc,
                                doc.documentElement
                            );
                            if( a !== null ) {
                                const c = a.match(
                                    /VAT: *([-$£€0-9.]*)/);
                                if( c !== null ) {
                                    return c[1];
                                }
                            }
                            return "N/A";
                        }.bind(this);

                        const cad_pst = function(){
                            let a = getField(
                                ['PST', 'RST', 'QST'].map(
                                    label => sprintf(
                                        '//div[contains(@id,"od-subtotals")]//' +
                                        'span[contains(text(),"%s") and not(contains(.,"Before"))]/' +
                                        'parent::div/following-sibling::div/span',
                                        label
                                    )
                                ).join('|'),
                                doc,
                                doc.documentElement
                            );
                            if( a !== "?") {
                                return a;
                            }
                            a = getField(
                                '//*[text()[contains(.,"PST") and not(contains(.,"Before"))]]',
                                doc,
                                doc.documentElement
                            );
                            if( a !== null ) {
                                const b = a.match(
                                    /VAT: *([-$£€0-9.]*)/);
                                if( b !== null ) {
                                    return b[1];
                                }
                            }
                            a = getField(
                                '//div[contains(@class,"a-row pmts-summary-preview-single-item-amount")]//' +
                                'span[contains(text(),"PST")]/' +
                                'parent::div/following-sibling::div/span',
                                doc,
                                doc.documentElement
                            );
                            if( a !== null ) {
                                const c = a.match(
                                    /VAT: *([-$£€0-9.]*)/);
                                if( c !== null ) {
                                    return c[1];
                                }
                            }
                            return "N/A";
                        }.bind(this);


Then modified the resolve function:
          resolve({
                            postage: postage(),
                            gift: gift(),
                            vat: vat(),
                            gst: cad_gst(),
                            pst: cad_pst()
                        });

And added this to the table.js after vat:
  { field_name:'GST', type:'detail', property_name:'gst',
            is_numeric:true},
  { field_name:'PST', type:'detail', property_name:'pst',
            is_numeric:true},

Loaded the unpacked plugin and tested as working for me with the additional fields.

**Comment by LTBComputers** [comment]
![image](https://user-images.githubusercontent.com/15116767/42129069-4cd618f0-7c77-11e8-8d68-3f6a5e904569.png)

**Comment by philipmulcahy** [comment]
This is really cool!
Do you know how to fashion a pull request?
I’ve not looked at the code closely (it’ll be easier to do so as a PR), but I can imagine two issues we may need to think about in order to merge your code:
1) Does it break other countries?
2) If people add equivalent code for their own countries in the same fashion will it become (more) unwieldy?

Philip

**Comment by LTBComputers** [comment]
I've never done a pull request (still super new to git). I'll take a look at doing that.

It would defiantly become more unwieldy and other countries likely don't need gst and pst functionality. Checking if gst/pst exists and then contextually scraping it would probably be best? (mine assumes it exists). That would also probably be best long term to keep it sane if you wanted to extend it. I named them cad_gst and cad_pst, so that would keep it sane for awhile, but it might struggle with edge cases.

Check the url to see where the amazon page is regional to (.ca, .fr, etc.) then checking for appropriate taxes from there? Don't want to waste cycles checking for taxes that aren't going to be there.

**Comment by LTBComputers** [comment]
Ok I forked it, modified the two files and made a pull request.

**Comment by philipmulcahy** [comment]
Thank you!
I merged the code into a new branch and did a little more work...

`git checkout --track origin/cad_tax`

It's not broken .co.uk or .fr. Would you mind checking .ca and then I can merge into master and push out a new release?
Philip.

**Comment by philipmulcahy** [comment]
too slow - I've pushed (pretty sure it won't break non .ca users)
