### ISSUE TITLE
NOV missing

### ISSUE THREAD

**Issue by Marow** [philipmulcahy/azad#260]
Hi, when i try to get last 3month, i get data from 2023-10-16 up to today. 
But all orders from november (11) are missing...

**Comment by philipmulcahy** [comment]
please share your console log for such a failing run (after clearing the extension’s cache): see the README doc for how to capture the log.Yours,PhilipSent from my phoneOn 16 Jan 2024, at 20:10, M.S. ***@***.***> wrote:﻿
Hi, when i try to get last 3month, i get data from 2023-10-16 up to today.
But all orders from november (11) are missing...

**Comment by philipmulcahy** [comment]
https://github.com/philipmulcahy/azad/blob/master/README.md#how-to-save-a-log-file

**Comment by philipmulcahy** [comment]
Also, is it getting the date arithmetic right? what do you see on the control popup while the scrape is happening - this is what I see shortly after clicking the 3m button: 
<img width="147" alt="image" src="https://github.com/philipmulcahy/azad/assets/1668892/a848e318-a9eb-4af6-b859-e96680026e80">

**Comment by philipmulcahy** [comment]
Do the November orders get picked up if you scrape the whole of 2023?

**Comment by philipmulcahy** [comment]
I am not feeling the love here - is this a fire-and-forget in both github ticket and review form?
<img width="1116" alt="image" src="https://github.com/philipmulcahy/azad/assets/1668892/46aa96d7-782a-4511-8372-ebb169a2b2b1">
If you just want to complain without helping fix stuff, then just publish a flame on the review site with some swear words, and leave me alone - hopefully folks'll be able to gauge your credibility.

**Comment by philipmulcahy** [comment]
I am going to assume this is not a thing anymore.
If you are experiencing a similar issue, please post answers to the above questions in a new ticket, including console log.
Thanks,
Philip
