### ISSUE TITLE
Payment methods - missing credit card info

### ISSUE THREAD

**Issue by sbjps** [philipmulcahy/azad#262]
Hi All,

I do not see payment methods information including the last 4 digital of the credit card information for each transaction.

As shown below, some transactions have the last 4-digit credit card info - see (1). But the majority of the transactions are shown as (2) or (3) below. 

1) Visa ending in 8112: January 22, 2023: $13.08; 
2) 2023-05-10: $9.99; 
3) ending in : ; 

Not sure if anyone has run into the same issue?

Thanks a lot!

Best,
JPS

**Comment by philipmulcahy** [comment]
Hi JPS,

If you can see better info in the order detail page for 2 and/or 3, that the scrape is not picking up, then please send me [debug dump files ](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-save-and-send-an-order-debug-json-file)for example orders, and I'll try and figure out what's gone wrong.

Yours,

Philip

**Comment by philipmulcahy** [comment]
no response from user -> closing
