### ISSUE TITLE
No data for 2023

### ISSUE THREAD

**Issue by smg1054** [philipmulcahy/azad#263]
The extension works well for all years (even as far as 2012) except 2023, the year I need for my taxes. I can't figure out why. Any help would be appreciated.

**Comment by philipmulcahy** [comment]
That sounds pretty useless!
Have you worked through the readme suggestions? https://github.com/philipmulcahy/azad?tab=readme-ov-file#azad-amazon-order-history-reporter-chrome-extension

If that doesn't sort you out, then a console log (how-to instructions in that link above) is the next step.
It's possible you've got an order in 2023 that's killing the scraping code. If so I should be able to identify it from the log and then probably ask you for some more diagnostic info on that order to enable me to figure out a fix.

I'll keep this open for a few days: no log => assumption that you're fixed.

**Comment by smg1054** [comment]
I had gone through and tried before writing but it didn't work. As I said, all works perfectly for all other years than 2023. The scraping for 2023 comes up with: Showing 0 to 0 of 0 entries (and I did have a lot of entries in 2023, believe me! Maybe too many...?)
I've just tries again for both 2011 and 2024 and it works fine. Just 2023 seems to have the problem. I assume then that as you said, there might be one order that blocks the results.

**Comment by philipmulcahy** [comment]
Thanks. Next: get me a console log with all the filtering turned off.Sent from my phoneOn 1 Feb 2024, at 11:53, smg1054 ***@***.***> wrote:﻿
I had gone through and tried before writing but it didn't work. As I said, all works perfectly for all other years than 2023. The scraping for 2023 comes up with: Showing 0 to 0 of 0 entries (and I did have a lot of entries in 2023, believe me! Maybe too many...?)
I've just tries again for both 2011 and 2024 and it works fine. Just 2023 seems to have the problem. I assume then that as you said, there might be one order that blocks the results.

**Comment by smg1054** [comment]
I'm sorry  I'm not sure what you mean. For 2023, I really don't get any data. I can't download anything since there is nothing to download. Can you tell what the process is? I can download a CVS table for all the other years.

**Comment by philipmulcahy** [comment]
When you load an Amazon tab in chrome, the extension attempts to figure out what years are available. It should have logged those queries in the console, and what happened next.It is possible that Amazon serves something that is different (not necessarily wrong) from what the extensions knows how to parse. Seeing the log may help me narrow down what’s gone wrong. After that I might ask you to save some html from various urls and send them to me. Without you sharing your login credentials with me (you should not!), this is how we debug such problems where I cannot reproduce the symptoms on my own account.Sent from my phoneOn 3 Feb 2024, at 17:29, smg1054 ***@***.***> wrote:﻿
I'm sorry  I'm not sure what you mean. For 2023, I really don't get any data. I can't download anything since there is nothing to download. Can you tell what the process is? I can download a CVS table for all the other years.

**Comment by philipmulcahy** [comment]
no response from user -> closing

**Comment by scholzol** [comment]
I have the same problem. I'll try to create a console log.

**Comment by whisky23** [comment]
Yes, same here! I've cleared cache, cookies and more. But no results :-( Any idea?

**Comment by philipmulcahy** [comment]
Same story: you need to supply the requested diagnostics: if it were not working on my end I would have fixed it, so therefore something is different on your end: not saying it is not a bug, but I need your help to fix it.Sent from my phoneOn 21 Apr 2024, at 09:58, whisky23 ***@***.***> wrote:﻿
Yes, same here! I've cleared cache, cookies and more. But no results :-( Any idea?

**Comment by philipmulcahy** [comment]
I have a log from @scholzol - reopening

**Comment by philipmulcahy** [comment]
@scholzol I think it's blowing up when it tries to parse this page: https://www.amazon.de/gp/css/order-history?opt=ab&digitalOrders=1&unifiedOrders=1&returnTo=&orderFilter=year-2023&startIndex=0&language=en_GB&disableCsd=no-js

Are you able to capture the html for that page and send it via email?

Yours,

Philip

**Comment by scholzol** [comment]
will try.

**Comment by smg1054** [comment]
Hi Philip,

Is this what you need?
I'm sorry I couldn't figure out a log before...

Sandra
________________________________

**Comment by philipmulcahy** [comment]
Sorry - my day job has been pretty heavy!

The html @smg1054 (Sandra) sent me appears to only contain a cookie prompt, which would explain why the extension is/was getting stuck:

<img width="1152" alt="image" src="https://github.com/philipmulcahy/azad/assets/1668892/146545e4-a178-4578-9eac-8e353766896b">

I think that you need to 
1) visit the link and accept/reject the cookies 
2) and then refresh the page
3) re-try the extension

**If that doesn't work**, then 
4) click the extension's blue "force logout" button
5) refresh the original amazon link
6) log in and make sure you can see some orders
7) re-try the extension

Yours,

Philip

**Comment by philipmulcahy** [comment]
I am assuming this worked out and that everything is good.
If that's not so, and you just didn't get around to responding yet (it's not as if I have been super speedy, is it?) then please re-open this ticket!

**Comment by scholzol** [comment]
Hi Philip,
I tested it again, but it is still not working. Sorry for the late reply, but I was in vacation the last weeks. My main problem of understanding is, why it works for 2022, 2024 and not for 2023 ???

br
Olaf

**Comment by philipmulcahy** [comment]
Hi @scholzol,

Please can I have the console log for a failing scrape (e.g. what goes into the console log - with verbose/debug messages included) when you press the 2023 button?

The readme file (front page of this GitHub project has a section about capturing console logs.)

We will get to the bottom of this and get your taxes done.

philip

**Comment by philipmulcahy** [comment]
I see nothing in gmail for this (#263) since April -> assuming all is good.
