### ISSUE TITLE
Report broken down by items

### ISSUE THREAD

**Issue by danniboy** [philipmulcahy/azad#265]
I ran that report for the first time and I am seeing a few issues. Sometimes the amount per item/line is the item price as per the order and sometimes it is the total price which means if I have a column multiplying quantity and price the total is very much incorrect. In other instances, the item price seems to be a number I do not recognize.

The columns price and quantity multiplied together should add up to the subtotal (before tax, shipping, taxes etc) correct?  Mine appears to be roughly double the amount I was expecting but the issue is not happening to every line.

**Comment by philipmulcahy** [comment]
Hi @danniboy,

What report?
Is _"The columns price and quantity multiplied together should add up to the subtotal (before tax, shipping, taxes etc) correct?"_ a question, or a statement, or something else?
I think you may inadvertently assuming that I am telepathic and have access to your amazon account. I am sad to say that neither is currently the case.

Here's an article I think would be worth reading before we go further: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

And then (to avoid unnecessary further round trips), please read https://github.com/philipmulcahy/azad/blob/master/README.md#:how-to-save-and-send-an-order-debug-json-file

Then (please) send me marked up screenshots of specific misbehaviours and the corresponding order debug json files. If you value your privacy, you should read the second link carefully. I want to fix bugs, and I don't doubt you're suffering from one, but I need the right information from you to be able to do anything constructive. When I am able to reproduce the problem you're seeing, with the order data and mark-ups you send me, then I can understand what's going wrong, fix it, and add a regression test to make sure the bug doesn't come back. You'll probably have helped loads of other users!

Yours,

Philip

**Comment by danniboy** [comment]
The title of the post is broken **down by items** therefore I thought I was being clear that I selected the **items** radio box before running the report.

> The columns price and quantity multiplied together should add up to the subtotal (before tax, shipping, taxes etc) correct?" a question, or a statement, or something else

I thought this was both formed as a question and that the ending of a question mark made it clear.

I appreciate the link but I thought both this post, my previous posts as well as email correspondence with you have been rather thorough.

I ran both the **orders** report and the **items** report for the same period and with almost 283 orders and 32 digital orders I noticed the following

- The **items** report catches all of the orders but less than half of the digital orders.
- Of the 283 orders 17 had a difference in subtotal amount. As the **orders** report does not collect the amount from the subtotal field I ran my own scrape to do a comparison. I used my scrape report (order number and subtotal) and did a lookup of a pivot of the **items** report and compared the subtotal of each order. 1 order had 1 item had a "," instead of a "." in the amount as well as the wrong amount so that one gave an error and, obviously did not match. 13 orders had a subtotal amount difference that ranged from $167 to $19,000 and 4 orders had a difference of $9-$51.

I would recommend the orders report adding a subtotal column as well if for no other reason than to be able to easily check for bugs or inconsistencies in the different reports.

What further details do you want besides the log?

**Comment by philipmulcahy** [comment]
A wall of handcrafted text telling me lots of stuff is not useful without some toe hold enabling me to be able to reproduce the problem.
You've easily cleared the first hurdle: convincing me I need to do some work, but you're totally ignoring the next hurdle which is enabling me to do that work. Clearing the first hurdle with "more feeling" is a waste of your time, and it makes me feel stupid and helpless as well.

I don't think I need a log for this bug, In fact I'm pretty sure I didn't ask for one. What I do need is:

1) one or more order debug json files (see second link), 
and...
2) Some way to understand what you think is wrong with how the extension is handling those specific orders. A marked up screenshot of  each of the order rows in question in the relevant output table seems (to me, from experience) to be the best route to get that.

While hypotheses of the mechanism of the bug are potentially interesting and useful, it's best if they are separated from the factual information about the bug.

Yours,

Philip

p.s.

The order debug json function was created precisely for this situation: "Hey! You're scraping my order, but not giving me the values I expect".
The console log is mostly only useful if we've not gotten as far as displaying a specific order (or perhaps any orders).
