### ISSUE TITLE
Price blank on software items

### ISSUE THREAD

**Issue by gfwalker7** [philipmulcahy/azad#272]
First, I LOVE this software!  It fills a critical need and works beautifully around Amazon's obstinate stupidity.  I am happy to contribute to the charity.

I scraped the 150 items in my 2023 orders (https://www.amazon.com/gp/css/order-history?ref_=nav_orders_first).  I reviewed every item in the CSV spreadsheet, in the process of adding my own category information, and only the two software items in the list had blank prices.  (The two products were TurboTax and Bitdefender.)  I buy VERY little software from Amazon, since it's generally always cheaper elsewhere, so I don't have a big sample to report.  Searching for "software" in my previous years' orders, I haven't purchased more than 1 or 2 software items per year for the last six years.  I recommend finding someone who buys a LOT of software to replicate the problem.

**Comment by jwarkentin** [comment]
I ran into the same thing tonight. Except it showed the correct information for two TurboTax orders from March but was missing the price for my December TurboTax order. Whatever changed to cause this issue doesn't seem to impact older orders.

**Comment by philipmulcahy** [comment]
Hi @gfwalker7 and @jwarkentin,

Please can you both share one or two [order json dump files](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-save-and-send-an-order-debug-json-file)  for such “bad” orders. These will enable me to see the html I need to fix this.

Yours,

Philip

**Comment by philipmulcahy** [comment]
not feeling the love here - I will close this in a week if no-one shows up
