### ISSUE TITLE
Duplicate line items in report

### ISSUE THREAD

**Issue by DKNCinc1** [philipmulcahy/azad#276]
Azad report prints duplicate entries for every ordered item. Everything is identical for the two lines, but there are two line items for every one item ordered. I could not figure out how to send a debug report, but here is a screen shot. 
 
![Image 4-28-24 at 5 40 PM](https://github.com/philipmulcahy/azad/assets/168377287/1d5ce539-6784-4d42-8d85-095fb2489c1b)

**Comment by philipmulcahy** [comment]
Please can you send me a debug json file for one of the orders that has duplicates in that screenshot? There is a paragraph on how to do this in the readme on the front page of the project’s GitHub page.Sent from my iPadOn 28 Apr 2024, at 22:43, DKNCinc1 ***@***.***> wrote:﻿
Azad report prints duplicate entries for every ordered item. Everything is identical for the two lines, but there are two line items for every one item ordered. I could not figure out how to send a debug report, but here is a screen shot.
Image.4-28-24.at.5.40.PM.jpeg (view on web)

**Comment by philipmulcahy** [comment]
it's been ~7 weeks and I've not seen a response here or in gmail -> closed.

**Comment by DKNCinc1** [comment]
I’m so sorry to not have responded sooner. This email went to my spam
folder. Has anyone else reported this bug besides me?
