### ISSUE TITLE
Request: Include Payment method in the data

### ISSUE THREAD

**Issue by davincidecoder** [philipmulcahy/azad#279]
Hey Philip! Thanks for the great extension. Please consider including the "Payment method" data from the invoices too in the data/CSV. Thanks

**Comment by philipmulcahy** [comment]
Have you seen the "transaction" column in the shipping table, or the "payments" column in the orders table?
It has entries like: "24 May 2024 - MasterCard ending in 7623:: £5.49" - This appears to duplicate the info in the Payment Method section of the few invoices I've looked at.

Amazon don't make it at all easy to glean this info, and it doesn't work for digital orders.
Invoices: the extension sometimes shows links to invoices, but it does NOT fetch them and therefore does not have access to the data inside them. There are engineering and practical reasons why this is so, and I'm not considering "fixing" them.
