### ISSUE TITLE
a button for each month?

### ISSUE THREAD

**Issue by fieldinggrocery** [philipmulcahy/azad#288]
apologies if this is the wrong place, or if already added and I'm missing it. I'm not familiar with github yet, but I think I've read through everything relevant

I thought specific months were an option (as opposed to previous 30/60/90 days from the time of generating a report, similar to the yearly buttons)

though I see now I may be misinterpreting the description 
("...scraping only the most recent 1, 2 or 3 months...") ("...UPDATE 2023-08-19 Commercial features batch 1 (ASIN, 1/2/3 months)...")

Huge thanks to Philip and anyone else who has worked on this product, very helpful (FWIW I am subscribed)

**Comment by philipmulcahy** [comment]
This is the right place!
I replied to your email just now, and then found this ticket.
Here's an abbreviated version of my response:

> I considered putting a date range in the UI when I first got the 1,2,3 months feature working, but it would make the control popup significantly more complicated for "vanilla" users without a reasonably hefty re-design, which there doesn't seem to be the appetite for at the moment. 
> 
> The killer benefit of 1,2,3M is the avoidance of pulling a full year's worth of order detail, which for busy accounts can take significant time, and when commercial users are doing weekly/monthly reporting, the time savings can be significant - I suspect that they're often filtering the rows down once the table's displayed/downloaded.
> 
> I'm slightly confused by "really all I need is to..." because date range selection and sort order are not quite the same thing.
> Would you be willing to explain your use case in a bit more detail? It's possible the solution is already in your reach without any code changes.

After Ryan's explained his use-case (assuming I cannot suggest a nice work-around), then let's see if enough users are interested. If they are, I'll look at adding the capability to the UI and stick it into the commercial feature set.

Yours,

Philip
