### ISSUE TITLE
Building a similar tool to collect Target orders

### ISSUE THREAD

**Issue by justinhaaheim** [philipmulcahy/azad#289]
Hey @philipmulcahy, 
I'm starting work on a similar chrome extension to collect target.com order data, and I'm wondering if you'd be open to me picking your brain a bit about how best to go about that, and any lessons you've learned from building this tool for Amazon orders. I've spent a bit of time with this codebase already and have at least a cursory understanding of how it works. I'm a senior software engineer at a bay area tech company, in case that's helpful for calibrating what our conversation might be like. A single, brief conversation via email/discord/zoom (or whatever your preference is) would be helpful! And no worries if this isn't a good time.

If you're open to it perhaps I can send you my contact info at azadextension@gmail.com (to avoid posting it here). And of course feel free to close this issue.

**Comment by philipmulcahy** [comment]
I'm going to have a bit more time free in about a month - by all means send me details and we can arrange a call.
Not all of the lessons I've learned are embodied in the project (to my shame!).

**Comment by justinhaaheim** [comment]
Sent!
