### ISSUE TITLE
digital orders are missing

### ISSUE THREAD

**Issue by ballle98** [philipmulcahy/azad#292]
None of my digital orders are appearing in the report.

**Comment by philipmulcahy** [comment]
Have you worked through all the self help stuff on the README doc yet?Sent from my phoneOn 25 Sep 2024, at 22:00, Lee Ballard ***@***.***> wrote:﻿
None of my digital orders are appearing in the report.

**Comment by ballle98** [comment]
@philipmulcahy yes I cleared cache logged out and back in.  Deleted all the amazon cookies.  I get all the normal orders (the ones that begin with 3 digits - 7 digits - 7 digits.  I don't see any digital orders with order IDs that start with "D".

**Comment by philipmulcahy** [comment]
Ah - this is new to me.
Can you please share a console log from such a failing run (starting with an empty cache).
Yours,
Philip

**Comment by philipmulcahy** [comment]
this might be the same as #293, which is where I'm going to be working for a bit until either it's fixed or we're doomed.

**Comment by philipmulcahy** [comment]
I will close this in a couple of days unless someone confirms they've tested https://mulcahyfamily.org/azad/azad_72fe13cb.zip (see https://github.com/philipmulcahy/azad/issues/293#issuecomment-2387961775) and found it to not fix this issue.
Plan is to address the multiple item count issue (e.g. more than one instance of the same SKU) and then release the fix more generally.

**Comment by philipmulcahy** [comment]
high confidence that #293 is the same thing, so closing this: please join in there!
