### ISSUE TITLE
Issue with Shipment Tracking in Extension

### ISSUE THREAD

**Issue by GngAuth** [philipmulcahy/azad#294]
Hi,

I've been using your extension for the past few months, and it's been working great until recently. Over the last 3-5 days, I've encountered an issue with the shipment tracking feature. Even though tracking information is available on Amazon, the extension frequently returns "No shipment" for orders.

Some of the items are marked as delivered, while others are shipped, but the extension isn't reflecting this correctly. Initially, this affected just 1 or 2 orders, but now about 50% of the shipments are showing incorrect data.

I’ve tried uninstalling and reinstalling the extension, clearing the cache, and updating my browser, but the issue persists.

I’d appreciate any guidance or a resolution for this.

Thank you!

**Comment by philipmulcahy** [comment]
That sounds annoying - initial suspicion in my head is pointing to Amazon changing their site template, thus breaking the scraping code.
Can you please share a console log from a clean (empty cache) run that exhibits the bad behaviour and a couple of order debug dump json files for orders that are misbehaving (instructions on how to do both, including protecting your personal data from the internet are in the readme file at the front of the GitHub site)?
Yours,
Philip

**Comment by philipmulcahy** [comment]
see progress on #293!
