### ISSUE TITLE
Enhancement - Current Price, not paid price. 

### ISSUE THREAD

**Issue by ProSam** [philipmulcahy/azad#297]
I came by AZAD trying to find a way to better track my Amazon Vine shipments for tax purposes.  Viners receive items from Amazon at $0 in return for high quality reviews.  When AZAD scrapes orders it pulls the price paid which is all $0.00.  

Would it be possible to have a column for the current price the item is selling for from the Amazon listing?  

Are bounties for enhancement requests possible?

**Comment by philipmulcahy** [comment]
Bounties: not really thought about it.Would you be willing to share an order dump JSON file of such an order so I can take a look?Sent from my phoneOn 17 Oct 2024, at 00:21, ProSam ***@***.***> wrote:﻿
I came by AZAD trying to find a way to better track my Amazon Vine shipments for tax purposes.  Viners receive items from Amazon at $0 in return for high quality reviews.  When AZAD scrapes orders it pulls the price paid which is all $0.00.
Would it be possible to have a column for the current price the item is selling for from the Amazon listing?
Are bounties for enhancement requests possible?
