### ISSUE TITLE
There's a problem displaying your orders right now.

### ISSUE THREAD

**Issue by mike391** [philipmulcahy/azad#298]
Ran the extension over my orders and now I can't view the orders page in amazon on my desktop or my phone. I just get the message
"There's a problem displaying your orders right now."

Is there some kind of api limit or is my account flagged or something?

**Comment by philipmulcahy** [comment]
I have not seen this behaviour or heard of it before, so either it’s new or unrelated to using azad.Sent from my phoneOn 19 Oct 2024, at 02:24, Mike ***@***.***> wrote:﻿
Ran the extension over my orders and now I can't view the orders page in amazon on my desktop or my phone. I just get the message
"There's a problem displaying your orders right now."
Is there some kind of api limit or is my account flagged or something?

**Comment by philipmulcahy** [comment]
Anyone else seeing this?
@mike391 are you still stuck?

**Comment by philipmulcahy** [comment]
closing this in a day or two if no-one piles in with the help I need
