### ISSUE TITLE
Extension won't work for me

### ISSUE THREAD

**Issue by csutton1998** [philipmulcahy/azad#300]
I've read all of the instructions, cleared my cache through chrome, cleared cookies, went to site data (chrome) and deleted everything from Amazon. Extension shows idle and the force logout and clear cache buttons are not clickable. I don't know what else to do.

**Comment by philipmulcahy** [comment]
Next step is to share a console log of the Amazon page you have open after clicking on a year button. Instructions in the readme (front page of the GitHub site)

Yours, 

Philip

Sent from my phone
>

**Comment by csutton1998** [comment]
I don’t get a year button. I get the idle page. Is there a console log for that? The clear cache and force logout buttons don’t work either.

 

Kind Regards,

 

Claudia J Sutton | Purchasing Manager

RNB Merchandise

114 Southchase BLVD

Fountain Inn, SC 29644

803-427-6077

 <http://www.rnbmerchandise.com/> www.rnbmerchandise.com

**Comment by philipmulcahy** [comment]
1) Screenshots of the sequence of things you observe2) console log from a logged in Amazon page (preferably one you can see some your orders on so we know you have successfully logged on to Amazon. If you are not seeing years, this is where they should be coming from and the console log might offer clues.Sent from my phoneOn 25 Oct 2024, at 17:47, csutton1998 ***@***.***> wrote:﻿
I don’t get a year button. I get the idle page. Is there a console log for that? The clear cache and force logout buttons don’t work either.



 



Kind Regards,



 



Claudia J Sutton | Purchasing Manager



RNB Merchandise



114 Southchase BLVD



Fountain Inn, SC 29644



803-427-6077



 <http://www.rnbmerchandise.com/> www.rnbmerchandise.com







 



From: Philip Mulcahy ***@***.***> 

Sent: Friday, October 25, 2024 12:45 PM

To: philipmulcahy/azad ***@***.***>

Cc: csutton1998 ***@***.***>; Author ***@***.***>

Subject: Re: [philipmulcahy/azad] Extension won't work for me (Issue #300)



 



Next step is to share a console log of the Amazon page you have open after clicking on a year button. Instructions in the readme (front page of the GitHub site)



Yours, 



Philip



Sent from my phone

**Comment by csutton1998** [comment]
![Screenshot 2024-10-25 141138](https://github.com/user-attachments/assets/bebcd2ee-17cf-4254-b9ea-f1d8e594d9ee)

**Comment by philipmulcahy** [comment]
Hi Claudia,

Thanks for the screen shot.

I don't recognize the page layout - is it a selling account? If so, Azad doesn't support those, as I've not got such an account.
It's not necessarily unfeasible to build support for selling accounts, but I would have thought that Amazon would provide better real-time access to such an account's data than consumer accounts get, hence why I am not besieged with requests for scraping such data.

If I've got the wrong end of the stick and your account (like mine) is for a simple consumer, then are you planning on sharing the console log? (I can't see one on this ticket or in the inbox of azad-extension at gmail.com

Yours,

Philip

**Comment by csutton1998** [comment]
Ah! Okay. Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
