### ISSUE TITLE
Purchases using Audible credit shown as a price instead of left blank

### ISSUE THREAD

**Issue by NicoleWillson** [philipmulcahy/azad#301]
I buy a lot of books on audible using credit.  When I downloaded my report, they showed up as various dollar amounts - not sure where the prices come from whether current or the price at the time of purchase.  Since the cost of those credits show up elsewhere these should either not be shown or should have the price left blank.

**Comment by philipmulcahy** [comment]
Hello Nicole,

Please can you share screenshots and order debug json files (see the README for how to capture them) for examples of each type of misbhaviour so I can investigate?

Yours,

Philip
