### ISSUE TITLE
Error - No years present

### ISSUE THREAD

**Issue by feldmane17** [philipmulcahy/azad#305]
Got this error code:

QUEUED_COUNT:0; RUNNING_COUNT:0; COMPLETED_COUNT:0; CACHE_HIT_COUNT:0; ERROR_COUNT:0

**Comment by philipmulcahy** [comment]
What is the difference between this one and #304?Sent from my phoneOn 4 Dec 2024, at 19:04, feldmane17 ***@***.***> wrote:﻿
Got this error code:
QUEUED_COUNT:0; RUNNING_COUNT:0; COMPLETED_COUNT:0; CACHE_HIT_COUNT:0; ERROR_COUNT:0
