### ISSUE TITLE
Support for Amazon.eg

### ISSUE THREAD

**Issue by KareemWaheed** [philipmulcahy/azad#306]
Hi,

Thank you for your work on this prohect! Unfortunately, I noticed that the extension doesn't work with amazon.eg domain. It seems the website is not supported in the domains list. Could you please look into adding support for it? This would be greatly appreciated.

Thank you.

**Comment by philipmulcahy** [comment]
Hi Kareem,

Please can you share some html examples from .eg
More specifically:
1) the e.g equivalent of https://www.amazon.co.uk/gp/your-account/order-history
2) an order detail page, similar to https://www.amazon.co.uk/gp/your-account/order-details?ie=UTF8&orderID=206-4239987-2987547

Yours,

Philip

**Comment by philipmulcahy** [comment]
it seems Kareem's need is insufficiently motivating for them to supply the data required.
