### ISSUE TITLE
Dates don't sort - they're treated as strings

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#31]
Goal: render all dates as iso8601 (YYYY-MM-DD) and ignore the storm of complaints about wanting dates in format X.
moment.js looks kinda promising but we'll need to hint it with locale from navigator.language or possibly using the site name.
`
moment('29 mai 2018', ['DD MMM YYYY'], 'fr').toISOString()
`

**Comment by philipmulcahy** [comment]
@blacktemplar FYI

**Comment by philipmulcahy** [comment]
This seems to be working for .com, .fr and .co.uk. Probably works for .de and .it (but cannot test). Don't know about  .ca.
Please make a new ticket referring to this one if you see dates not like YYYY-MM-DD in the output.
To fix, I'll need to know the site (such as amazon.it), and a couple of examples of the non converted date.

**Comment by ScottMcNay** [comment]
Question: does Amazon change the date format if you set a locale in the HttpRequest header? If so, this might get you away from the need to use a library.
