### ISSUE TITLE
File Encoding: Format Errors

### ISSUE THREAD

**Issue by Richyread** [philipmulcahy/azad#33]
Background:  Acquire all orders for 2017 (for which Amazon reports 95 entries)
Site: Amazon.co.uk
Plugin Version: 1.8.12

Issue:
After successfully generating a report using the plugin/extension, the output .CSV file when viewed using Excel (Office 2013) has additional HTML characters transposed into the file. These characters (specifically the 'Â' symbol) are **not** visible within the text file themselves, which suggests an encoding mismatch somewhere along the line.

After a quick google of the 'Â' symbol there's a few posts which suggests changing the encoding format from **UTF-8** to **UTF-8-BOM**. 

I'm not going to pretend I understand the subtleties...merely confirm that adjusting the format does resolve the issue! :-)

E.g in the sample screenshot below on the right is the unaltered .CSV from the plugin and on the left is a copy that has been 'Saved As' using the UTF-8-BOM encoding format within Notepad++

![image](https://user-images.githubusercontent.com/7470850/43043211-281f8c88-8d86-11e8-9b3e-548c3adc0f4c.png)

As I say i'm not an expert here in any form just presenting what is a successful workaround, so adjusting the encoding long-term may not be what you'd expect the ideal approach/best practice to be etc.

Hope this helps.

Richy.

**Comment by philipmulcahy** [comment]
Hi Richy!
This is very interesting. Thanks for putting such effort into making a clear report.
I'm far from being a unicode expert. My initial readings suggest it should be OK to inject the BOM into the file unless the consuming app is "naive". The question is... what happens in that case, and how many people will complain. I'll do some experiments when I get a few moments and report back here.
Philip

**Comment by philipmulcahy** [comment]
Missing BOM definitely breaks Excel. Other tools I have don't seem to care, so I'm going to figure out how to inject it into the CSV file.

**Comment by philipmulcahy** [comment]
@Richyread fixed in 1.8.13 - please kick the tyres and close if you're happy.

**Comment by Richyread** [comment]
Tyres kicked.... she's a runner! :wink:

Thanks for resolving so quickly.

Cheers!!

Richy.
