### ISSUE TITLE
Empty 'items' field for most of the orders

### ISSUE THREAD

**Issue by 75tpus** [philipmulcahy/azad#4]
Hello

very useful addin thank you. Last time I tried in June it successfully downloaded all the orders. 

Now it seems most of the orders (including those in the past which worked ok) have empty 'items' column - can you please see if its reproducible on your end and something easy to fix?

Thank you!
75

**Comment by philipmulcahy** [comment]
You're right - it's happening to me too: I'll take a closer look.

**Comment by philipmulcahy** [comment]
Hi 75tpus,

I think I've fixed it - Amazon had changed their code, which broke azad.
1.3.0 is propagating in the chrome web store right now.
Please let me know if it's fixed for you in 1.3.0 once you have it and have a moment to check.
There are no other meaningful changes other than experimental addition of amazon.de support.

Regards,

Philip

**Comment by 75tpus** [comment]
Hi Philip,  
confirmed as fixed! 
Thank you very much!!
