### ISSUE TITLE
Tabs not showing after new install of Chrome and extension on MacOS MBP

### ISSUE THREAD

**Issue by Pingumann** [philipmulcahy/azad#40]
Hi Philip,

No Tabs appear after installation of Chrome and the extension.

1.  Chrome Version 70.0.3538.110 (Official Build) (64-bit). 
2. OS:  MacOS 10.13.6 (Eng UK). All Apps & programmes installed are in UK Eng.
3. Chrome login with smile.chrome.de, no Tabs appear in the "Meine Bestellungen" (My Orders).

Regards,
Pingumann

**Comment by philipmulcahy** [comment]
Are you able to attach the chrome console log so I can figure out what’s happening?

**Comment by philipmulcahy** [comment]
went dark
