### ISSUE TITLE
Enhancement: List transactions

### ISSUE THREAD

**Issue by klemens-u** [philipmulcahy/azad#41]
Hi Philip,

thank you very much for this useful extension.

I'm missing one thing though. Would it possible to include a list of "transactions"?
It's a major PITA to map the bank account transactions to amazon orders.

In more detail:

- On my bank accound I have two transactions "€ 33,25" and "€ 12,01"
- The corresponding order is listed with the sum of "€53,39". That's also the amount listed on your spreadsheet.

Now I check my bank account and have lots of amazon transaction amounts which I can't map to the orders.

It would be great if you could add the transaction values.
It could work something like this:

- For every order on the Amazon orders page
- click on "Order Details"
- click on "Transactions"
- List all transactions on your report table in a new column "transactions"
Separate by comma or newlines

If you find time for this extension I would appreciate it a lot.
And I would like to buy you a coffee or two :-)

Best regards from Vienna/Austria
Klemens

**Comment by philipmulcahy** [comment]
Hi Klemens,

Your strategy sounds well thought out.
I will take a look: might be several weeks before I get time to code on it though…

P

**Comment by ScottMcNay** [comment]
I think that people would be interested in using this extension for three primary purposes:

1. Payment information (you currently need to look this up individually, if not using this extension).
2. Shipment information (ditto).
3. Item information (there's a report... but it doesn't include digital purchases).

With this in mind, suggest a separate table for a list of transactions (some orders would be multiple rows), combined with, if reasonable, the list of items being paid with that transaction.

I have a list of 12 issues and enhancement requests to submit (one appears to be an Amazon bug); implementing this request as a separate table with each transaction on its own row would take care of two items on my list.

This extension is a vast improvement over what Amazon offers; if you have a way to make donations, such as a PayPal account, I'll be happy to contribute to your coffee/beer/tea/chocolate/expensive bottled water/etc. fund,

**Comment by ScottMcNay** [comment]
@klemens-u, see my spreadsheet at https://github.com/philipmulcahy/azad/issues/43; you'd copy-n-paste your data into cell A2, and the extra columns will calculate. Does that do what you want?

**Comment by ehforscher** [comment]
@ScottMcNay re: your comment on Feb 16, I would also be interested in shipment information! I would be specifically interested in the items below.

- selected shipping speed (available for any order by clicking on the Order Invoice)
- time of delivery (available in a popup by clicking on Track Package and then clicking on the Tracking ID link)
- Actual shipping speed (which can be done by extracting time and date information from the         tracking popup)

Two notes:

1. I am based in the U.S., so these specifics are based on that user experience, but I would be curious to know if this is standard amongst the countries you support. 
2. The level of information available appears to vary by the age of the order (i.e., for any orders older than about two months I can no longer track packages).

@philipmulcahy I could imagine this might be a fair amount of work, so I'll echo the sentiment above that I'm more than willing to donate! Although I can't say I support bottled water :). Happy to open a new enhancement thread too if easier.

**Comment by polychromeuganda** [comment]
There may be a more straightforward way to achieve this purpose than to parse it from the order history if that HTML is poorly formed. The transaction is history available directly. ( Your account>Your Payments>Transactions ) In the USA a menu tree leading there is not self-evident, but other Amazon pages link to it at:

    https://www.amazon.com/cpe/yourpayments/transactions      (in the USA).

The transaction list includes both payments and refunds. The html appears to be reasonably well structured using a date container and transaction widgets containing order id,  payment source, amount and for external payment processors, amazon, amazon marketplace, amazon payments, and kindle payments are identified, but an Amazon Gift Card transactions does not identify the other party. 

   There are two drawbacks to this page:

1. It offers up one page of history at a time beginning with the present with no way to query a time range of interest other than to use "Next Page" ad nauseum.
2. WholeFoods orders are conspicuously absent from this transaction report.

**Comment by gfwalker7** [comment]
@polychromeuganda - Transaction list is interesting, but on each page, it's missing from 1 to 6 transaction dates.  I've attached a sample screen-shot.  Each transaction starts with the order date, and three of them are missing (they're replaced with a full-width underline, for some reason).  Going to the original orders, the date displays normally, so it's not missing there.  The data doesn't seem reliable.

![Transaction List with Missing Dates](https://github.com/philipmulcahy/azad/assets/153405391/9a9df3f6-d17c-4c6d-8a60-3d712c909713)

**Comment by philipmulcahy** [comment]
Thanks for reporting. To understand and fix this I am going to need some order dump json files to match at least a couple of the screenshotted examples. Instructions for how to get them and send them while protecting your PII are in the readme(on front page of the GitHub project): search for json.Sent from my phoneOn 18 Apr 2024, at 06:46, gfwalker7 ***@***.***> wrote:﻿
@polychromeuganda - Transaction list is interesting, but on each page, it's missing from 1 to 6 transaction dates.  I've attached a sample screen-shot.  Each transaction starts with the order date, and three of them are missing (they're replaced with a full-width underline, for some reason).  Going to the original orders, the date displays normally, so it's not missing there.  The data doesn't seem reliable.
Transaction.List.with.Missing.Dates.jpg (view on web)

**Comment by gfwalker7** [comment]
@philipmulcahy It's not clear to me that this is something that you need to "fix", since it's not directly connected to Azad.  I was simply pointing out that there seems to be a quality issue with Amazon's Transaction History Report (https://www.amazon.com/cpe/yourpayments/transactions, as reported by @polychromeuganda), which makes it markedly less useful.  

But in case I don't fully understand the context of your request, I have generated three order-dump json files for you on orders that are OK in Azad but that are missing the order date in the Amazon Transaction History Report.  They have been emailed to azadextension@gmail.com as you requested.

**Comment by philipmulcahy** [comment]
thanks @gfwalker7 I now think you are telling me that Azad is correctly capturing what Amazon is showing you, but that the Amazon data is patchy. Is this correct?
If so, then you're right that there's nothing I can do.
If not, then your files might enable me to improve Azad.
