### ISSUE TITLE
Issue: "To" field is all "N/A" for all orders

### ISSUE THREAD

**Issue by ScottMcNay** [philipmulcahy/azad#45]
Amazon.com on Windows 10.
Maybe it's different for others, but the To column is all "N//A" for me. Is this supposed to be the recipient?

**Comment by philipmulcahy** [comment]
For me this only populates when it's not your normal address - like if you send it to a friend or a box
Is it a deal breaker for you?

**Comment by ScottMcNay** [comment]
Not a deal-breaker, but if you poke at it, I've used multiple addresses, and it always shows N/A for me; see the sample attached to another ticket.

**Comment by Abba-** [comment]
Always shows N/A for me, and yes deal breaker for me as I use some sort of tracker to see who I ordered stuff for.

**Comment by ScottMcNay** [comment]
This is currently working as of 2020-05-10.
