### ISSUE TITLE
Issue: No totals for digital items

### ISSUE THREAD

**Issue by ScottMcNay** [philipmulcahy/azad#46]
Amazon.com on Windows 10.
No totals for digital items. This appears to be related to Amazon using a different order summary page for digital orders.

**Comment by philipmulcahy** [comment]
any better in 1.8.26 @ScottMcNay ?

**Comment by philipmulcahy** [comment]
Also, this is definitely not happening in the UK for 2019 digital orders or old US ones (I don't have any new US ones)
If it's still happening, can you post the html for the invoice and details page of an impacted order?

**Comment by ScottMcNay** [comment]
It's now about half & half; see the sample and log I attached to another ticket.
