### ISSUE TITLE
Amazon Issue: Payment is sometimes duplicated

### ISSUE THREAD

**Issue by ScottMcNay** [philipmulcahy/azad#48]
Amazon.com on Windows 10
Payment is sometimes duplicated, so that, for example, there are two $10 payments listed for a single $10 item. This appears to be an Amazon bug. If you decide not to work around it, might want to mention it so people know.

Here's an example of the broken transaction listing:

Transactions
Amount Payment Method Status
$111.15 Visa ending in xxxx Charged on November 16, 2018
$111.15 Visa ending in xxxx Charged on November 16, 2018
Total: $111.15

**Comment by philipmulcahy** [comment]
is there any chance you could send me the html files for the order detail and the linked invoice for this example?

**Comment by ScottMcNay** [comment]
It looks like Amazon fixed this; I now only have 5 records with 2 transactions, and I think all are refunds.
