### ISSUE TITLE
Enhancement: CSV loses the HTML links

### ISSUE THREAD

**Issue by ScottMcNay** [philipmulcahy/azad#49]
Amazon.com on Windows 10
CSV loses the HTML links; suggest adding extra column(s) for that in order to keep the info.

**Comment by philipmulcahy** [comment]
1) links can be tricky in csv depending on what's reading the file.
2) you can easily add a formula column in your SS to reconstruct those links - something like ="https://www.amazon.co.uk/gp/your-account/order-details/ref=oh_aui_or_o01_?ie=UTF8&orderID=" & A2
