### ISSUE TITLE
Enhancement: Blank amount

### ISSUE THREAD

**Issue by ScottMcNay** [philipmulcahy/azad#51]
Amazon.com on Windows 10.
One order came up with blank amounts; turned out to be $0.00, and payment was "gift card". It looks like this was a re-send for a missing shipment. Still, I'd expect it to at least show "0.00" and maybe "gift card" instead of just a blank spot; the blank kinda implies that it didn't collect the info.

**Comment by philipmulcahy** [comment]
I think this is going to very hard to get working given the info visible - do you have plans to attempt it? If not, I'm going to close this ticket

**Comment by ScottMcNay** [comment]
This is one of the items on the sample I attached to another ticket. Probably not worth the bother given that Amazon documents it poorly, and they seem to do it differently at times.

**Comment by ScottMcNay** [comment]
I'll test to see if I figured this out.

**Comment by philipmulcahy** [comment]
closing, without prejudice.
