### ISSUE TITLE
US digital orders broken

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#53]
Amazon have changed the layout of both the order list view and the order detail page, breaking most columns in the report output.
I've just pushed 1.8.22 as a partial fix - it restores order id (and associated link) and the order total amount.
Depending on interest in this bug and available time, I'll look at fixing the other columns next.
I'm interested to know if people are seeing problems with .com for non digital orders as well. I only have a couple in my account, and they look fine to me.

**Comment by thebat11** [comment]
this extension gives me the amount only. nothing else works.. no date no postage, no gift, no tax, ? is there a working extension? thanks

**Comment by philipmulcahy** [comment]
I have something that’s looking a bit more healthy in dev, but it’s not properly tested yet.
Would you be able to share the html from a digital order page on this ticket? (I don’t have any US digital orders on my US account)

**Comment by philipmulcahy** [comment]
I think this is probably fixed in 1.8.26 - please let me know if I'm wrong
