### ISSUE TITLE
Amazon.es payments column empty for non-kindle.

### ISSUE THREAD

**Issue by aladagemre** [philipmulcahy/azad#54]
In Amazon.ES,

* for kindle e-book orders, prices are displayed in **payments** column (ex: 2019-03-16: EUR 8,99;) but the field **to** is N/A
* the rest of the rows have blank **payments** column but correct **to** field (my name).
*  Columns **total postage gift VAT refund** are all pending for all the records. 
* On console I can see the following errors:

```order.js:168 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Order.<anonymous> (order.js:168)
    at Order.<anonymous> (order.js:421)
    at RequestScheduler.<anonymous> (request_scheduler.js:190)
request_scheduler.js:176 Finished https://www.amazon.es/gp/your-account/order-details/ref=oh_aui_or_o01_?ie=UTF8&orderID=171-0505481-0301938 with queue size 162
request_scheduler.js:135 Executing https://www.amazon.es/gp/your-account/order-details/ref=oh_aui_or_o01_?ie=UTF8&orderID=171-4497824-8671568 with queue size 161 and priority 171-4497824-8671568```

**Comment by philipmulcahy** [comment]
I think we need a bit more of the log to figure out what's going on
