### ISSUE TITLE
Missing Dates, "?" instead

### ISSUE THREAD

**Issue by aswatkins** [philipmulcahy/azad#56]
My report for 2019 with 242 entries has nothing in the date fields other than a question mark.
[amazon_order_history.xlsx](https://github.com/philipmulcahy/azad/files/3293601/amazon_order_history.xlsx)

Using Amazon.com from US.

**Comment by philipmulcahy** [comment]
still happening in 1.8.26

**Comment by philipmulcahy** [comment]
@aswatkins - I think this is fixed. Do you think differently?
I am going to close this issue - please feel free to re-open if needed.
Philip

**Comment by aswatkins** [comment]
OK.

Sent from my iPad

> On Dec 11, 2019, at 2:16 PM, Philip Mulcahy <notifications@github.com> wrote:
> 

﻿
@aswatkins - I think this is fixed. Do you think differently?
I am going to close this issue - please feel free to re-open if needed.
Philip
