### ISSUE TITLE
Enhancement: Add troubleshooting button

### ISSUE THREAD

**Issue by ScottMcNay** [philipmulcahy/azad#63]
Add a troubleshooting (or some other name) button next to the year buttons, for people to click when they don't get the results they expect. Have it open a page which tells them they need to click on a year button in order to see a blue button, etc. Have it explain how to save and submit a log. Have it explain how to sanitize the csv file so that it doesn't reveal too much info (clear column B, delete redundant rows, etc). Etc.

**Comment by philipmulcahy** [comment]
I think that the orange and blue buttons are super confusing (and it was me that bodged them in the first place)
@ScottMcNay your challenge (should you choose to accept it) - come up with a better UI that supports the current capabilities, allows improvements and is reasonably simple for me (or someone else) to code.
