### ISSUE TITLE
Totals shows NaN

### ISSUE THREAD

**Issue by maziac** [philipmulcahy/azad#85]
If an entry in the table does not contain a number the totals show "page=NaN; all=NaN".
I would suggest to ignore non-numbers when calculating the totals.

This happens for various purchased items, here is an example (also as screenshot):

item="Digitaler Amazon.de Gutschein (A wie Amazon);" => total="Grand Total:", payments="UNKNOWN"

This does not happen only for "Gutschein" but also for other items. Maybe this happens for digital items only because I saw it also when purchasing a game digitally.

![order_history](https://user-images.githubusercontent.com/3081973/68543010-1f280580-03b2-11ea-87ee-8b4fbc328402.jpg)

**Comment by philipmulcahy** [comment]
That shouldn’t happen - I am pretty busy right at the minute, but I will take a look when I get some time.

**Comment by philipmulcahy** [comment]
I think I might have fixed this in 1.9.1 which is rolling out right about now.

**Comment by philipmulcahy** [comment]
no response - assuming fixed

**Comment by maziac** [comment]
Yes, "Gutschein" does not cause NaN anymore.
