### ISSUE TITLE
CSV download shows pending

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#88]
Lots of users are reporting that their CSV downloads are full of "pending" despite the in-browser table showing the values they're expecting.

**Comment by philipmulcahy** [comment]
I can reproduce this issue so it should be straightforward to fix (famous last words!)
Fields impacted: (to, date, total, postage, gift, VAT, refund)

**Comment by philipmulcahy** [comment]
I think it's fixed in v1.9.3 - publishing right now...
Let me know if it works for you!

**Comment by ScottMcNay** [comment]
I just tested... It works now for me for 2011 and 2018, but no download for
2019, which has a transaction which fails to scrape.

You said something about a timeout, but I don't remember seeing anything in
the code for timing out.

--Scott.

**Comment by philipmulcahy** [comment]
Is this a failure to show the table for 2019 (re https://github.com/philipmulcahy/azad/issues/86) or that once the table is displayed, the csv button doesn't work?
Either way, I guess a console log file would be valuable, especially given that at least some of the users are reporting the two fixes I pushed this week have worked for them.
Thanks for letting me know all is not well!

**Comment by philipmulcahy** [comment]
@ScottMcNay any chance you're on a local dev copy that hasn't got the changes in 1.9.2 and 1.9.3? (long shot, but I'm hoping...)

**Comment by ScottMcNay** [comment]
No, I uninstalled the dev copy and installed the store copy. It appears
works fine, except 2019 has an unresolved issue with one transaction
showing as pending. I'll see about looking at it tomorrow to see if I can
fix that.

--Scott.

**Comment by ScottMcNay** [comment]
Just noticed another issue in 1.9.3: some order IDs are duplicated.

Sorry, I don't have enough of the big picture yet to understand all of what
the code is doing.

--Scott.

**Comment by philipmulcahy** [comment]
@ScottMcNay I suspect your issues are not the same as the one covered by this ticket: it's for people who've not managed to get anything displayed for 2019, whereas your screen shot shows some (perhaps too many) orders displayed for 2019. I'm going to shut this ticket down to avoid spamming everyone. Let's make two new tickets: for the dupes and the "transaction which fails to scrape."
