### ISSUE TITLE
.CA GST not working

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#92]
A few users have complained about this.
I don't have a Canadian account, so am going to need some help from a CA user.
With any luck, it should only involve giving me a single file upload on this ticket which will contain scrape data from up to 10 of your orders, including one that shows the problem with missing GST.
Let me know if you're happy to share this data (which would show what you bought in those 10 orders, but not give any more access to your account.)

**Comment by LTBComputers** [comment]
I just was looking at this, I worked on the last CA one. I'll fork a copy and make a new pull request once I test it working.

**Comment by philipmulcahy** [comment]
closing without prejudice (looks like we closed https://github.com/philipmulcahy/azad/pull/94, but I've not been great at issue hygiene)
