### ISSUE TITLE
Enhancement: Multiple Accounts

### ISSUE THREAD

**Issue by LandonSchropp** [philipmulcahy/azad#93]
First, thanks for building this great extension! It's saving me a ton of time.

Would it be possible to extend this extension to support multiple accounts?

Thanks!

**Comment by philipmulcahy** [comment]
What would multiple account support look like?
(I have a couple of uk accounts and US and FR as well, and it "works" on all of them.
It does _not_ work on all of them at the same time though - that'd probably require the extension to hold the credentials on your behalf, which would be asking users to put a lot more trust in a free extension written by a backend developer (me) who is just playing at frontends and doesn't have anyone to do security reviews.

**Comment by LandonSchropp** [comment]
Thanks for the reply!

My main use case is that my wife and I both have separate Amazon accounts. When I do our budgeting, I occasionally need to look at her account to determine how to categorize expenses. When I tried to do that with azad, it only showed the purchases for my account. Both accounts are on `smile.amazon.com`.

For me, the ideal would be to aggregate both accounts into the same list. Amazon leaves me signed into both, and I can switch between one and the other, so it's possible the extension could do some of the switching for me. Barring that, it would still be helpful to have the extension display whatever the currently signed in account is. That way, I could open up an incognito window when doing my budgeting.

I'm happy to contribute to this if you're on board and could point me in the right direction. 🙂

**Comment by ScottMcNay** [comment]
@LandonSchropp, how about saving to a spreadsheet? You can then have both spreadsheets open separately. There's a button in the upper-left corner to save the data.

**Comment by philipmulcahy** [comment]
I'm going to close this without prejudice - if someone can think of a compelling use-case that isn't already reasonably supported AND a safe and feasible way to do authentication then we can definitely reopen it.
